// Code generated by go run gob_gen.go; DO NOT EDIT.

package filesystem

import (
	"android/soong/android"
	"bytes"
	"github.com/google/blueprint/gobtools"
)

// begin of android_device.go
func init() {
	ApexKeyPathInfoGobRegId = gobtools.RegisterType(func() gobtools.CustomDec { return new(ApexKeyPathInfo) })
}

func (r ApexKeyPathInfo) Encode(ctx gobtools.EncContext, buf *bytes.Buffer) error {
	var err error

	if err = gobtools.EncodeInterface(ctx, buf, r.ApexKeyPath); err != nil {
		return err
	}
	return err
}

func (r *ApexKeyPathInfo) Decode(ctx gobtools.EncContext, buf *bytes.Reader) error {
	var err error

	if val2, err := gobtools.DecodeInterface(ctx, buf); err != nil {
		return err
	} else if val2 == nil {
		r.ApexKeyPath = nil
	} else {
		r.ApexKeyPath = val2.(android.Path)
	}

	return err
}

var ApexKeyPathInfoGobRegId int16

func (r ApexKeyPathInfo) GetTypeId() int16 {
	return ApexKeyPathInfoGobRegId
}

// end of android_device.go

// begin of bootimg.go
func init() {
	BootimgInfoGobRegId = gobtools.RegisterType(func() gobtools.CustomDec { return new(BootimgInfo) })
	ramdiskFragmentInfoGobRegId = gobtools.RegisterType(func() gobtools.CustomDec { return new(ramdiskFragmentInfo) })
	ramdiskFragmentsInfoGobRegId = gobtools.RegisterType(func() gobtools.CustomDec { return new(ramdiskFragmentsInfo) })
}

func (r BootimgInfo) Encode(ctx gobtools.EncContext, buf *bytes.Buffer) error {
	var err error

	if err = gobtools.EncodeInt(buf, int(r.Type)); err != nil {
		return err
	}

	if r.Cmdline == nil {
		if err = gobtools.EncodeInt(buf, -1); err != nil {
			return err
		}
	} else {
		if err = gobtools.EncodeInt(buf, len(r.Cmdline)); err != nil {
			return err
		}
		for val1 := 0; val1 < len(r.Cmdline); val1++ {
			if err = gobtools.EncodeString(buf, r.Cmdline[val1]); err != nil {
				return err
			}
		}
	}

	if err = gobtools.EncodeInterface(ctx, buf, r.Kernel); err != nil {
		return err
	}

	if err = gobtools.EncodeInterface(ctx, buf, r.Dtb); err != nil {
		return err
	}

	if err = gobtools.EncodeInterface(ctx, buf, r.Bootconfig); err != nil {
		return err
	}

	if err = gobtools.EncodeInterface(ctx, buf, r.Output); err != nil {
		return err
	}

	if err = gobtools.EncodeInterface(ctx, buf, r.SignedOutput); err != nil {
		return err
	}

	if err = gobtools.EncodeInterface(ctx, buf, r.PropFileForMiscInfo); err != nil {
		return err
	}

	if err = gobtools.EncodeString(buf, r.HeaderVersion); err != nil {
		return err
	}

	if err = gobtools.EncodeBool(buf, r.IsPrebuilt); err != nil {
		return err
	}
	return err
}

func (r *BootimgInfo) Decode(ctx gobtools.EncContext, buf *bytes.Reader) error {
	var err error

	var val2 int
	err = gobtools.DecodeInt(buf, &val2)
	if err != nil {
		return err
	}
	r.Type = bootImageType(val2)

	var val5 int
	err = gobtools.DecodeInt(buf, &val5)
	if err != nil {
		return err
	}
	if val5 != -1 {
		r.Cmdline = make([]string, val5)
		for val6 := 0; val6 < int(val5); val6++ {
			err = gobtools.DecodeString(buf, &r.Cmdline[val6])
			if err != nil {
				return err
			}
		}
	}

	if val9, err := gobtools.DecodeInterface(ctx, buf); err != nil {
		return err
	} else if val9 == nil {
		r.Kernel = nil
	} else {
		r.Kernel = val9.(android.Path)
	}

	if val11, err := gobtools.DecodeInterface(ctx, buf); err != nil {
		return err
	} else if val11 == nil {
		r.Dtb = nil
	} else {
		r.Dtb = val11.(android.Path)
	}

	if val13, err := gobtools.DecodeInterface(ctx, buf); err != nil {
		return err
	} else if val13 == nil {
		r.Bootconfig = nil
	} else {
		r.Bootconfig = val13.(android.Path)
	}

	if val15, err := gobtools.DecodeInterface(ctx, buf); err != nil {
		return err
	} else if val15 == nil {
		r.Output = nil
	} else {
		r.Output = val15.(android.Path)
	}

	if val17, err := gobtools.DecodeInterface(ctx, buf); err != nil {
		return err
	} else if val17 == nil {
		r.SignedOutput = nil
	} else {
		r.SignedOutput = val17.(android.Path)
	}

	if val19, err := gobtools.DecodeInterface(ctx, buf); err != nil {
		return err
	} else if val19 == nil {
		r.PropFileForMiscInfo = nil
	} else {
		r.PropFileForMiscInfo = val19.(android.Path)
	}

	err = gobtools.DecodeString(buf, &r.HeaderVersion)
	if err != nil {
		return err
	}

	err = gobtools.DecodeBool(buf, &r.IsPrebuilt)
	if err != nil {
		return err
	}

	return err
}

var BootimgInfoGobRegId int16

func (r BootimgInfo) GetTypeId() int16 {
	return BootimgInfoGobRegId
}

func (r ramdiskFragmentInfo) Encode(ctx gobtools.EncContext, buf *bytes.Buffer) error {
	var err error

	if err = gobtools.EncodeInterface(ctx, buf, r.Output); err != nil {
		return err
	}

	if err = gobtools.EncodeString(buf, r.Ramdisk_name); err != nil {
		return err
	}

	if err = gobtools.EncodeInterface(ctx, buf, r.RootDir); err != nil {
		return err
	}
	return err
}

func (r *ramdiskFragmentInfo) Decode(ctx gobtools.EncContext, buf *bytes.Reader) error {
	var err error

	if val2, err := gobtools.DecodeInterface(ctx, buf); err != nil {
		return err
	} else if val2 == nil {
		r.Output = nil
	} else {
		r.Output = val2.(android.Path)
	}

	err = gobtools.DecodeString(buf, &r.Ramdisk_name)
	if err != nil {
		return err
	}

	if val5, err := gobtools.DecodeInterface(ctx, buf); err != nil {
		return err
	} else if val5 == nil {
		r.RootDir = nil
	} else {
		r.RootDir = val5.(android.Path)
	}

	return err
}

var ramdiskFragmentInfoGobRegId int16

func (r ramdiskFragmentInfo) GetTypeId() int16 {
	return ramdiskFragmentInfoGobRegId
}

func (r ramdiskFragmentsInfo) Encode(ctx gobtools.EncContext, buf *bytes.Buffer) error {
	var err error

	if r == nil {
		if err = gobtools.EncodeInt(buf, -1); err != nil {
			return err
		}
	} else {
		if err = gobtools.EncodeInt(buf, len(r)); err != nil {
			return err
		}
		for val1 := 0; val1 < len(r); val1++ {
			if err = r[val1].Encode(ctx, buf); err != nil {
				return err
			}
		}
	}
	return err
}

func (r *ramdiskFragmentsInfo) Decode(ctx gobtools.EncContext, buf *bytes.Reader) error {
	var err error

	var val2 int
	err = gobtools.DecodeInt(buf, &val2)
	if err != nil {
		return err
	}
	if val2 != -1 {
		(*r) = make([]ramdiskFragmentInfo, val2)
		for val3 := 0; val3 < int(val2); val3++ {
			if err = (*r)[val3].Decode(ctx, buf); err != nil {
				return err
			}
		}
	}

	return err
}

var ramdiskFragmentsInfoGobRegId int16

func (r ramdiskFragmentsInfo) GetTypeId() int16 {
	return ramdiskFragmentsInfoGobRegId
}

// end of bootimg.go

// begin of bootloader.go
func init() {
	bootloaderInfoGobRegId = gobtools.RegisterType(func() gobtools.CustomDec { return new(bootloaderInfo) })
}

func (r bootloaderInfo) Encode(ctx gobtools.EncContext, buf *bytes.Buffer) error {
	var err error

	if err = gobtools.EncodeInterface(ctx, buf, r.bootloaderImg); err != nil {
		return err
	}
	return err
}

func (r *bootloaderInfo) Decode(ctx gobtools.EncContext, buf *bytes.Reader) error {
	var err error

	if val2, err := gobtools.DecodeInterface(ctx, buf); err != nil {
		return err
	} else if val2 == nil {
		r.bootloaderImg = nil
	} else {
		r.bootloaderImg = val2.(android.Path)
	}

	return err
}

var bootloaderInfoGobRegId int16

func (r bootloaderInfo) GetTypeId() int16 {
	return bootloaderInfoGobRegId
}

// end of bootloader.go

// begin of dtboimg.go
func init() {
	DtboImgInfoGobRegId = gobtools.RegisterType(func() gobtools.CustomDec { return new(DtboImgInfo) })
}

func (r DtboImgInfo) Encode(ctx gobtools.EncContext, buf *bytes.Buffer) error {
	var err error

	if err = gobtools.EncodeInterface(ctx, buf, r.PropFileForMiscInfo); err != nil {
		return err
	}
	return err
}

func (r *DtboImgInfo) Decode(ctx gobtools.EncContext, buf *bytes.Reader) error {
	var err error

	if val2, err := gobtools.DecodeInterface(ctx, buf); err != nil {
		return err
	} else if val2 == nil {
		r.PropFileForMiscInfo = nil
	} else {
		r.PropFileForMiscInfo = val2.(android.Path)
	}

	return err
}

var DtboImgInfoGobRegId int16

func (r DtboImgInfo) GetTypeId() int16 {
	return DtboImgInfoGobRegId
}

// end of dtboimg.go

// begin of filesystem.go
func init() {
	InstalledFilesStructGobRegId = gobtools.RegisterType(func() gobtools.CustomDec { return new(InstalledFilesStruct) })
	InstalledModuleInfoGobRegId = gobtools.RegisterType(func() gobtools.CustomDec { return new(InstalledModuleInfo) })
	FilesystemInfoGobRegId = gobtools.RegisterType(func() gobtools.CustomDec { return new(FilesystemInfo) })
	FullInstallPathInfoGobRegId = gobtools.RegisterType(func() gobtools.CustomDec { return new(FullInstallPathInfo) })
	FilesystemDefaultsInfoGobRegId = gobtools.RegisterType(func() gobtools.CustomDec { return new(FilesystemDefaultsInfo) })
}

func (r InstalledFilesStruct) Encode(ctx gobtools.EncContext, buf *bytes.Buffer) error {
	var err error

	if err = gobtools.EncodeInterface(ctx, buf, r.Txt); err != nil {
		return err
	}

	if err = gobtools.EncodeInterface(ctx, buf, r.Json); err != nil {
		return err
	}
	return err
}

func (r *InstalledFilesStruct) Decode(ctx gobtools.EncContext, buf *bytes.Reader) error {
	var err error

	if val2, err := gobtools.DecodeInterface(ctx, buf); err != nil {
		return err
	} else if val2 == nil {
		r.Txt = nil
	} else {
		r.Txt = val2.(android.Path)
	}

	if val4, err := gobtools.DecodeInterface(ctx, buf); err != nil {
		return err
	} else if val4 == nil {
		r.Json = nil
	} else {
		r.Json = val4.(android.Path)
	}

	return err
}

var InstalledFilesStructGobRegId int16

func (r InstalledFilesStruct) GetTypeId() int16 {
	return InstalledFilesStructGobRegId
}

func (r InstalledModuleInfo) Encode(ctx gobtools.EncContext, buf *bytes.Buffer) error {
	var err error

	if err = gobtools.EncodeString(buf, r.Name); err != nil {
		return err
	}

	if err = gobtools.EncodeString(buf, r.Variation); err != nil {
		return err
	}

	if err = gobtools.EncodeBool(buf, r.Prebuilt); err != nil {
		return err
	}
	return err
}

func (r *InstalledModuleInfo) Decode(ctx gobtools.EncContext, buf *bytes.Reader) error {
	var err error

	err = gobtools.DecodeString(buf, &r.Name)
	if err != nil {
		return err
	}

	err = gobtools.DecodeString(buf, &r.Variation)
	if err != nil {
		return err
	}

	err = gobtools.DecodeBool(buf, &r.Prebuilt)
	if err != nil {
		return err
	}

	return err
}

var InstalledModuleInfoGobRegId int16

func (r InstalledModuleInfo) GetTypeId() int16 {
	return InstalledModuleInfoGobRegId
}

func (r FilesystemInfo) Encode(ctx gobtools.EncContext, buf *bytes.Buffer) error {
	var err error

	if err = gobtools.EncodeInterface(ctx, buf, r.Output); err != nil {
		return err
	}

	if err = gobtools.EncodeInterface(ctx, buf, r.SignedOutputPath); err != nil {
		return err
	}

	if err = gobtools.EncodeInterface(ctx, buf, r.FileListFile); err != nil {
		return err
	}

	if err = r.RootDir.Encode(ctx, buf); err != nil {
		return err
	}

	if r.ExtraRootDirs == nil {
		if err = gobtools.EncodeInt(buf, -1); err != nil {
			return err
		}
	} else {
		if err = gobtools.EncodeInt(buf, len(r.ExtraRootDirs)); err != nil {
			return err
		}
		for val1 := 0; val1 < len(r.ExtraRootDirs); val1++ {
			if err = gobtools.EncodeInterface(ctx, buf, r.ExtraRootDirs[val1]); err != nil {
				return err
			}
		}
	}

	if err = r.RebasedDir.Encode(ctx, buf); err != nil {
		return err
	}

	if err = gobtools.EncodeString(buf, r.ModuleName); err != nil {
		return err
	}

	if err = gobtools.EncodeInterface(ctx, buf, r.BuildImagePropFile); err != nil {
		return err
	}

	if r.BuildImagePropFileDeps == nil {
		if err = gobtools.EncodeInt(buf, -1); err != nil {
			return err
		}
	} else {
		if err = gobtools.EncodeInt(buf, len(r.BuildImagePropFileDeps)); err != nil {
			return err
		}
		for val2 := 0; val2 < len(r.BuildImagePropFileDeps); val2++ {
			if err = gobtools.EncodeInterface(ctx, buf, r.BuildImagePropFileDeps[val2]); err != nil {
				return err
			}
		}
	}

	if r.SpecsForSystemOther == nil {
		if err = gobtools.EncodeInt(buf, -1); err != nil {
			return err
		}
	} else {
		if err = gobtools.EncodeInt(buf, len(r.SpecsForSystemOther)); err != nil {
			return err
		}
		for val3, val4 := range r.SpecsForSystemOther {
			if err = gobtools.EncodeString(buf, val3); err != nil {
				return err
			}
			if err = val4.Encode(ctx, buf); err != nil {
				return err
			}
		}
	}

	if r.FullInstallPaths == nil {
		if err = gobtools.EncodeInt(buf, -1); err != nil {
			return err
		}
	} else {
		if err = gobtools.EncodeInt(buf, len(r.FullInstallPaths)); err != nil {
			return err
		}
		for val5 := 0; val5 < len(r.FullInstallPaths); val5++ {
			if err = r.FullInstallPaths[val5].Encode(ctx, buf); err != nil {
				return err
			}
		}
	}

	if err = r.InstalledFilesDepSet.Encode(ctx, buf); err != nil {
		return err
	}

	if err = gobtools.EncodeInterface(ctx, buf, r.ErofsCompressHints); err != nil {
		return err
	}

	if err = gobtools.EncodeInterface(ctx, buf, r.SelinuxFc); err != nil {
		return err
	}

	if err = gobtools.EncodeInterface(ctx, buf, r.FilesystemConfig); err != nil {
		return err
	}

	if err = r.Owners.Encode(ctx, buf); err != nil {
		return err
	}

	if err = gobtools.EncodeBool(buf, r.HasFsverity); err != nil {
		return err
	}

	if err = gobtools.EncodeInterface(ctx, buf, r.PropFileForMiscInfo); err != nil {
		return err
	}

	val6 := r.PartitionSize == nil
	if err = gobtools.EncodeBool(buf, val6); err != nil {
		return err
	}
	if !val6 {
		if err = gobtools.EncodeInt64(buf, (*r.PartitionSize)); err != nil {
			return err
		}
	}

	if err = gobtools.EncodeBool(buf, r.UseAvb); err != nil {
		return err
	}

	if err = gobtools.EncodeString(buf, r.AvbAlgorithm); err != nil {
		return err
	}

	if err = gobtools.EncodeString(buf, r.AvbHashAlgorithm); err != nil {
		return err
	}

	if err = gobtools.EncodeInterface(ctx, buf, r.AvbKey); err != nil {
		return err
	}

	if err = gobtools.EncodeString(buf, r.PartitionName); err != nil {
		return err
	}

	if err = gobtools.EncodeBool(buf, r.NoFlashall); err != nil {
		return err
	}

	if err = gobtools.EncodeBool(buf, r.HasOrIsRecovery); err != nil {
		return err
	}

	if err = gobtools.EncodeInterface(ctx, buf, r.checkVintfLog); err != nil {
		return err
	}

	if err = gobtools.EncodeBool(buf, r.Prebuilt); err != nil {
		return err
	}
	return err
}

func (r *FilesystemInfo) Decode(ctx gobtools.EncContext, buf *bytes.Reader) error {
	var err error

	if val2, err := gobtools.DecodeInterface(ctx, buf); err != nil {
		return err
	} else if val2 == nil {
		r.Output = nil
	} else {
		r.Output = val2.(android.Path)
	}

	if val4, err := gobtools.DecodeInterface(ctx, buf); err != nil {
		return err
	} else if val4 == nil {
		r.SignedOutputPath = nil
	} else {
		r.SignedOutputPath = val4.(android.Path)
	}

	if val6, err := gobtools.DecodeInterface(ctx, buf); err != nil {
		return err
	} else if val6 == nil {
		r.FileListFile = nil
	} else {
		r.FileListFile = val6.(android.Path)
	}

	if err = r.RootDir.Decode(ctx, buf); err != nil {
		return err
	}

	var val10 int
	err = gobtools.DecodeInt(buf, &val10)
	if err != nil {
		return err
	}
	if val10 != -1 {
		r.ExtraRootDirs = make([]android.Path, val10)
		for val11 := 0; val11 < int(val10); val11++ {
			if val13, err := gobtools.DecodeInterface(ctx, buf); err != nil {
				return err
			} else if val13 == nil {
				r.ExtraRootDirs[val11] = nil
			} else {
				r.ExtraRootDirs[val11] = val13.(android.Path)
			}
		}
	}

	if err = r.RebasedDir.Decode(ctx, buf); err != nil {
		return err
	}

	err = gobtools.DecodeString(buf, &r.ModuleName)
	if err != nil {
		return err
	}

	if val17, err := gobtools.DecodeInterface(ctx, buf); err != nil {
		return err
	} else if val17 == nil {
		r.BuildImagePropFile = nil
	} else {
		r.BuildImagePropFile = val17.(android.Path)
	}

	var val20 int
	err = gobtools.DecodeInt(buf, &val20)
	if err != nil {
		return err
	}
	if val20 != -1 {
		r.BuildImagePropFileDeps = make([]android.Path, val20)
		for val21 := 0; val21 < int(val20); val21++ {
			if val23, err := gobtools.DecodeInterface(ctx, buf); err != nil {
				return err
			} else if val23 == nil {
				r.BuildImagePropFileDeps[val21] = nil
			} else {
				r.BuildImagePropFileDeps[val21] = val23.(android.Path)
			}
		}
	}

	var val24 int
	err = gobtools.DecodeInt(buf, &val24)
	if err != nil {
		return err
	}
	if val24 != -1 {
		r.SpecsForSystemOther = make(map[string]android.PackagingSpec, val24)
		for val25 := 0; val25 < int(val24); val25++ {
			var val26 string
			var val27 android.PackagingSpec
			err = gobtools.DecodeString(buf, &val26)
			if err != nil {
				return err
			}
			if err = val27.Decode(ctx, buf); err != nil {
				return err
			}
			r.SpecsForSystemOther[val26] = val27
		}
	}

	var val31 int
	err = gobtools.DecodeInt(buf, &val31)
	if err != nil {
		return err
	}
	if val31 != -1 {
		r.FullInstallPaths = make([]FullInstallPathInfo, val31)
		for val32 := 0; val32 < int(val31); val32++ {
			if err = r.FullInstallPaths[val32].Decode(ctx, buf); err != nil {
				return err
			}
		}
	}

	if err = r.InstalledFilesDepSet.Decode(ctx, buf); err != nil {
		return err
	}

	if val36, err := gobtools.DecodeInterface(ctx, buf); err != nil {
		return err
	} else if val36 == nil {
		r.ErofsCompressHints = nil
	} else {
		r.ErofsCompressHints = val36.(android.Path)
	}

	if val38, err := gobtools.DecodeInterface(ctx, buf); err != nil {
		return err
	} else if val38 == nil {
		r.SelinuxFc = nil
	} else {
		r.SelinuxFc = val38.(android.Path)
	}

	if val40, err := gobtools.DecodeInterface(ctx, buf); err != nil {
		return err
	} else if val40 == nil {
		r.FilesystemConfig = nil
	} else {
		r.FilesystemConfig = val40.(android.Path)
	}

	if err = r.Owners.Decode(ctx, buf); err != nil {
		return err
	}

	err = gobtools.DecodeBool(buf, &r.HasFsverity)
	if err != nil {
		return err
	}

	if val44, err := gobtools.DecodeInterface(ctx, buf); err != nil {
		return err
	} else if val44 == nil {
		r.PropFileForMiscInfo = nil
	} else {
		r.PropFileForMiscInfo = val44.(android.Path)
	}

	var val46 bool
	if err = gobtools.DecodeBool(buf, &val46); err != nil {
		return err
	}
	if !val46 {
		var val45 int64
		err = gobtools.DecodeInt64(buf, &val45)
		if err != nil {
			return err
		}
		r.PartitionSize = &val45
	}

	err = gobtools.DecodeBool(buf, &r.UseAvb)
	if err != nil {
		return err
	}

	err = gobtools.DecodeString(buf, &r.AvbAlgorithm)
	if err != nil {
		return err
	}

	err = gobtools.DecodeString(buf, &r.AvbHashAlgorithm)
	if err != nil {
		return err
	}

	if val52, err := gobtools.DecodeInterface(ctx, buf); err != nil {
		return err
	} else if val52 == nil {
		r.AvbKey = nil
	} else {
		r.AvbKey = val52.(android.Path)
	}

	err = gobtools.DecodeString(buf, &r.PartitionName)
	if err != nil {
		return err
	}

	err = gobtools.DecodeBool(buf, &r.NoFlashall)
	if err != nil {
		return err
	}

	err = gobtools.DecodeBool(buf, &r.HasOrIsRecovery)
	if err != nil {
		return err
	}

	if val57, err := gobtools.DecodeInterface(ctx, buf); err != nil {
		return err
	} else if val57 == nil {
		r.checkVintfLog = nil
	} else {
		r.checkVintfLog = val57.(android.Path)
	}

	err = gobtools.DecodeBool(buf, &r.Prebuilt)
	if err != nil {
		return err
	}

	return err
}

var FilesystemInfoGobRegId int16

func (r FilesystemInfo) GetTypeId() int16 {
	return FilesystemInfoGobRegId
}

func (r FullInstallPathInfo) Encode(ctx gobtools.EncContext, buf *bytes.Buffer) error {
	var err error

	if err = gobtools.EncodeBool(buf, r.RequiresFullInstall); err != nil {
		return err
	}

	if err = r.FullInstallPath.Encode(ctx, buf); err != nil {
		return err
	}

	if err = gobtools.EncodeInterface(ctx, buf, r.SourcePath); err != nil {
		return err
	}

	if err = gobtools.EncodeString(buf, r.SymlinkTarget); err != nil {
		return err
	}

	if err = gobtools.EncodeBool(buf, r.IsDir); err != nil {
		return err
	}
	return err
}

func (r *FullInstallPathInfo) Decode(ctx gobtools.EncContext, buf *bytes.Reader) error {
	var err error

	err = gobtools.DecodeBool(buf, &r.RequiresFullInstall)
	if err != nil {
		return err
	}

	if err = r.FullInstallPath.Decode(ctx, buf); err != nil {
		return err
	}

	if val4, err := gobtools.DecodeInterface(ctx, buf); err != nil {
		return err
	} else if val4 == nil {
		r.SourcePath = nil
	} else {
		r.SourcePath = val4.(android.Path)
	}

	err = gobtools.DecodeString(buf, &r.SymlinkTarget)
	if err != nil {
		return err
	}

	err = gobtools.DecodeBool(buf, &r.IsDir)
	if err != nil {
		return err
	}

	return err
}

var FullInstallPathInfoGobRegId int16

func (r FullInstallPathInfo) GetTypeId() int16 {
	return FullInstallPathInfoGobRegId
}

func (r FilesystemDefaultsInfo) Encode(ctx gobtools.EncContext, buf *bytes.Buffer) error {
	var err error
	return err
}

func (r *FilesystemDefaultsInfo) Decode(ctx gobtools.EncContext, buf *bytes.Reader) error {
	var err error

	return err
}

var FilesystemDefaultsInfoGobRegId int16

func (r FilesystemDefaultsInfo) GetTypeId() int16 {
	return FilesystemDefaultsInfoGobRegId
}

// end of filesystem.go

// begin of raw_binary.go
func init() {
	RawBinaryInfoGobRegId = gobtools.RegisterType(func() gobtools.CustomDec { return new(RawBinaryInfo) })
}

func (r RawBinaryInfo) Encode(ctx gobtools.EncContext, buf *bytes.Buffer) error {
	var err error

	if r.SrcSymbolInfos == nil {
		if err = gobtools.EncodeInt(buf, -1); err != nil {
			return err
		}
	} else {
		if err = gobtools.EncodeInt(buf, len(r.SrcSymbolInfos)); err != nil {
			return err
		}
		for val1 := 0; val1 < len(r.SrcSymbolInfos); val1++ {
			val2 := r.SrcSymbolInfos[val1] == nil
			if err = gobtools.EncodeBool(buf, val2); err != nil {
				return err
			}
			if !val2 {
				if err = (*r.SrcSymbolInfos[val1]).Encode(ctx, buf); err != nil {
					return err
				}
			}
		}
	}
	return err
}

func (r *RawBinaryInfo) Decode(ctx gobtools.EncContext, buf *bytes.Reader) error {
	var err error

	var val3 int
	err = gobtools.DecodeInt(buf, &val3)
	if err != nil {
		return err
	}
	if val3 != -1 {
		r.SrcSymbolInfos = make([]*android.SymbolicOutputInfo, val3)
		for val4 := 0; val4 < int(val3); val4++ {
			var val6 bool
			if err = gobtools.DecodeBool(buf, &val6); err != nil {
				return err
			}
			if !val6 {
				var val5 android.SymbolicOutputInfo
				if err = val5.Decode(ctx, buf); err != nil {
					return err
				}
				r.SrcSymbolInfos[val4] = &val5
			}
		}
	}

	return err
}

var RawBinaryInfoGobRegId int16

func (r RawBinaryInfo) GetTypeId() int16 {
	return RawBinaryInfoGobRegId
}

// end of raw_binary.go

// begin of super_image.go
func init() {
	SuperImageInfoGobRegId = gobtools.RegisterType(func() gobtools.CustomDec { return new(SuperImageInfo) })
}

func (r SuperImageInfo) Encode(ctx gobtools.EncContext, buf *bytes.Buffer) error {
	var err error

	if err = gobtools.EncodeInterface(ctx, buf, r.SuperImage); err != nil {
		return err
	}

	if r.SubImageInfo == nil {
		if err = gobtools.EncodeInt(buf, -1); err != nil {
			return err
		}
	} else {
		if err = gobtools.EncodeInt(buf, len(r.SubImageInfo)); err != nil {
			return err
		}
		for val1, val2 := range r.SubImageInfo {
			if err = gobtools.EncodeString(buf, val1); err != nil {
				return err
			}
			if err = val2.Encode(ctx, buf); err != nil {
				return err
			}
		}
	}

	if err = gobtools.EncodeInterface(ctx, buf, r.DynamicPartitionsInfo); err != nil {
		return err
	}

	if err = gobtools.EncodeInterface(ctx, buf, r.SuperEmptyImage); err != nil {
		return err
	}

	if err = gobtools.EncodeBool(buf, r.AbUpdate); err != nil {
		return err
	}
	return err
}

func (r *SuperImageInfo) Decode(ctx gobtools.EncContext, buf *bytes.Reader) error {
	var err error

	if val2, err := gobtools.DecodeInterface(ctx, buf); err != nil {
		return err
	} else if val2 == nil {
		r.SuperImage = nil
	} else {
		r.SuperImage = val2.(android.Path)
	}

	var val3 int
	err = gobtools.DecodeInt(buf, &val3)
	if err != nil {
		return err
	}
	if val3 != -1 {
		r.SubImageInfo = make(map[string]FilesystemInfo, val3)
		for val4 := 0; val4 < int(val3); val4++ {
			var val5 string
			var val6 FilesystemInfo
			err = gobtools.DecodeString(buf, &val5)
			if err != nil {
				return err
			}
			if err = val6.Decode(ctx, buf); err != nil {
				return err
			}
			r.SubImageInfo[val5] = val6
		}
	}

	if val10, err := gobtools.DecodeInterface(ctx, buf); err != nil {
		return err
	} else if val10 == nil {
		r.DynamicPartitionsInfo = nil
	} else {
		r.DynamicPartitionsInfo = val10.(android.Path)
	}

	if val12, err := gobtools.DecodeInterface(ctx, buf); err != nil {
		return err
	} else if val12 == nil {
		r.SuperEmptyImage = nil
	} else {
		r.SuperEmptyImage = val12.(android.Path)
	}

	err = gobtools.DecodeBool(buf, &r.AbUpdate)
	if err != nil {
		return err
	}

	return err
}

var SuperImageInfoGobRegId int16

func (r SuperImageInfo) GetTypeId() int16 {
	return SuperImageInfoGobRegId
}

// end of super_image.go

// begin of vbmeta.go
func init() {
	vbmetaPartitionInfoGobRegId = gobtools.RegisterType(func() gobtools.CustomDec { return new(vbmetaPartitionInfo) })
	vbmetaPartitionInfosGobRegId = gobtools.RegisterType(func() gobtools.CustomDec { return new(vbmetaPartitionInfos) })
}

func (r vbmetaPartitionInfo) Encode(ctx gobtools.EncContext, buf *bytes.Buffer) error {
	var err error

	if err = gobtools.EncodeString(buf, r.Name); err != nil {
		return err
	}

	if err = gobtools.EncodeString(buf, r.FilesystemPartitionType); err != nil {
		return err
	}

	if err = gobtools.EncodeInt(buf, r.RollbackIndexLocation); err != nil {
		return err
	}

	if err = gobtools.EncodeInterface(ctx, buf, r.PublicKey); err != nil {
		return err
	}

	if err = gobtools.EncodeInterface(ctx, buf, r.Output); err != nil {
		return err
	}

	if err = gobtools.EncodeInterface(ctx, buf, r.PropFileForMiscInfo); err != nil {
		return err
	}

	if err = gobtools.EncodeBool(buf, r.AbOtaBootloaderPartition); err != nil {
		return err
	}
	return err
}

func (r *vbmetaPartitionInfo) Decode(ctx gobtools.EncContext, buf *bytes.Reader) error {
	var err error

	err = gobtools.DecodeString(buf, &r.Name)
	if err != nil {
		return err
	}

	err = gobtools.DecodeString(buf, &r.FilesystemPartitionType)
	if err != nil {
		return err
	}

	err = gobtools.DecodeInt(buf, &r.RollbackIndexLocation)
	if err != nil {
		return err
	}

	if val5, err := gobtools.DecodeInterface(ctx, buf); err != nil {
		return err
	} else if val5 == nil {
		r.PublicKey = nil
	} else {
		r.PublicKey = val5.(android.Path)
	}

	if val7, err := gobtools.DecodeInterface(ctx, buf); err != nil {
		return err
	} else if val7 == nil {
		r.Output = nil
	} else {
		r.Output = val7.(android.Path)
	}

	if val9, err := gobtools.DecodeInterface(ctx, buf); err != nil {
		return err
	} else if val9 == nil {
		r.PropFileForMiscInfo = nil
	} else {
		r.PropFileForMiscInfo = val9.(android.Path)
	}

	err = gobtools.DecodeBool(buf, &r.AbOtaBootloaderPartition)
	if err != nil {
		return err
	}

	return err
}

var vbmetaPartitionInfoGobRegId int16

func (r vbmetaPartitionInfo) GetTypeId() int16 {
	return vbmetaPartitionInfoGobRegId
}

func (r vbmetaPartitionInfos) Encode(ctx gobtools.EncContext, buf *bytes.Buffer) error {
	var err error

	if r == nil {
		if err = gobtools.EncodeInt(buf, -1); err != nil {
			return err
		}
	} else {
		if err = gobtools.EncodeInt(buf, len(r)); err != nil {
			return err
		}
		for val1 := 0; val1 < len(r); val1++ {
			if err = r[val1].Encode(ctx, buf); err != nil {
				return err
			}
		}
	}
	return err
}

func (r *vbmetaPartitionInfos) Decode(ctx gobtools.EncContext, buf *bytes.Reader) error {
	var err error

	var val2 int
	err = gobtools.DecodeInt(buf, &val2)
	if err != nil {
		return err
	}
	if val2 != -1 {
		(*r) = make([]vbmetaPartitionInfo, val2)
		for val3 := 0; val3 < int(val2); val3++ {
			if err = (*r)[val3].Decode(ctx, buf); err != nil {
				return err
			}
		}
	}

	return err
}

var vbmetaPartitionInfosGobRegId int16

func (r vbmetaPartitionInfos) GetTypeId() int16 {
	return vbmetaPartitionInfosGobRegId
}

// end of vbmeta.go
