// Code generated by go run gob_gen.go; DO NOT EDIT.

package aidl_library

import (
	"android/soong/android"
	"bytes"
	"github.com/google/blueprint/gobtools"
)

// begin of aidl_library.go
func init() {
	AidlLibraryInfoGobRegId = gobtools.RegisterType(func() gobtools.CustomDec { return new(AidlLibraryInfo) })
}

func (r AidlLibraryInfo) Encode(ctx gobtools.EncContext, buf *bytes.Buffer) error {
	var err error

	if r.Srcs == nil {
		if err = gobtools.EncodeInt(buf, -1); err != nil {
			return err
		}
	} else {
		if err = gobtools.EncodeInt(buf, len(r.Srcs)); err != nil {
			return err
		}
		for val1 := 0; val1 < len(r.Srcs); val1++ {
			if err = gobtools.EncodeInterface(ctx, buf, r.Srcs[val1]); err != nil {
				return err
			}
		}
	}

	if err = r.IncludeDirs.EncodeInterface(ctx, buf); err != nil {
		return err
	}

	if err = r.Hdrs.EncodeInterface(ctx, buf); err != nil {
		return err
	}
	return err
}

func (r *AidlLibraryInfo) Decode(ctx gobtools.EncContext, buf *bytes.Reader) error {
	var err error

	var val3 int
	err = gobtools.DecodeInt(buf, &val3)
	if err != nil {
		return err
	}
	if val3 != -1 {
		r.Srcs = make([]android.Path, val3)
		for val4 := 0; val4 < int(val3); val4++ {
			if val6, err := gobtools.DecodeInterface(ctx, buf); err != nil {
				return err
			} else if val6 == nil {
				r.Srcs[val4] = nil
			} else {
				r.Srcs[val4] = val6.(android.Path)
			}
		}
	}

	if err = r.IncludeDirs.DecodeInterface(ctx, buf); err != nil {
		return err
	}

	if err = r.Hdrs.DecodeInterface(ctx, buf); err != nil {
		return err
	}

	return err
}

var AidlLibraryInfoGobRegId int16

func (r AidlLibraryInfo) GetTypeId() int16 {
	return AidlLibraryInfoGobRegId
}

// end of aidl_library.go
