// Code generated by go run gob_gen.go; DO NOT EDIT.

package aconfig

import (
	"android/soong/android"
	"bytes"
	"github.com/google/blueprint/gobtools"
)

// begin of aconfig_value_set.go
func init() {
	valueSetProviderDataGobRegId = gobtools.RegisterType(func() gobtools.CustomDec { return new(valueSetProviderData) })
}

func (r valueSetProviderData) Encode(ctx gobtools.EncContext, buf *bytes.Buffer) error {
	var err error

	if r.AvailablePackages == nil {
		if err = gobtools.EncodeInt(buf, -1); err != nil {
			return err
		}
	} else {
		if err = gobtools.EncodeInt(buf, len(r.AvailablePackages)); err != nil {
			return err
		}
		for val1, val2 := range r.AvailablePackages {
			if err = gobtools.EncodeString(buf, val1); err != nil {
				return err
			}
			if val2 == nil {
				if err = gobtools.EncodeInt(buf, -1); err != nil {
					return err
				}
			} else {
				if err = gobtools.EncodeInt(buf, len(val2)); err != nil {
					return err
				}
				for val3 := 0; val3 < len(val2); val3++ {
					if err = gobtools.EncodeInterface(ctx, buf, val2[val3]); err != nil {
						return err
					}
				}
			}
		}
	}
	return err
}

func (r *valueSetProviderData) Decode(ctx gobtools.EncContext, buf *bytes.Reader) error {
	var err error

	var val1 int
	err = gobtools.DecodeInt(buf, &val1)
	if err != nil {
		return err
	}
	if val1 != -1 {
		r.AvailablePackages = make(map[string]android.Paths, val1)
		for val2 := 0; val2 < int(val1); val2++ {
			var val3 string
			var val4 android.Paths
			err = gobtools.DecodeString(buf, &val3)
			if err != nil {
				return err
			}
			var val8 int
			err = gobtools.DecodeInt(buf, &val8)
			if err != nil {
				return err
			}
			if val8 != -1 {
				val4 = make([]android.Path, val8)
				for val9 := 0; val9 < int(val8); val9++ {
					if val11, err := gobtools.DecodeInterface(ctx, buf); err != nil {
						return err
					} else if val11 == nil {
						val4[val9] = nil
					} else {
						val4[val9] = val11.(android.Path)
					}
				}
			}
			r.AvailablePackages[val3] = val4
		}
	}

	return err
}

var valueSetProviderDataGobRegId int16

func (r valueSetProviderData) GetTypeId() int16 {
	return valueSetProviderDataGobRegId
}

// end of aconfig_value_set.go

// begin of aconfig_values.go
func init() {
	valuesProviderDataGobRegId = gobtools.RegisterType(func() gobtools.CustomDec { return new(valuesProviderData) })
}

func (r valuesProviderData) Encode(ctx gobtools.EncContext, buf *bytes.Buffer) error {
	var err error

	if err = gobtools.EncodeString(buf, r.Package); err != nil {
		return err
	}

	if r.Values == nil {
		if err = gobtools.EncodeInt(buf, -1); err != nil {
			return err
		}
	} else {
		if err = gobtools.EncodeInt(buf, len(r.Values)); err != nil {
			return err
		}
		for val1 := 0; val1 < len(r.Values); val1++ {
			if err = gobtools.EncodeInterface(ctx, buf, r.Values[val1]); err != nil {
				return err
			}
		}
	}
	return err
}

func (r *valuesProviderData) Decode(ctx gobtools.EncContext, buf *bytes.Reader) error {
	var err error

	err = gobtools.DecodeString(buf, &r.Package)
	if err != nil {
		return err
	}

	var val4 int
	err = gobtools.DecodeInt(buf, &val4)
	if err != nil {
		return err
	}
	if val4 != -1 {
		r.Values = make([]android.Path, val4)
		for val5 := 0; val5 < int(val4); val5++ {
			if val7, err := gobtools.DecodeInterface(ctx, buf); err != nil {
				return err
			} else if val7 == nil {
				r.Values[val5] = nil
			} else {
				r.Values[val5] = val7.(android.Path)
			}
		}
	}

	return err
}

var valuesProviderDataGobRegId int16

func (r valuesProviderData) GetTypeId() int16 {
	return valuesProviderDataGobRegId
}

// end of aconfig_values.go

// begin of all_aconfig_declarations.go
func init() {
	AllAconfigDeclarationsInfoGobRegId = gobtools.RegisterType(func() gobtools.CustomDec { return new(AllAconfigDeclarationsInfo) })
}

func (r AllAconfigDeclarationsInfo) Encode(ctx gobtools.EncContext, buf *bytes.Buffer) error {
	var err error

	if err = gobtools.EncodeInterface(ctx, buf, r.ParsedFlagsFile); err != nil {
		return err
	}

	if err = gobtools.EncodeInterface(ctx, buf, r.TextProtoFlagsFile); err != nil {
		return err
	}

	if err = gobtools.EncodeInterface(ctx, buf, r.StorageFlagVal); err != nil {
		return err
	}

	if err = gobtools.EncodeInterface(ctx, buf, r.StorageFlagMap); err != nil {
		return err
	}

	if err = gobtools.EncodeInterface(ctx, buf, r.StorageFlagInfo); err != nil {
		return err
	}

	if err = gobtools.EncodeInterface(ctx, buf, r.StoragePackageMap); err != nil {
		return err
	}
	return err
}

func (r *AllAconfigDeclarationsInfo) Decode(ctx gobtools.EncContext, buf *bytes.Reader) error {
	var err error

	if val2, err := gobtools.DecodeInterface(ctx, buf); err != nil {
		return err
	} else if val2 == nil {
		r.ParsedFlagsFile = nil
	} else {
		r.ParsedFlagsFile = val2.(android.Path)
	}

	if val4, err := gobtools.DecodeInterface(ctx, buf); err != nil {
		return err
	} else if val4 == nil {
		r.TextProtoFlagsFile = nil
	} else {
		r.TextProtoFlagsFile = val4.(android.Path)
	}

	if val6, err := gobtools.DecodeInterface(ctx, buf); err != nil {
		return err
	} else if val6 == nil {
		r.StorageFlagVal = nil
	} else {
		r.StorageFlagVal = val6.(android.Path)
	}

	if val8, err := gobtools.DecodeInterface(ctx, buf); err != nil {
		return err
	} else if val8 == nil {
		r.StorageFlagMap = nil
	} else {
		r.StorageFlagMap = val8.(android.Path)
	}

	if val10, err := gobtools.DecodeInterface(ctx, buf); err != nil {
		return err
	} else if val10 == nil {
		r.StorageFlagInfo = nil
	} else {
		r.StorageFlagInfo = val10.(android.Path)
	}

	if val12, err := gobtools.DecodeInterface(ctx, buf); err != nil {
		return err
	} else if val12 == nil {
		r.StoragePackageMap = nil
	} else {
		r.StoragePackageMap = val12.(android.Path)
	}

	return err
}

var AllAconfigDeclarationsInfoGobRegId int16

func (r AllAconfigDeclarationsInfo) GetTypeId() int16 {
	return AllAconfigDeclarationsInfoGobRegId
}

// end of all_aconfig_declarations.go
