// Code generated by go run gob_gen.go; DO NOT EDIT.

package sh

import (
	"android/soong/android"
	"bytes"
	"github.com/google/blueprint/gobtools"
)

// begin of sh_binary.go
func init() {
	ShBinaryInfoGobRegId = gobtools.RegisterType(func() gobtools.CustomDec { return new(ShBinaryInfo) })
}

func (r ShBinaryInfo) Encode(ctx gobtools.EncContext, buf *bytes.Buffer) error {
	var err error

	if err = gobtools.EncodeString(buf, r.SubDir); err != nil {
		return err
	}

	if err = gobtools.EncodeInterface(ctx, buf, r.OutputFile); err != nil {
		return err
	}

	if r.Symlinks == nil {
		if err = gobtools.EncodeInt(buf, -1); err != nil {
			return err
		}
	} else {
		if err = gobtools.EncodeInt(buf, len(r.Symlinks)); err != nil {
			return err
		}
		for val1 := 0; val1 < len(r.Symlinks); val1++ {
			if err = gobtools.EncodeString(buf, r.Symlinks[val1]); err != nil {
				return err
			}
		}
	}
	return err
}

func (r *ShBinaryInfo) Decode(ctx gobtools.EncContext, buf *bytes.Reader) error {
	var err error

	err = gobtools.DecodeString(buf, &r.SubDir)
	if err != nil {
		return err
	}

	if val3, err := gobtools.DecodeInterface(ctx, buf); err != nil {
		return err
	} else if val3 == nil {
		r.OutputFile = nil
	} else {
		r.OutputFile = val3.(android.Path)
	}

	var val5 int
	err = gobtools.DecodeInt(buf, &val5)
	if err != nil {
		return err
	}
	if val5 != -1 {
		r.Symlinks = make([]string, val5)
		for val6 := 0; val6 < int(val5); val6++ {
			err = gobtools.DecodeString(buf, &r.Symlinks[val6])
			if err != nil {
				return err
			}
		}
	}

	return err
}

var ShBinaryInfoGobRegId int16

func (r ShBinaryInfo) GetTypeId() int16 {
	return ShBinaryInfoGobRegId
}

// end of sh_binary.go
