// Code generated by go run gob_gen.go; DO NOT EDIT.

package build_flags

import (
	"android/soong/android"
	"bytes"
	"github.com/google/blueprint/gobtools"
)

// begin of declarations.go
func init() {
	BuildFlagDeclarationsProviderDataGobRegId = gobtools.RegisterType(func() gobtools.CustomDec { return new(BuildFlagDeclarationsProviderData) })
}

func (r BuildFlagDeclarationsProviderData) Encode(ctx gobtools.EncContext, buf *bytes.Buffer) error {
	var err error

	if err = gobtools.EncodeInterface(ctx, buf, r.IntermediateCacheOutputPath); err != nil {
		return err
	}

	if err = gobtools.EncodeInterface(ctx, buf, r.IntermediateDumpOutputPath); err != nil {
		return err
	}
	return err
}

func (r *BuildFlagDeclarationsProviderData) Decode(ctx gobtools.EncContext, buf *bytes.Reader) error {
	var err error

	if val2, err := gobtools.DecodeInterface(ctx, buf); err != nil {
		return err
	} else if val2 == nil {
		r.IntermediateCacheOutputPath = nil
	} else {
		r.IntermediateCacheOutputPath = val2.(android.WritablePath)
	}

	if val4, err := gobtools.DecodeInterface(ctx, buf); err != nil {
		return err
	} else if val4 == nil {
		r.IntermediateDumpOutputPath = nil
	} else {
		r.IntermediateDumpOutputPath = val4.(android.WritablePath)
	}

	return err
}

var BuildFlagDeclarationsProviderDataGobRegId int16

func (r BuildFlagDeclarationsProviderData) GetTypeId() int16 {
	return BuildFlagDeclarationsProviderDataGobRegId
}

// end of declarations.go

// begin of release_configs.go
func init() {
	ReleaseConfigContributionsProviderDataGobRegId = gobtools.RegisterType(func() gobtools.CustomDec { return new(ReleaseConfigContributionsProviderData) })
	ReleaseConfigProviderDataGobRegId = gobtools.RegisterType(func() gobtools.CustomDec { return new(ReleaseConfigProviderData) })
	AllReleaseConfigsProviderDataGobRegId = gobtools.RegisterType(func() gobtools.CustomDec { return new(AllReleaseConfigsProviderData) })
}

func (r ReleaseConfigContributionsProviderData) Encode(ctx gobtools.EncContext, buf *bytes.Buffer) error {
	var err error

	if err = r.ContributionDir.Encode(ctx, buf); err != nil {
		return err
	}

	if r.ContributionPaths == nil {
		if err = gobtools.EncodeInt(buf, -1); err != nil {
			return err
		}
	} else {
		if err = gobtools.EncodeInt(buf, len(r.ContributionPaths)); err != nil {
			return err
		}
		for val1 := 0; val1 < len(r.ContributionPaths); val1++ {
			if err = gobtools.EncodeInterface(ctx, buf, r.ContributionPaths[val1]); err != nil {
				return err
			}
		}
	}
	return err
}

func (r *ReleaseConfigContributionsProviderData) Decode(ctx gobtools.EncContext, buf *bytes.Reader) error {
	var err error

	if err = r.ContributionDir.Decode(ctx, buf); err != nil {
		return err
	}

	var val4 int
	err = gobtools.DecodeInt(buf, &val4)
	if err != nil {
		return err
	}
	if val4 != -1 {
		r.ContributionPaths = make([]android.Path, val4)
		for val5 := 0; val5 < int(val4); val5++ {
			if val7, err := gobtools.DecodeInterface(ctx, buf); err != nil {
				return err
			} else if val7 == nil {
				r.ContributionPaths[val5] = nil
			} else {
				r.ContributionPaths[val5] = val7.(android.Path)
			}
		}
	}

	return err
}

var ReleaseConfigContributionsProviderDataGobRegId int16

func (r ReleaseConfigContributionsProviderData) GetTypeId() int16 {
	return ReleaseConfigContributionsProviderDataGobRegId
}

func (r ReleaseConfigProviderData) Encode(ctx gobtools.EncContext, buf *bytes.Buffer) error {
	var err error

	if err = gobtools.EncodeInterface(ctx, buf, r.BuildFlagsProductJson); err != nil {
		return err
	}

	if err = gobtools.EncodeInterface(ctx, buf, r.BuildFlagsSystemJson); err != nil {
		return err
	}

	if err = gobtools.EncodeInterface(ctx, buf, r.BuildFlagsSystemExtJson); err != nil {
		return err
	}

	if err = gobtools.EncodeInterface(ctx, buf, r.BuildFlagsVendorJson); err != nil {
		return err
	}
	return err
}

func (r *ReleaseConfigProviderData) Decode(ctx gobtools.EncContext, buf *bytes.Reader) error {
	var err error

	if val2, err := gobtools.DecodeInterface(ctx, buf); err != nil {
		return err
	} else if val2 == nil {
		r.BuildFlagsProductJson = nil
	} else {
		r.BuildFlagsProductJson = val2.(android.Path)
	}

	if val4, err := gobtools.DecodeInterface(ctx, buf); err != nil {
		return err
	} else if val4 == nil {
		r.BuildFlagsSystemJson = nil
	} else {
		r.BuildFlagsSystemJson = val4.(android.Path)
	}

	if val6, err := gobtools.DecodeInterface(ctx, buf); err != nil {
		return err
	} else if val6 == nil {
		r.BuildFlagsSystemExtJson = nil
	} else {
		r.BuildFlagsSystemExtJson = val6.(android.Path)
	}

	if val8, err := gobtools.DecodeInterface(ctx, buf); err != nil {
		return err
	} else if val8 == nil {
		r.BuildFlagsVendorJson = nil
	} else {
		r.BuildFlagsVendorJson = val8.(android.Path)
	}

	return err
}

var ReleaseConfigProviderDataGobRegId int16

func (r ReleaseConfigProviderData) GetTypeId() int16 {
	return ReleaseConfigProviderDataGobRegId
}

func (r AllReleaseConfigsProviderData) Encode(ctx gobtools.EncContext, buf *bytes.Buffer) error {
	var err error

	if err = gobtools.EncodeInterface(ctx, buf, r.AllReleaseConfigsDb); err != nil {
		return err
	}

	if err = gobtools.EncodeInterface(ctx, buf, r.AllReleaseConfigsTextproto); err != nil {
		return err
	}

	if err = gobtools.EncodeInterface(ctx, buf, r.AllReleaseConfigsJson); err != nil {
		return err
	}

	if err = gobtools.EncodeInterface(ctx, buf, r.InheritanceGraphDot); err != nil {
		return err
	}
	return err
}

func (r *AllReleaseConfigsProviderData) Decode(ctx gobtools.EncContext, buf *bytes.Reader) error {
	var err error

	if val2, err := gobtools.DecodeInterface(ctx, buf); err != nil {
		return err
	} else if val2 == nil {
		r.AllReleaseConfigsDb = nil
	} else {
		r.AllReleaseConfigsDb = val2.(android.Path)
	}

	if val4, err := gobtools.DecodeInterface(ctx, buf); err != nil {
		return err
	} else if val4 == nil {
		r.AllReleaseConfigsTextproto = nil
	} else {
		r.AllReleaseConfigsTextproto = val4.(android.Path)
	}

	if val6, err := gobtools.DecodeInterface(ctx, buf); err != nil {
		return err
	} else if val6 == nil {
		r.AllReleaseConfigsJson = nil
	} else {
		r.AllReleaseConfigsJson = val6.(android.Path)
	}

	if val8, err := gobtools.DecodeInterface(ctx, buf); err != nil {
		return err
	} else if val8 == nil {
		r.InheritanceGraphDot = nil
	} else {
		r.InheritanceGraphDot = val8.(android.Path)
	}

	return err
}

var AllReleaseConfigsProviderDataGobRegId int16

func (r AllReleaseConfigsProviderData) GetTypeId() int16 {
	return AllReleaseConfigsProviderDataGobRegId
}

// end of release_configs.go
