// Code generated by go run gob_gen.go; DO NOT EDIT.

package android

import (
	"bytes"
	"github.com/google/blueprint/gobtools"
)

func init() {
	AndroidMkDataInfoGobRegId = gobtools.RegisterType(func() gobtools.CustomDec { return new(AndroidMkDataInfo) })
	distCopyGobRegId = gobtools.RegisterType(func() gobtools.CustomDec { return new(distCopy) })
	AndroidMkProviderInfoGobRegId = gobtools.RegisterType(func() gobtools.CustomDec { return new(AndroidMkProviderInfo) })
	AndroidMkInfoGobRegId = gobtools.RegisterType(func() gobtools.CustomDec { return new(AndroidMkInfo) })
}

func (r AndroidMkDataInfo) Encode(ctx gobtools.EncContext, buf *bytes.Buffer) error {
	var err error

	if err = gobtools.EncodeString(buf, r.Class); err != nil {
		return err
	}
	return err
}

func (r *AndroidMkDataInfo) Decode(ctx gobtools.EncContext, buf *bytes.Reader) error {
	var err error

	err = gobtools.DecodeString(buf, &r.Class)
	if err != nil {
		return err
	}

	return err
}

var AndroidMkDataInfoGobRegId int16

func (r AndroidMkDataInfo) GetTypeId() int16 {
	return AndroidMkDataInfoGobRegId
}

func (r distCopy) Encode(ctx gobtools.EncContext, buf *bytes.Buffer) error {
	var err error

	if err = gobtools.EncodeInterface(ctx, buf, r.from); err != nil {
		return err
	}

	if err = gobtools.EncodeString(buf, r.dest); err != nil {
		return err
	}
	return err
}

func (r *distCopy) Decode(ctx gobtools.EncContext, buf *bytes.Reader) error {
	var err error

	if val2, err := gobtools.DecodeInterface(ctx, buf); err != nil {
		return err
	} else if val2 == nil {
		r.from = nil
	} else {
		r.from = val2.(Path)
	}

	err = gobtools.DecodeString(buf, &r.dest)
	if err != nil {
		return err
	}

	return err
}

var distCopyGobRegId int16

func (r distCopy) GetTypeId() int16 {
	return distCopyGobRegId
}

func (r AndroidMkProviderInfo) Encode(ctx gobtools.EncContext, buf *bytes.Buffer) error {
	var err error

	if err = r.PrimaryInfo.Encode(ctx, buf); err != nil {
		return err
	}

	if r.ExtraInfo == nil {
		if err = gobtools.EncodeInt(buf, -1); err != nil {
			return err
		}
	} else {
		if err = gobtools.EncodeInt(buf, len(r.ExtraInfo)); err != nil {
			return err
		}
		for val1 := 0; val1 < len(r.ExtraInfo); val1++ {
			if err = r.ExtraInfo[val1].Encode(ctx, buf); err != nil {
				return err
			}
		}
	}
	return err
}

func (r *AndroidMkProviderInfo) Decode(ctx gobtools.EncContext, buf *bytes.Reader) error {
	var err error

	if err = r.PrimaryInfo.Decode(ctx, buf); err != nil {
		return err
	}

	var val3 int
	err = gobtools.DecodeInt(buf, &val3)
	if err != nil {
		return err
	}
	if val3 != -1 {
		r.ExtraInfo = make([]AndroidMkInfo, val3)
		for val4 := 0; val4 < int(val3); val4++ {
			if err = r.ExtraInfo[val4].Decode(ctx, buf); err != nil {
				return err
			}
		}
	}

	return err
}

var AndroidMkProviderInfoGobRegId int16

func (r AndroidMkProviderInfo) GetTypeId() int16 {
	return AndroidMkProviderInfoGobRegId
}

func (r AndroidMkInfo) Encode(ctx gobtools.EncContext, buf *bytes.Buffer) error {
	var err error

	if err = gobtools.EncodeString(buf, r.Class); err != nil {
		return err
	}

	if err = gobtools.EncodeString(buf, r.SubName); err != nil {
		return err
	}

	if err = gobtools.EncodeString(buf, r.OverrideName); err != nil {
		return err
	}

	if err = r.OutputFile.Encode(ctx, buf); err != nil {
		return err
	}

	if err = gobtools.EncodeString(buf, r.Include); err != nil {
		return err
	}

	if r.Required == nil {
		if err = gobtools.EncodeInt(buf, -1); err != nil {
			return err
		}
	} else {
		if err = gobtools.EncodeInt(buf, len(r.Required)); err != nil {
			return err
		}
		for val1 := 0; val1 < len(r.Required); val1++ {
			if err = gobtools.EncodeString(buf, r.Required[val1]); err != nil {
				return err
			}
		}
	}

	if r.Host_required == nil {
		if err = gobtools.EncodeInt(buf, -1); err != nil {
			return err
		}
	} else {
		if err = gobtools.EncodeInt(buf, len(r.Host_required)); err != nil {
			return err
		}
		for val2 := 0; val2 < len(r.Host_required); val2++ {
			if err = gobtools.EncodeString(buf, r.Host_required[val2]); err != nil {
				return err
			}
		}
	}

	if r.Target_required == nil {
		if err = gobtools.EncodeInt(buf, -1); err != nil {
			return err
		}
	} else {
		if err = gobtools.EncodeInt(buf, len(r.Target_required)); err != nil {
			return err
		}
		for val3 := 0; val3 < len(r.Target_required); val3++ {
			if err = gobtools.EncodeString(buf, r.Target_required[val3]); err != nil {
				return err
			}
		}
	}

	if r.HeaderStrings == nil {
		if err = gobtools.EncodeInt(buf, -1); err != nil {
			return err
		}
	} else {
		if err = gobtools.EncodeInt(buf, len(r.HeaderStrings)); err != nil {
			return err
		}
		for val4 := 0; val4 < len(r.HeaderStrings); val4++ {
			if err = gobtools.EncodeString(buf, r.HeaderStrings[val4]); err != nil {
				return err
			}
		}
	}

	if r.FooterStrings == nil {
		if err = gobtools.EncodeInt(buf, -1); err != nil {
			return err
		}
	} else {
		if err = gobtools.EncodeInt(buf, len(r.FooterStrings)); err != nil {
			return err
		}
		for val5 := 0; val5 < len(r.FooterStrings); val5++ {
			if err = gobtools.EncodeString(buf, r.FooterStrings[val5]); err != nil {
				return err
			}
		}
	}

	if r.EntryMap == nil {
		if err = gobtools.EncodeInt(buf, -1); err != nil {
			return err
		}
	} else {
		if err = gobtools.EncodeInt(buf, len(r.EntryMap)); err != nil {
			return err
		}
		for val6, val7 := range r.EntryMap {
			if err = gobtools.EncodeString(buf, val6); err != nil {
				return err
			}
			if val7 == nil {
				if err = gobtools.EncodeInt(buf, -1); err != nil {
					return err
				}
			} else {
				if err = gobtools.EncodeInt(buf, len(val7)); err != nil {
					return err
				}
				for val8 := 0; val8 < len(val7); val8++ {
					if err = gobtools.EncodeString(buf, val7[val8]); err != nil {
						return err
					}
				}
			}
		}
	}

	if r.EntryOrder == nil {
		if err = gobtools.EncodeInt(buf, -1); err != nil {
			return err
		}
	} else {
		if err = gobtools.EncodeInt(buf, len(r.EntryOrder)); err != nil {
			return err
		}
		for val9 := 0; val9 < len(r.EntryOrder); val9++ {
			if err = gobtools.EncodeString(buf, r.EntryOrder[val9]); err != nil {
				return err
			}
		}
	}
	return err
}

func (r *AndroidMkInfo) Decode(ctx gobtools.EncContext, buf *bytes.Reader) error {
	var err error

	err = gobtools.DecodeString(buf, &r.Class)
	if err != nil {
		return err
	}

	err = gobtools.DecodeString(buf, &r.SubName)
	if err != nil {
		return err
	}

	err = gobtools.DecodeString(buf, &r.OverrideName)
	if err != nil {
		return err
	}

	if err = r.OutputFile.Decode(ctx, buf); err != nil {
		return err
	}

	err = gobtools.DecodeString(buf, &r.Include)
	if err != nil {
		return err
	}

	var val7 int
	err = gobtools.DecodeInt(buf, &val7)
	if err != nil {
		return err
	}
	if val7 != -1 {
		r.Required = make([]string, val7)
		for val8 := 0; val8 < int(val7); val8++ {
			err = gobtools.DecodeString(buf, &r.Required[val8])
			if err != nil {
				return err
			}
		}
	}

	var val11 int
	err = gobtools.DecodeInt(buf, &val11)
	if err != nil {
		return err
	}
	if val11 != -1 {
		r.Host_required = make([]string, val11)
		for val12 := 0; val12 < int(val11); val12++ {
			err = gobtools.DecodeString(buf, &r.Host_required[val12])
			if err != nil {
				return err
			}
		}
	}

	var val15 int
	err = gobtools.DecodeInt(buf, &val15)
	if err != nil {
		return err
	}
	if val15 != -1 {
		r.Target_required = make([]string, val15)
		for val16 := 0; val16 < int(val15); val16++ {
			err = gobtools.DecodeString(buf, &r.Target_required[val16])
			if err != nil {
				return err
			}
		}
	}

	var val19 int
	err = gobtools.DecodeInt(buf, &val19)
	if err != nil {
		return err
	}
	if val19 != -1 {
		r.HeaderStrings = make([]string, val19)
		for val20 := 0; val20 < int(val19); val20++ {
			err = gobtools.DecodeString(buf, &r.HeaderStrings[val20])
			if err != nil {
				return err
			}
		}
	}

	var val23 int
	err = gobtools.DecodeInt(buf, &val23)
	if err != nil {
		return err
	}
	if val23 != -1 {
		r.FooterStrings = make([]string, val23)
		for val24 := 0; val24 < int(val23); val24++ {
			err = gobtools.DecodeString(buf, &r.FooterStrings[val24])
			if err != nil {
				return err
			}
		}
	}

	var val26 int
	err = gobtools.DecodeInt(buf, &val26)
	if err != nil {
		return err
	}
	if val26 != -1 {
		r.EntryMap = make(map[string][]string, val26)
		for val27 := 0; val27 < int(val26); val27++ {
			var val28 string
			var val29 []string
			err = gobtools.DecodeString(buf, &val28)
			if err != nil {
				return err
			}
			var val32 int
			err = gobtools.DecodeInt(buf, &val32)
			if err != nil {
				return err
			}
			if val32 != -1 {
				val29 = make([]string, val32)
				for val33 := 0; val33 < int(val32); val33++ {
					err = gobtools.DecodeString(buf, &val29[val33])
					if err != nil {
						return err
					}
				}
			}
			r.EntryMap[val28] = val29
		}
	}

	var val36 int
	err = gobtools.DecodeInt(buf, &val36)
	if err != nil {
		return err
	}
	if val36 != -1 {
		r.EntryOrder = make([]string, val36)
		for val37 := 0; val37 < int(val36); val37++ {
			err = gobtools.DecodeString(buf, &r.EntryOrder[val37])
			if err != nil {
				return err
			}
		}
	}

	return err
}

var AndroidMkInfoGobRegId int16

func (r AndroidMkInfo) GetTypeId() int16 {
	return AndroidMkInfoGobRegId
}
