// Code generated by go run gob_gen.go; DO NOT EDIT.

package android

import (
	"bytes"
	"github.com/google/blueprint/gobtools"
)

func init() {
	ApexInfoGobRegId = gobtools.RegisterType(func() gobtools.CustomDec { return new(ApexInfo) })
	ApexBundleDepsInfoGobRegId = gobtools.RegisterType(func() gobtools.CustomDec { return new(ApexBundleDepsInfo) })
	ApexBundleDepsDataGobRegId = gobtools.RegisterType(func() gobtools.CustomDec { return new(ApexBundleDepsData) })
	ApexBundleTypeInfoGobRegId = gobtools.RegisterType(func() gobtools.CustomDec { return new(ApexBundleTypeInfo) })
	PrebuiltJsonInfoGobRegId = gobtools.RegisterType(func() gobtools.CustomDec { return new(PrebuiltJsonInfo) })
}

func (r ApexInfo) Encode(ctx gobtools.EncContext, buf *bytes.Buffer) error {
	var err error

	if err = gobtools.EncodeString(buf, r.ApexVariationName); err != nil {
		return err
	}

	if err = r.MinSdkVersion.Encode(ctx, buf); err != nil {
		return err
	}

	if err = gobtools.EncodeBool(buf, r.Updatable); err != nil {
		return err
	}

	if err = gobtools.EncodeBool(buf, r.UsePlatformApis); err != nil {
		return err
	}

	if err = gobtools.EncodeBool(buf, r.ForPrebuiltApex); err != nil {
		return err
	}

	if err = gobtools.EncodeString(buf, r.BaseApexName); err != nil {
		return err
	}

	if err = gobtools.EncodeString(buf, r.ApexAvailableName); err != nil {
		return err
	}
	return err
}

func (r *ApexInfo) Decode(ctx gobtools.EncContext, buf *bytes.Reader) error {
	var err error

	err = gobtools.DecodeString(buf, &r.ApexVariationName)
	if err != nil {
		return err
	}

	if err = r.MinSdkVersion.Decode(ctx, buf); err != nil {
		return err
	}

	err = gobtools.DecodeBool(buf, &r.Updatable)
	if err != nil {
		return err
	}

	err = gobtools.DecodeBool(buf, &r.UsePlatformApis)
	if err != nil {
		return err
	}

	err = gobtools.DecodeBool(buf, &r.ForPrebuiltApex)
	if err != nil {
		return err
	}

	err = gobtools.DecodeString(buf, &r.BaseApexName)
	if err != nil {
		return err
	}

	err = gobtools.DecodeString(buf, &r.ApexAvailableName)
	if err != nil {
		return err
	}

	return err
}

var ApexInfoGobRegId int16

func (r ApexInfo) GetTypeId() int16 {
	return ApexInfoGobRegId
}

func (r ApexBundleDepsInfo) Encode(ctx gobtools.EncContext, buf *bytes.Buffer) error {
	var err error

	if err = gobtools.EncodeInterface(ctx, buf, r.flatListPath); err != nil {
		return err
	}

	if err = gobtools.EncodeInterface(ctx, buf, r.fullListPath); err != nil {
		return err
	}
	return err
}

func (r *ApexBundleDepsInfo) Decode(ctx gobtools.EncContext, buf *bytes.Reader) error {
	var err error

	if val2, err := gobtools.DecodeInterface(ctx, buf); err != nil {
		return err
	} else if val2 == nil {
		r.flatListPath = nil
	} else {
		r.flatListPath = val2.(Path)
	}

	if val4, err := gobtools.DecodeInterface(ctx, buf); err != nil {
		return err
	} else if val4 == nil {
		r.fullListPath = nil
	} else {
		r.fullListPath = val4.(Path)
	}

	return err
}

var ApexBundleDepsInfoGobRegId int16

func (r ApexBundleDepsInfo) GetTypeId() int16 {
	return ApexBundleDepsInfoGobRegId
}

func (r ApexBundleDepsData) Encode(ctx gobtools.EncContext, buf *bytes.Buffer) error {
	var err error

	if err = gobtools.EncodeBool(buf, r.Updatable); err != nil {
		return err
	}

	if err = gobtools.EncodeInterface(ctx, buf, r.FlatListPath); err != nil {
		return err
	}
	return err
}

func (r *ApexBundleDepsData) Decode(ctx gobtools.EncContext, buf *bytes.Reader) error {
	var err error

	err = gobtools.DecodeBool(buf, &r.Updatable)
	if err != nil {
		return err
	}

	if val3, err := gobtools.DecodeInterface(ctx, buf); err != nil {
		return err
	} else if val3 == nil {
		r.FlatListPath = nil
	} else {
		r.FlatListPath = val3.(Path)
	}

	return err
}

var ApexBundleDepsDataGobRegId int16

func (r ApexBundleDepsData) GetTypeId() int16 {
	return ApexBundleDepsDataGobRegId
}

func (r ApexBundleTypeInfo) Encode(ctx gobtools.EncContext, buf *bytes.Buffer) error {
	var err error

	if err = gobtools.EncodeInterface(ctx, buf, r.Pem); err != nil {
		return err
	}

	if err = gobtools.EncodeInterface(ctx, buf, r.Key); err != nil {
		return err
	}
	return err
}

func (r *ApexBundleTypeInfo) Decode(ctx gobtools.EncContext, buf *bytes.Reader) error {
	var err error

	if val2, err := gobtools.DecodeInterface(ctx, buf); err != nil {
		return err
	} else if val2 == nil {
		r.Pem = nil
	} else {
		r.Pem = val2.(Path)
	}

	if val4, err := gobtools.DecodeInterface(ctx, buf); err != nil {
		return err
	} else if val4 == nil {
		r.Key = nil
	} else {
		r.Key = val4.(Path)
	}

	return err
}

var ApexBundleTypeInfoGobRegId int16

func (r ApexBundleTypeInfo) GetTypeId() int16 {
	return ApexBundleTypeInfoGobRegId
}

func (r PrebuiltJsonInfo) Encode(ctx gobtools.EncContext, buf *bytes.Buffer) error {
	var err error

	if err = gobtools.EncodeString(buf, r.Name); err != nil {
		return err
	}

	if err = gobtools.EncodeBool(buf, r.Is_prebuilt); err != nil {
		return err
	}

	if err = gobtools.EncodeString(buf, r.Prebuilt_info_file_path); err != nil {
		return err
	}
	return err
}

func (r *PrebuiltJsonInfo) Decode(ctx gobtools.EncContext, buf *bytes.Reader) error {
	var err error

	err = gobtools.DecodeString(buf, &r.Name)
	if err != nil {
		return err
	}

	err = gobtools.DecodeBool(buf, &r.Is_prebuilt)
	if err != nil {
		return err
	}

	err = gobtools.DecodeString(buf, &r.Prebuilt_info_file_path)
	if err != nil {
		return err
	}

	return err
}

var PrebuiltJsonInfoGobRegId int16

func (r PrebuiltJsonInfo) GetTypeId() int16 {
	return PrebuiltJsonInfoGobRegId
}
