// Code generated by go run gob_gen.go; DO NOT EDIT.

package android

import (
	"bytes"
	"github.com/google/blueprint/gobtools"
)

func init() {
	ApiLevelGobRegId = gobtools.RegisterType(func() gobtools.CustomDec { return new(ApiLevel) })
}

func (r ApiLevel) Encode(ctx gobtools.EncContext, buf *bytes.Buffer) error {
	var err error

	if err = gobtools.EncodeString(buf, r.value); err != nil {
		return err
	}

	if err = gobtools.EncodeInt(buf, r.number); err != nil {
		return err
	}

	if err = gobtools.EncodeBool(buf, r.isPreview); err != nil {
		return err
	}
	return err
}

func (r *ApiLevel) Decode(ctx gobtools.EncContext, buf *bytes.Reader) error {
	var err error

	err = gobtools.DecodeString(buf, &r.value)
	if err != nil {
		return err
	}

	err = gobtools.DecodeInt(buf, &r.number)
	if err != nil {
		return err
	}

	err = gobtools.DecodeBool(buf, &r.isPreview)
	if err != nil {
		return err
	}

	return err
}

var ApiLevelGobRegId int16

func (r ApiLevel) GetTypeId() int16 {
	return ApiLevelGobRegId
}
