// Code generated by go run gob_gen.go; DO NOT EDIT.

package android

import (
	"bytes"
	"github.com/google/blueprint/gobtools"
)

func init() {
	ConfiguredJarListGobRegId = gobtools.RegisterType(func() gobtools.CustomDec { return new(ConfiguredJarList) })
}

func (r ConfiguredJarList) Encode(ctx gobtools.EncContext, buf *bytes.Buffer) error {
	var err error

	if r.apexes == nil {
		if err = gobtools.EncodeInt(buf, -1); err != nil {
			return err
		}
	} else {
		if err = gobtools.EncodeInt(buf, len(r.apexes)); err != nil {
			return err
		}
		for val1 := 0; val1 < len(r.apexes); val1++ {
			if err = gobtools.EncodeString(buf, r.apexes[val1]); err != nil {
				return err
			}
		}
	}

	if r.jars == nil {
		if err = gobtools.EncodeInt(buf, -1); err != nil {
			return err
		}
	} else {
		if err = gobtools.EncodeInt(buf, len(r.jars)); err != nil {
			return err
		}
		for val2 := 0; val2 < len(r.jars); val2++ {
			if err = gobtools.EncodeString(buf, r.jars[val2]); err != nil {
				return err
			}
		}
	}
	return err
}

func (r *ConfiguredJarList) Decode(ctx gobtools.EncContext, buf *bytes.Reader) error {
	var err error

	var val2 int
	err = gobtools.DecodeInt(buf, &val2)
	if err != nil {
		return err
	}
	if val2 != -1 {
		r.apexes = make([]string, val2)
		for val3 := 0; val3 < int(val2); val3++ {
			err = gobtools.DecodeString(buf, &r.apexes[val3])
			if err != nil {
				return err
			}
		}
	}

	var val6 int
	err = gobtools.DecodeInt(buf, &val6)
	if err != nil {
		return err
	}
	if val6 != -1 {
		r.jars = make([]string, val6)
		for val7 := 0; val7 < int(val6); val7++ {
			err = gobtools.DecodeString(buf, &r.jars[val7])
			if err != nil {
				return err
			}
		}
	}

	return err
}

var ConfiguredJarListGobRegId int16

func (r ConfiguredJarList) GetTypeId() int16 {
	return ConfiguredJarListGobRegId
}
