// Copyright 2015 Google Inc. All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package android

import (
	"fmt"
	"strings"
	"unicode"

	"github.com/google/blueprint"
	"github.com/google/blueprint/proptools"
)

var (
	pctx = NewPackageContext("android/soong/android")

	cpPreserveSymlinks = pctx.VariableConfigMethod("cpPreserveSymlinks",
		Config.CpPreserveSymlinksFlags)

	HostPrebuiltTag = pctx.VariableConfigMethod("HostPrebuiltTag", Config.PrebuiltOS)

	// A phony rule that is not the built-in Ninja phony rule.  The built-in
	// phony rule has special behavior that is sometimes not desired.  See the
	// Ninja docs for more details.
	Phony = pctx.AndroidStaticRule("Phony",
		blueprint.RuleParams{
			Command:         "# phony $out",
			Description:     "phony $out",
			SandboxDisabled: true,
		})

	// GeneratedFile is a rule for indicating that a given file was generated
	// while running soong.  This allows the file to be cleaned up if it ever
	// stops being generated by soong.
	GeneratedFile = pctx.AndroidStaticRule("GeneratedFile",
		blueprint.RuleParams{
			Command:         "# generated $out",
			Description:     "generated $out",
			Generator:       true,
			SandboxDisabled: true,
		})

	// A copy rule.
	Cp = pctx.AndroidStaticRule("CpRule",
		blueprint.RuleParams{
			Command:     "${Rm} -f $out && ${Cp} $cpPreserveSymlinks $cpFlags $in $out$extraCmds",
			CommandDeps: []string{"Rm-deps", "Cp-deps"},
			Description: "cp $out",
		},
		"cpFlags", "extraCmds")

	// A copy rule wrapped with bash.
	CpWithBash = pctx.AndroidStaticRule("CpWithBash",
		blueprint.RuleParams{
			Command:     "/bin/bash -c \"${Rm} -f $out && ${Cp} $cpFlags $cpPreserveSymlinks $in $out$extraCmds\"",
			CommandDeps: []string{"Rm-deps", "Cp-deps"},
			Description: "cp $out",
		},
		"cpFlags", "extraCmds")

	// A copy rule that doesn't preserve symlinks.
	CpNoPreserveSymlink = pctx.AndroidStaticRule("CpNoPreserveSymlink",
		blueprint.RuleParams{
			Command:     "${Rm} -f $out && ${Cp} $cpFlags $in $out$extraCmds",
			CommandDeps: []string{"Rm-deps", "Cp-deps"},
			Description: "cp $out",
		},
		"cpFlags", "extraCmds")

	// A copy rule that only updates the output if it changed.
	CpIfChanged = pctx.AndroidStaticRule("CpIfChanged",
		blueprint.RuleParams{
			Command:     "if ! ${Cmp} -s $in $out; then ${Cp} $in $out; fi",
			CommandDeps: []string{"Cmp-deps", "Cp-deps"},
			Description: "cp if changed $out",
			Restat:      true,
		})

	CpExecutable = pctx.AndroidStaticRule("CpExecutable",
		blueprint.RuleParams{
			Command:     "${Rm} -f $out && ${Cp} $cpFlags $in $out && ${Chmod} +x $out$extraCmds",
			CommandDeps: []string{"Rm-deps", "Cp-deps", "Chmod-deps"},
			Description: "cp $out",
		},
		"cpFlags", "extraCmds")

	// A copy executable rule wrapped with bash
	CpExecutableWithBash = pctx.AndroidStaticRule("CpExecutableWithBash",
		blueprint.RuleParams{
			Command:     "/bin/bash -c \"(${Rm} -f $out && ${Cp} $cpFlags $cpPreserveSymlinks $in $out ) && (${Chmod} +x $out$extraCmds )\"",
			CommandDeps: []string{"Rm-deps", "Cp-deps", "Chmod-deps"},
			Description: "cp $out",
		},
		"cpFlags", "extraCmds")

	// A timestamp touch rule.
	Touch = pctx.AndroidStaticRule("TouchRule",
		blueprint.RuleParams{
			Command:     "${Touch} $out",
			CommandDeps: []string{"Touch-deps"},
			Description: "touch $out",
		})

	// A symlink rule.
	Symlink = pctx.AndroidStaticRule("Symlink",
		blueprint.RuleParams{
			Command:         "${Rm} -f $out && ${Ln} -f -s $fromPath $out",
			CommandDeps:     []string{"Rm-deps", "Ln-deps"},
			Description:     "symlink $out",
			SandboxDisabled: true,
		},
		"fromPath")

	// A symlink rule wrapped with bash
	SymlinkWithBash = pctx.AndroidStaticRule("SymlinkWithBash",
		blueprint.RuleParams{
			Command:         "/bin/bash -c \"${Rm} -f $out && ${Ln} -sfn $fromPath $out\"",
			CommandDeps:     []string{"Rm-deps", "Ln-deps"},
			Description:     "symlink $out",
			SandboxDisabled: true,
		},
		"fromPath")

	// A rule that always fails at execution time with the given error message.
	// The error message must be passed through proptools.NinjaAndShellEscape() first.
	// Calling ErrorRule() will do that for you and use this rule.
	errorRule = pctx.AndroidStaticRule("Error",
		blueprint.RuleParams{
			Command:     `${Echo} $error && false`,
			CommandDeps: []string{"Echo-deps"},
			Description: "error building $out",
		},
		"error")

	Cat = pctx.AndroidStaticRule("CatRule",
		blueprint.RuleParams{
			Command:     "${Rm} -f $out && ${Cat} $in > $out",
			CommandDeps: []string{"Rm-deps", "Cat-deps"},
			Description: "concatenate files to $out",
		})

	CatAndSort = pctx.AndroidStaticRule("CatAndSort",
		blueprint.RuleParams{
			Command:     "${Rm} -f $out && ${Cat} $in > $out && ${Sort} -o $out $out",
			CommandDeps: []string{"Rm-deps", "Cat-deps", "Sort-deps"},
			Description: "concatenate sorted file contents to $out",
		})

	CatAndSortAndUnique = pctx.AndroidStaticRule("CatAndSortAndUnique",
		blueprint.RuleParams{
			Command:     "${Rm} -f $out && ${Cat} $in > $out && ${Sort} -u -o $out $out",
			CommandDeps: []string{"Rm-deps", "Cat-deps", "Sort-deps"},
			Description: "concatenate sorted file contents to $out",
		})

	MergeZips = pctx.AndroidStaticRule("MergeZips",
		blueprint.RuleParams{
			Command: `${MergeZipsCmd} -s $out $in`,
			CommandDeps: []string{
				"${MergeZipsCmd}",
			},
			SandboxDisabled: true,
		})

	AssembleVintfRule = pctx.StaticRule("AssembleVintfRule", blueprint.RuleParams{
		Command:         `${Rm} -f $out && VINTF_IGNORE_TARGET_FCM_VERSION=true ${AssembleVintf} -i $in -o $out`,
		CommandDeps:     []string{"${AssembleVintf}", "Rm-deps"},
		Description:     "run assemble_vintf",
		SandboxDisabled: true,
	})

	depfileVerifierRule = pctx.AndroidStaticRule("DepfileVerifierRule",
		blueprint.RuleParams{
			Command:     "${Rm} -f $out && ${DepfileVerifier} $in && ${Touch} $out",
			CommandDeps: []string{"Rm-deps", "Touch-deps", "${DepfileVerifier}"},
			Description: "verify depfile",
		})

	// Used only when USE_REWRAPPER=true is set, to restrict non-RBE jobs to the local parallelism value
	localPool = blueprint.NewBuiltinPool("local_pool")

	// Used only by RuleBuilder to identify remoteable rules. Does not actually get created in ninja.
	remotePool = blueprint.NewBuiltinPool("remote_pool")

	// Used for processes that need significant RAM to ensure there are not too many running in parallel.
	highmemPool = blueprint.NewBuiltinPool("highmem_pool")
)

var commonToyboxSymlinks = []string{
	"basename",
	"cat",
	"chmod",
	"cmp",
	"comm",
	"cp",
	"cut",
	"date",
	"dd",
	"dirname",
	"dos2unix",
	"du",
	"echo",
	"egrep",
	"env",
	"file",
	"find",
	"getconf",
	"getopt",
	"grep",
	"gzip",
	"head",
	"hostname",
	"id",
	"install",
	"ln",
	"ls",
	"md5sum",
	"mkdir",
	"mktemp",
	"mv",
	"nl",
	"od",
	"paste",
	"patch",
	"printf",
	"pwd",
	"readlink",
	"realpath",
	"rm",
	"rmdir",
	"sed",
	"seq",
	"setsid",
	"sha1sum",
	"sha256sum",
	"sha512sum",
	"sleep",
	"sort",
	"stat",
	"tail",
	"tar",
	"tee",
	"test",
	"timeout",
	"touch",
	"tr",
	"true",
	"truncate",
	"uname",
	"uniq",
	"unix2dos",
	"wc",
	"which",
	"whoami",
	"xargs",
	"xxd",
}

func init() {
	pctx.Import("github.com/google/blueprint/bootstrap")

	pctx.VariableFunc("RBEWrapper", func(ctx PackageVarContext) string {
		return ctx.Config().RBEWrapper()
	})

	pctx.HostBinToolVariable("MergeZipsCmd", "merge_zips")
	pctx.HostBinToolVariable("AssembleVintf", "assemble_vintf")
	pctx.HostBinToolVariable("DepfileVerifier", "depfile_verifier")
	pctx.SourcePathVariable("toybox", "prebuilts/build-tools/${HostPrebuiltTag}/bin/toybox")

	// Create a variable for every toybox command. toybox_phonies_singleton will also create
	// a -deps phony, but we can't do that here because blueprint doesn't currently have a way to
	// create phonies in the init() function.
	for _, name := range commonToyboxSymlinks {
		varName := string(unicode.ToUpper(rune(name[0]))) + name[1:]
		pctx.SourcePathVariable(varName, "prebuilts/build-tools/path/${HostPrebuiltTag}/"+name)
	}

	InitRegistrationContext.RegisterParallelSingletonType("toybox_phonies_singleton", toyboxPhoniesSingletonFactory)
}

// CopyFileRule creates a ninja rule to copy path to outPath.
func CopyFileRule(ctx ModuleContext, path Path, outPath WritablePath, validations ...Path) {
	ctx.Build(pctx, BuildParams{
		Rule:        Cp,
		Input:       path,
		Output:      outPath,
		Description: "copy " + outPath.Base(),
		Validations: validations,
	})
}

// ErrorRule creates a ninja action that fails to build the given file, failing with the
// provided error message.
func ErrorRule(ctx BuilderContext, path WritablePath, msg string) {
	ctx.Build(pctx, BuildParams{
		Rule:   errorRule,
		Output: path,
		Args: map[string]string{
			"error": proptools.NinjaAndShellEscape(msg),
		},
	})
}

// IsErrorRule returns true if the given rule was created by ErrorRuleFunc. Intended for use
// in tests.
func IsErrorRule(rule blueprint.Rule) bool {
	return rule == errorRule
}

// DepfileVerifierRule creates a rule that will check that all the inputs in the given depfile
// are also listed in the given inputs. It will touch an empty outPath if successful. This can
// be used as a validation action for
func DepfileVerifierRule(ctx ModuleContext, outPath WritablePath, depfile Path, inputs Paths) {
	inputsFile := outPath.AddExtension(ctx, "inputs_list")
	var inputsFileContents strings.Builder
	for _, input := range inputs {
		inputsFileContents.WriteString(input.String())
		inputsFileContents.WriteString("\n")
	}
	WriteFileRuleVerbatim(ctx, inputsFile, inputsFileContents.String())

	ctx.Build(pctx, BuildParams{
		Rule:   depfileVerifierRule,
		Inputs: Paths{depfile, inputsFile},
		Output: outPath,
	})
}

type toyboxPhoniesSingleton struct{}

func toyboxPhoniesSingletonFactory() Singleton {
	return &toyboxPhoniesSingleton{}
}

// Generate the phonies for the deps in a singleton, as blueprint currently doesn't have
// a way to create phonies from the init() function.
func (t *toyboxPhoniesSingleton) GenerateBuildActions(ctx SingletonContext) {
	for _, name := range commonToyboxSymlinks {
		varName := string(unicode.ToUpper(rune(name[0]))) + name[1:]
		binary := PathForSource(ctx, fmt.Sprintf("prebuilts/build-tools/%s/bin/toybox", ctx.Config().PrebuiltOS()))
		symlink := PathForSource(ctx, fmt.Sprintf("prebuilts/build-tools/path/%s/%s", ctx.Config().PrebuiltOS(), name))
		ctx.Build(pctx, BuildParams{
			Rule:   blueprint.Phony,
			Output: PathForPhony(ctx, varName+"-deps"),
			Inputs: []Path{binary, symlink},
		})
	}
}
