// Copyright 2015 Google Inc. All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package android

import (
	"fmt"

	"github.com/google/blueprint"
	"github.com/google/blueprint/proptools"
)

var (
	pctx = NewPackageContext("android/soong/android")

	cpPreserveSymlinks = pctx.VariableConfigMethod("cpPreserveSymlinks",
		Config.CpPreserveSymlinksFlags)

	HostPrebuiltTag = pctx.VariableConfigMethod("HostPrebuiltTag", Config.PrebuiltOS)

	// A phony rule that is not the built-in Ninja phony rule.  The built-in
	// phony rule has special behavior that is sometimes not desired.  See the
	// Ninja docs for more details.
	Phony = pctx.AndroidStaticRule("Phony",
		blueprint.RuleParams{
			Command:         "# phony $out",
			Description:     "phony $out",
			SandboxDisabled: true,
		})

	// GeneratedFile is a rule for indicating that a given file was generated
	// while running soong.  This allows the file to be cleaned up if it ever
	// stops being generated by soong.
	GeneratedFile = pctx.AndroidStaticRule("GeneratedFile",
		blueprint.RuleParams{
			Command:         "# generated $out",
			Description:     "generated $out",
			Generator:       true,
			SandboxDisabled: true,
		})

	// A copy rule.
	Cp = pctx.AndroidStaticRule("Cp",
		blueprint.RuleParams{
			Command:     "${rm} -f $out && ${cp} $cpPreserveSymlinks $cpFlags $in $out$extraCmds",
			CommandDeps: []string{"${rm}", "${cp}"},
			Description: "cp $out",
		},
		"cpFlags", "extraCmds")

	// A copy rule wrapped with bash.
	CpWithBash = pctx.AndroidStaticRule("CpWithBash",
		blueprint.RuleParams{
			Command:     "/bin/bash -c \"${rm} -f $out && ${cp} $cpFlags $cpPreserveSymlinks $in $out$extraCmds\"",
			CommandDeps: []string{"${rm}", "${cp}"},
			Description: "cp $out",
		},
		"cpFlags", "extraCmds")

	// A copy rule wrapped with bash with bootstrapping
	CpWithBashBootstrap = pctx.AndroidStaticRule("CpWithBashBootstrap",
		blueprint.RuleParams{
			Command:     "/bin/bash -c \"${rmSrc} -f $out && ${cpSrc} $cpFlags $cpPreserveSymlinks $in $out$extraCmds\"",
			CommandDeps: []string{"${rmSrc}", "${cpSrc}", "${toybox}"},
			Description: "cp $out",
		},
		"cpFlags", "extraCmds")

	// A copy rule that doesn't preserve symlinks.
	CpNoPreserveSymlink = pctx.AndroidStaticRule("CpNoPreserveSymlink",
		blueprint.RuleParams{
			Command:     "${rm} -f $out && ${cp} $cpFlags $in $out$extraCmds",
			CommandDeps: []string{"${rm}", "${cp}"},
			Description: "cp $out",
		},
		"cpFlags", "extraCmds")

	// A copy rule that only updates the output if it changed.
	CpIfChanged = pctx.AndroidStaticRule("CpIfChanged",
		blueprint.RuleParams{
			Command:     "if ! ${cmp} -s $in $out; then ${cp} $in $out; fi",
			CommandDeps: []string{"${cmp}", "${cp}"},
			Description: "cp if changed $out",
			Restat:      true,
		})

	CpExecutable = pctx.AndroidStaticRule("CpExecutable",
		blueprint.RuleParams{
			Command:     "${rm} -f $out && ${cp} $cpFlags $in $out && ${chmod} +x $out$extraCmds",
			CommandDeps: []string{"${rm}", "${cp}", "${chmod}"},
			Description: "cp $out",
		},
		"cpFlags", "extraCmds")

	// A copy executable rule wrapped with bash
	CpExecutableWithBash = pctx.AndroidStaticRule("CpExecutableWithBash",
		blueprint.RuleParams{
			Command:     "/bin/bash -c \"(${rm} -f $out && ${cp} $cpFlags $cpPreserveSymlinks $in $out ) && (${chmod} +x $out$extraCmds )\"",
			CommandDeps: []string{"${rm}", "${cp}", "${chmod}"},
			Description: "cp $out",
		},
		"cpFlags", "extraCmds")

	// A copy executable rule wrapped with bash with bootstrapping
	CpExecutableWithBashBootstrap = pctx.AndroidStaticRule("CpExecutableWithBashBootstrap",
		blueprint.RuleParams{
			Command:         "/bin/bash -c \"(${rmSrc} -f $out && ${cpSrc} $cpFlags $cpPreserveSymlinks $in $out ) && (${chmodSrc} +x $out$extraCmds )\"",
			CommandDeps:     []string{"${rmSrc}", "${cpSrc}", "${chmodSrc}", "${toybox}"},
			Description:     "cp $out",
			SandboxDisabled: true,
		},
		"cpFlags", "extraCmds")

	// A timestamp touch rule.
	Touch = pctx.AndroidStaticRule("Touch",
		blueprint.RuleParams{
			Command:     "${touch} $out",
			CommandDeps: []string{"${touch}"},
			Description: "touch $out",
		})

	// A symlink rule.
	Symlink = pctx.AndroidStaticRule("Symlink",
		blueprint.RuleParams{
			Command:     "${rm} -f $out && ${ln} -f -s $fromPath $out",
			CommandDeps: []string{"${rm}", "${ln}"},
			Description: "symlink $out",
		},
		"fromPath")

	// A symlink rule wrapped with bash
	SymlinkWithBash = pctx.AndroidStaticRule("SymlinkWithBash",
		blueprint.RuleParams{
			Command:     "/bin/bash -c \"${rm} -f $out && ${ln} -sfn $fromPath $out\"",
			CommandDeps: []string{"${rm}", "${ln}"},
			Description: "symlink $out",
		},
		"fromPath")

	// A rule that always fails at execution time with the given error message.
	// The error message must be passed through proptools.NinjaAndShellEscape() first.
	// Calling ErrorRule() will do that for you and use this rule.
	errorRule = pctx.AndroidStaticRule("Error",
		blueprint.RuleParams{
			Command:     `${echo} $error && false`,
			CommandDeps: []string{"${echo}"},
			Description: "error building $out",
		},
		"error")

	Cat = pctx.AndroidStaticRule("Cat",
		blueprint.RuleParams{
			Command:     "${rm} -f $out && ${cat} $in > $out",
			CommandDeps: []string{"${rm}", "${cat}"},
			Description: "concatenate files to $out",
		})

	CatAndSort = pctx.AndroidStaticRule("CatAndSort",
		blueprint.RuleParams{
			Command:     "${rm} -f $out && ${cat} $in > $out && ${sort} -o $out $out",
			CommandDeps: []string{"${rm}", "${cat}", "${sort}"},
			Description: "concatenate sorted file contents to $out",
		})

	CatAndSortAndUnique = pctx.AndroidStaticRule("CatAndSortAndUnique",
		blueprint.RuleParams{
			Command:     "${rm} -f $out && ${cat} $in > $out && ${sort} -u -o $out $out",
			CommandDeps: []string{"${rm}", "${cat}", "${sort}"},
			Description: "concatenate sorted file contents to $out",
		})

	MergeZips = pctx.AndroidStaticRule("MergeZips",
		blueprint.RuleParams{
			Command: `${MergeZipsCmd} -s $out $in`,
			CommandDeps: []string{
				"${MergeZipsCmd}",
			},
			SandboxDisabled: true,
		})

	AssembleVintfRule = pctx.StaticRule("AssembleVintfRule", blueprint.RuleParams{
		Command:     `${rm} -f $out && VINTF_IGNORE_TARGET_FCM_VERSION=true ${AssembleVintf} -i $in -o $out`,
		CommandDeps: []string{"${AssembleVintf}", "${rm}"},
		Description: "run assemble_vintf",
	})

	// Used only when USE_REWRAPPER=true is set, to restrict non-RBE jobs to the local parallelism value
	localPool = blueprint.NewBuiltinPool("local_pool")

	// Used only by RuleBuilder to identify remoteable rules. Does not actually get created in ninja.
	remotePool = blueprint.NewBuiltinPool("remote_pool")

	// Used for processes that need significant RAM to ensure there are not too many running in parallel.
	highmemPool = blueprint.NewBuiltinPool("highmem_pool")
)

var commonToyboxSymlinks = []string{
	"basename",
	"cat",
	"chmod",
	"cmp",
	"comm",
	"cp",
	"cut",
	"date",
	"dd",
	"dirname",
	"dos2unix",
	"du",
	"echo",
	"egrep",
	"env",
	"file",
	"find",
	"getconf",
	"getopt",
	"grep",
	"gzip",
	"head",
	"hostname",
	"id",
	"install",
	"ln",
	"ls",
	"md5sum",
	"mkdir",
	"mktemp",
	"mv",
	"nl",
	"od",
	"paste",
	"patch",
	"printf",
	"pwd",
	"readlink",
	"realpath",
	"rm",
	"rmdir",
	"sed",
	"seq",
	"setsid",
	"sha1sum",
	"sha256sum",
	"sha512sum",
	"sleep",
	"sort",
	"stat",
	"tail",
	"tar",
	"tee",
	"test",
	"timeout",
	"touch",
	"tr",
	"true",
	"truncate",
	"uname",
	"uniq",
	"unix2dos",
	"wc",
	"which",
	"whoami",
	"xargs",
	"xxd",
}

func init() {
	pctx.Import("github.com/google/blueprint/bootstrap")

	pctx.VariableFunc("RBEWrapper", func(ctx PackageVarContext) string {
		return ctx.Config().RBEWrapper()
	})

	pctx.HostBinToolVariable("MergeZipsCmd", "merge_zips")
	pctx.HostBinToolVariable("AssembleVintf", "assemble_vintf")
	pctx.SourcePathVariable("toybox", "prebuilts/build-tools/${HostPrebuiltTag}/bin/toybox")

	hostBinToolSourcePathVariables := func(names []string) {
		for _, name := range names {
			pctx.SourcePathVariable(fmt.Sprintf("%sSrc", name), fmt.Sprintf("prebuilts/build-tools/path/${HostPrebuiltTag}/%s", name))
		}
	}

	hostBinToolVariables := func(names []string) {
		for _, name := range names {
			pctx.VariableFunc(name, func(ctx PackageVarContext) string {
				if ctx.Config().UseHostMusl() {
					return fmt.Sprintf("${%sSrc}", name)
				}
				return proptools.NinjaAndShellEscape(ctx.Config().HostToolPath(ctx, name).String())
			})
		}
	}

	hostBinToolSourcePathVariables(commonToyboxSymlinks)
	hostBinToolVariables(commonToyboxSymlinks)
}

// CopyFileRule creates a ninja rule to copy path to outPath.
func CopyFileRule(ctx ModuleContext, path Path, outPath WritablePath, validations ...Path) {
	ctx.Build(pctx, BuildParams{
		Rule:        Cp,
		Input:       path,
		Output:      outPath,
		Description: "copy " + outPath.Base(),
		Validations: validations,
	})
}

// ErrorRule creates a ninja action that fails to build the given file, failing with the
// provided error message.
func ErrorRule(ctx BuilderContext, path WritablePath, msg string) {
	ctx.Build(pctx, BuildParams{
		Rule:   errorRule,
		Output: path,
		Args: map[string]string{
			"error": proptools.NinjaAndShellEscape(msg),
		},
	})
}

// IsErrorRule returns true if the given rule was created by ErrorRuleFunc. Intended for use
// in tests.
func IsErrorRule(rule blueprint.Rule) bool {
	return rule == errorRule
}
