// Code generated by go run gob_gen.go; DO NOT EDIT.

package android

import (
	"bytes"
	"github.com/google/blueprint/gobtools"
)

func init() {
	DistGobRegId = gobtools.RegisterType(func() gobtools.CustomDec { return new(Dist) })
	InstallFilesInfoGobRegId = gobtools.RegisterType(func() gobtools.CustomDec { return new(InstallFilesInfo) })
	SourceFilesInfoGobRegId = gobtools.RegisterType(func() gobtools.CustomDec { return new(SourceFilesInfo) })
	ModuleBuildTargetsInfoGobRegId = gobtools.RegisterType(func() gobtools.CustomDec { return new(ModuleBuildTargetsInfo) })
	CommonModuleInfoGobRegId = gobtools.RegisterType(func() gobtools.CustomDec { return new(CommonModuleInfo) })
	ApiLevelOrPlatformGobRegId = gobtools.RegisterType(func() gobtools.CustomDec { return new(ApiLevelOrPlatform) })
	HostToolProviderInfoGobRegId = gobtools.RegisterType(func() gobtools.CustomDec { return new(HostToolProviderInfo) })
	DistInfoGobRegId = gobtools.RegisterType(func() gobtools.CustomDec { return new(DistInfo) })
	GeneratedSourceInfoGobRegId = gobtools.RegisterType(func() gobtools.CustomDec { return new(GeneratedSourceInfo) })
	katiInstallGobRegId = gobtools.RegisterType(func() gobtools.CustomDec { return new(katiInstall) })
	extraFilesZipGobRegId = gobtools.RegisterType(func() gobtools.CustomDec { return new(extraFilesZip) })
	OutputFilesInfoGobRegId = gobtools.RegisterType(func() gobtools.CustomDec { return new(OutputFilesInfo) })
	IdeInfoGobRegId = gobtools.RegisterType(func() gobtools.CustomDec { return new(IdeInfo) })
}

func (r Dist) Encode(ctx gobtools.EncContext, buf *bytes.Buffer) error {
	var err error

	if r.Targets == nil {
		if err = gobtools.EncodeInt(buf, -1); err != nil {
			return err
		}
	} else {
		if err = gobtools.EncodeInt(buf, len(r.Targets)); err != nil {
			return err
		}
		for val1 := 0; val1 < len(r.Targets); val1++ {
			if err = gobtools.EncodeString(buf, r.Targets[val1]); err != nil {
				return err
			}
		}
	}

	val2 := r.Dest == nil
	if err = gobtools.EncodeBool(buf, val2); err != nil {
		return err
	}
	if !val2 {
		if err = gobtools.EncodeString(buf, (*r.Dest)); err != nil {
			return err
		}
	}

	val3 := r.Dir == nil
	if err = gobtools.EncodeBool(buf, val3); err != nil {
		return err
	}
	if !val3 {
		if err = gobtools.EncodeString(buf, (*r.Dir)); err != nil {
			return err
		}
	}

	val4 := r.Suffix == nil
	if err = gobtools.EncodeBool(buf, val4); err != nil {
		return err
	}
	if !val4 {
		if err = gobtools.EncodeString(buf, (*r.Suffix)); err != nil {
			return err
		}
	}

	val5 := r.Append_artifact_with_product == nil
	if err = gobtools.EncodeBool(buf, val5); err != nil {
		return err
	}
	if !val5 {
		if err = gobtools.EncodeBool(buf, (*r.Append_artifact_with_product)); err != nil {
			return err
		}
	}

	val6 := r.Prepend_artifact_with_product == nil
	if err = gobtools.EncodeBool(buf, val6); err != nil {
		return err
	}
	if !val6 {
		if err = gobtools.EncodeBool(buf, (*r.Prepend_artifact_with_product)); err != nil {
			return err
		}
	}

	val7 := r.Tag == nil
	if err = gobtools.EncodeBool(buf, val7); err != nil {
		return err
	}
	if !val7 {
		if err = gobtools.EncodeString(buf, (*r.Tag)); err != nil {
			return err
		}
	}

	val8 := r.Only_on_java_coverage_builds == nil
	if err = gobtools.EncodeBool(buf, val8); err != nil {
		return err
	}
	if !val8 {
		if err = gobtools.EncodeBool(buf, (*r.Only_on_java_coverage_builds)); err != nil {
			return err
		}
	}
	return err
}

func (r *Dist) Decode(ctx gobtools.EncContext, buf *bytes.Reader) error {
	var err error

	var val2 int
	err = gobtools.DecodeInt(buf, &val2)
	if err != nil {
		return err
	}
	if val2 != -1 {
		r.Targets = make([]string, val2)
		for val3 := 0; val3 < int(val2); val3++ {
			err = gobtools.DecodeString(buf, &r.Targets[val3])
			if err != nil {
				return err
			}
		}
	}

	var val6 bool
	if err = gobtools.DecodeBool(buf, &val6); err != nil {
		return err
	}
	if !val6 {
		var val5 string
		err = gobtools.DecodeString(buf, &val5)
		if err != nil {
			return err
		}
		r.Dest = &val5
	}

	var val9 bool
	if err = gobtools.DecodeBool(buf, &val9); err != nil {
		return err
	}
	if !val9 {
		var val8 string
		err = gobtools.DecodeString(buf, &val8)
		if err != nil {
			return err
		}
		r.Dir = &val8
	}

	var val12 bool
	if err = gobtools.DecodeBool(buf, &val12); err != nil {
		return err
	}
	if !val12 {
		var val11 string
		err = gobtools.DecodeString(buf, &val11)
		if err != nil {
			return err
		}
		r.Suffix = &val11
	}

	var val15 bool
	if err = gobtools.DecodeBool(buf, &val15); err != nil {
		return err
	}
	if !val15 {
		var val14 bool
		err = gobtools.DecodeBool(buf, &val14)
		if err != nil {
			return err
		}
		r.Append_artifact_with_product = &val14
	}

	var val18 bool
	if err = gobtools.DecodeBool(buf, &val18); err != nil {
		return err
	}
	if !val18 {
		var val17 bool
		err = gobtools.DecodeBool(buf, &val17)
		if err != nil {
			return err
		}
		r.Prepend_artifact_with_product = &val17
	}

	var val21 bool
	if err = gobtools.DecodeBool(buf, &val21); err != nil {
		return err
	}
	if !val21 {
		var val20 string
		err = gobtools.DecodeString(buf, &val20)
		if err != nil {
			return err
		}
		r.Tag = &val20
	}

	var val24 bool
	if err = gobtools.DecodeBool(buf, &val24); err != nil {
		return err
	}
	if !val24 {
		var val23 bool
		err = gobtools.DecodeBool(buf, &val23)
		if err != nil {
			return err
		}
		r.Only_on_java_coverage_builds = &val23
	}

	return err
}

var DistGobRegId int16

func (r Dist) GetTypeId() int16 {
	return DistGobRegId
}

func (r InstallFilesInfo) Encode(ctx gobtools.EncContext, buf *bytes.Buffer) error {
	var err error

	if r.InstallFiles == nil {
		if err = gobtools.EncodeInt(buf, -1); err != nil {
			return err
		}
	} else {
		if err = gobtools.EncodeInt(buf, len(r.InstallFiles)); err != nil {
			return err
		}
		for val1 := 0; val1 < len(r.InstallFiles); val1++ {
			if err = r.InstallFiles[val1].Encode(ctx, buf); err != nil {
				return err
			}
		}
	}

	if r.CheckbuildFiles == nil {
		if err = gobtools.EncodeInt(buf, -1); err != nil {
			return err
		}
	} else {
		if err = gobtools.EncodeInt(buf, len(r.CheckbuildFiles)); err != nil {
			return err
		}
		for val2 := 0; val2 < len(r.CheckbuildFiles); val2++ {
			if err = gobtools.EncodeInterface(ctx, buf, r.CheckbuildFiles[val2]); err != nil {
				return err
			}
		}
	}

	if err = gobtools.EncodeBool(buf, r.UncheckedModule); err != nil {
		return err
	}

	if r.PackagingSpecs == nil {
		if err = gobtools.EncodeInt(buf, -1); err != nil {
			return err
		}
	} else {
		if err = gobtools.EncodeInt(buf, len(r.PackagingSpecs)); err != nil {
			return err
		}
		for val3 := 0; val3 < len(r.PackagingSpecs); val3++ {
			if err = r.PackagingSpecs[val3].Encode(ctx, buf); err != nil {
				return err
			}
		}
	}

	if r.KatiInstalls == nil {
		if err = gobtools.EncodeInt(buf, -1); err != nil {
			return err
		}
	} else {
		if err = gobtools.EncodeInt(buf, len(r.KatiInstalls)); err != nil {
			return err
		}
		for val4 := 0; val4 < len(r.KatiInstalls); val4++ {
			if err = r.KatiInstalls[val4].Encode(ctx, buf); err != nil {
				return err
			}
		}
	}

	if r.KatiSymlinks == nil {
		if err = gobtools.EncodeInt(buf, -1); err != nil {
			return err
		}
	} else {
		if err = gobtools.EncodeInt(buf, len(r.KatiSymlinks)); err != nil {
			return err
		}
		for val5 := 0; val5 < len(r.KatiSymlinks); val5++ {
			if err = r.KatiSymlinks[val5].Encode(ctx, buf); err != nil {
				return err
			}
		}
	}

	if r.TestData == nil {
		if err = gobtools.EncodeInt(buf, -1); err != nil {
			return err
		}
	} else {
		if err = gobtools.EncodeInt(buf, len(r.TestData)); err != nil {
			return err
		}
		for val6 := 0; val6 < len(r.TestData); val6++ {
			if err = r.TestData[val6].Encode(ctx, buf); err != nil {
				return err
			}
		}
	}

	if err = r.TransitivePackagingSpecs.Encode(ctx, buf); err != nil {
		return err
	}

	if err = gobtools.EncodeInterface(ctx, buf, r.LicenseMetadataFile); err != nil {
		return err
	}

	if err = r.TransitiveInstallFiles.Encode(ctx, buf); err != nil {
		return err
	}

	if r.KatiInitRcInstalls == nil {
		if err = gobtools.EncodeInt(buf, -1); err != nil {
			return err
		}
	} else {
		if err = gobtools.EncodeInt(buf, len(r.KatiInitRcInstalls)); err != nil {
			return err
		}
		for val7 := 0; val7 < len(r.KatiInitRcInstalls); val7++ {
			if err = r.KatiInitRcInstalls[val7].Encode(ctx, buf); err != nil {
				return err
			}
		}
	}

	if r.KatiVintfInstalls == nil {
		if err = gobtools.EncodeInt(buf, -1); err != nil {
			return err
		}
	} else {
		if err = gobtools.EncodeInt(buf, len(r.KatiVintfInstalls)); err != nil {
			return err
		}
		for val8 := 0; val8 < len(r.KatiVintfInstalls); val8++ {
			if err = r.KatiVintfInstalls[val8].Encode(ctx, buf); err != nil {
				return err
			}
		}
	}

	if r.InitRcPaths == nil {
		if err = gobtools.EncodeInt(buf, -1); err != nil {
			return err
		}
	} else {
		if err = gobtools.EncodeInt(buf, len(r.InitRcPaths)); err != nil {
			return err
		}
		for val9 := 0; val9 < len(r.InitRcPaths); val9++ {
			if err = gobtools.EncodeInterface(ctx, buf, r.InitRcPaths[val9]); err != nil {
				return err
			}
		}
	}

	if r.VintfFragmentsPaths == nil {
		if err = gobtools.EncodeInt(buf, -1); err != nil {
			return err
		}
	} else {
		if err = gobtools.EncodeInt(buf, len(r.VintfFragmentsPaths)); err != nil {
			return err
		}
		for val10 := 0; val10 < len(r.VintfFragmentsPaths); val10++ {
			if err = gobtools.EncodeInterface(ctx, buf, r.VintfFragmentsPaths[val10]); err != nil {
				return err
			}
		}
	}

	if r.InstalledInitRcPaths == nil {
		if err = gobtools.EncodeInt(buf, -1); err != nil {
			return err
		}
	} else {
		if err = gobtools.EncodeInt(buf, len(r.InstalledInitRcPaths)); err != nil {
			return err
		}
		for val11 := 0; val11 < len(r.InstalledInitRcPaths); val11++ {
			if err = r.InstalledInitRcPaths[val11].Encode(ctx, buf); err != nil {
				return err
			}
		}
	}

	if r.InstalledVintfFragmentsPaths == nil {
		if err = gobtools.EncodeInt(buf, -1); err != nil {
			return err
		}
	} else {
		if err = gobtools.EncodeInt(buf, len(r.InstalledVintfFragmentsPaths)); err != nil {
			return err
		}
		for val12 := 0; val12 < len(r.InstalledVintfFragmentsPaths); val12++ {
			if err = r.InstalledVintfFragmentsPaths[val12].Encode(ctx, buf); err != nil {
				return err
			}
		}
	}

	if r.DistFiles == nil {
		if err = gobtools.EncodeInt(buf, -1); err != nil {
			return err
		}
	} else {
		if err = gobtools.EncodeInt(buf, len(r.DistFiles)); err != nil {
			return err
		}
		for val13, val14 := range r.DistFiles {
			if err = gobtools.EncodeString(buf, val13); err != nil {
				return err
			}
			if val14 == nil {
				if err = gobtools.EncodeInt(buf, -1); err != nil {
					return err
				}
			} else {
				if err = gobtools.EncodeInt(buf, len(val14)); err != nil {
					return err
				}
				for val15 := 0; val15 < len(val14); val15++ {
					if err = gobtools.EncodeInterface(ctx, buf, val14[val15]); err != nil {
						return err
					}
				}
			}
		}
	}
	return err
}

func (r *InstallFilesInfo) Decode(ctx gobtools.EncContext, buf *bytes.Reader) error {
	var err error

	var val3 int
	err = gobtools.DecodeInt(buf, &val3)
	if err != nil {
		return err
	}
	if val3 != -1 {
		r.InstallFiles = make([]InstallPath, val3)
		for val4 := 0; val4 < int(val3); val4++ {
			if err = r.InstallFiles[val4].Decode(ctx, buf); err != nil {
				return err
			}
		}
	}

	var val8 int
	err = gobtools.DecodeInt(buf, &val8)
	if err != nil {
		return err
	}
	if val8 != -1 {
		r.CheckbuildFiles = make([]Path, val8)
		for val9 := 0; val9 < int(val8); val9++ {
			if val11, err := gobtools.DecodeInterface(ctx, buf); err != nil {
				return err
			} else if val11 == nil {
				r.CheckbuildFiles[val9] = nil
			} else {
				r.CheckbuildFiles[val9] = val11.(Path)
			}
		}
	}

	err = gobtools.DecodeBool(buf, &r.UncheckedModule)
	if err != nil {
		return err
	}

	var val14 int
	err = gobtools.DecodeInt(buf, &val14)
	if err != nil {
		return err
	}
	if val14 != -1 {
		r.PackagingSpecs = make([]PackagingSpec, val14)
		for val15 := 0; val15 < int(val14); val15++ {
			if err = r.PackagingSpecs[val15].Decode(ctx, buf); err != nil {
				return err
			}
		}
	}

	var val19 int
	err = gobtools.DecodeInt(buf, &val19)
	if err != nil {
		return err
	}
	if val19 != -1 {
		r.KatiInstalls = make([]katiInstall, val19)
		for val20 := 0; val20 < int(val19); val20++ {
			if err = r.KatiInstalls[val20].Decode(ctx, buf); err != nil {
				return err
			}
		}
	}

	var val24 int
	err = gobtools.DecodeInt(buf, &val24)
	if err != nil {
		return err
	}
	if val24 != -1 {
		r.KatiSymlinks = make([]katiInstall, val24)
		for val25 := 0; val25 < int(val24); val25++ {
			if err = r.KatiSymlinks[val25].Decode(ctx, buf); err != nil {
				return err
			}
		}
	}

	var val28 int
	err = gobtools.DecodeInt(buf, &val28)
	if err != nil {
		return err
	}
	if val28 != -1 {
		r.TestData = make([]DataPath, val28)
		for val29 := 0; val29 < int(val28); val29++ {
			if err = r.TestData[val29].Decode(ctx, buf); err != nil {
				return err
			}
		}
	}

	if err = r.TransitivePackagingSpecs.Decode(ctx, buf); err != nil {
		return err
	}

	if val33, err := gobtools.DecodeInterface(ctx, buf); err != nil {
		return err
	} else if val33 == nil {
		r.LicenseMetadataFile = nil
	} else {
		r.LicenseMetadataFile = val33.(WritablePath)
	}

	if err = r.TransitiveInstallFiles.Decode(ctx, buf); err != nil {
		return err
	}

	var val37 int
	err = gobtools.DecodeInt(buf, &val37)
	if err != nil {
		return err
	}
	if val37 != -1 {
		r.KatiInitRcInstalls = make([]katiInstall, val37)
		for val38 := 0; val38 < int(val37); val38++ {
			if err = r.KatiInitRcInstalls[val38].Decode(ctx, buf); err != nil {
				return err
			}
		}
	}

	var val42 int
	err = gobtools.DecodeInt(buf, &val42)
	if err != nil {
		return err
	}
	if val42 != -1 {
		r.KatiVintfInstalls = make([]katiInstall, val42)
		for val43 := 0; val43 < int(val42); val43++ {
			if err = r.KatiVintfInstalls[val43].Decode(ctx, buf); err != nil {
				return err
			}
		}
	}

	var val47 int
	err = gobtools.DecodeInt(buf, &val47)
	if err != nil {
		return err
	}
	if val47 != -1 {
		r.InitRcPaths = make([]Path, val47)
		for val48 := 0; val48 < int(val47); val48++ {
			if val50, err := gobtools.DecodeInterface(ctx, buf); err != nil {
				return err
			} else if val50 == nil {
				r.InitRcPaths[val48] = nil
			} else {
				r.InitRcPaths[val48] = val50.(Path)
			}
		}
	}

	var val53 int
	err = gobtools.DecodeInt(buf, &val53)
	if err != nil {
		return err
	}
	if val53 != -1 {
		r.VintfFragmentsPaths = make([]Path, val53)
		for val54 := 0; val54 < int(val53); val54++ {
			if val56, err := gobtools.DecodeInterface(ctx, buf); err != nil {
				return err
			} else if val56 == nil {
				r.VintfFragmentsPaths[val54] = nil
			} else {
				r.VintfFragmentsPaths[val54] = val56.(Path)
			}
		}
	}

	var val59 int
	err = gobtools.DecodeInt(buf, &val59)
	if err != nil {
		return err
	}
	if val59 != -1 {
		r.InstalledInitRcPaths = make([]InstallPath, val59)
		for val60 := 0; val60 < int(val59); val60++ {
			if err = r.InstalledInitRcPaths[val60].Decode(ctx, buf); err != nil {
				return err
			}
		}
	}

	var val64 int
	err = gobtools.DecodeInt(buf, &val64)
	if err != nil {
		return err
	}
	if val64 != -1 {
		r.InstalledVintfFragmentsPaths = make([]InstallPath, val64)
		for val65 := 0; val65 < int(val64); val65++ {
			if err = r.InstalledVintfFragmentsPaths[val65].Decode(ctx, buf); err != nil {
				return err
			}
		}
	}

	var val68 int
	err = gobtools.DecodeInt(buf, &val68)
	if err != nil {
		return err
	}
	if val68 != -1 {
		r.DistFiles = make(map[string]Paths, val68)
		for val69 := 0; val69 < int(val68); val69++ {
			var val70 string
			var val71 Paths
			err = gobtools.DecodeString(buf, &val70)
			if err != nil {
				return err
			}
			var val75 int
			err = gobtools.DecodeInt(buf, &val75)
			if err != nil {
				return err
			}
			if val75 != -1 {
				val71 = make([]Path, val75)
				for val76 := 0; val76 < int(val75); val76++ {
					if val78, err := gobtools.DecodeInterface(ctx, buf); err != nil {
						return err
					} else if val78 == nil {
						val71[val76] = nil
					} else {
						val71[val76] = val78.(Path)
					}
				}
			}
			r.DistFiles[val70] = val71
		}
	}

	return err
}

var InstallFilesInfoGobRegId int16

func (r InstallFilesInfo) GetTypeId() int16 {
	return InstallFilesInfoGobRegId
}

func (r SourceFilesInfo) Encode(ctx gobtools.EncContext, buf *bytes.Buffer) error {
	var err error

	if r.Srcs == nil {
		if err = gobtools.EncodeInt(buf, -1); err != nil {
			return err
		}
	} else {
		if err = gobtools.EncodeInt(buf, len(r.Srcs)); err != nil {
			return err
		}
		for val1 := 0; val1 < len(r.Srcs); val1++ {
			if err = gobtools.EncodeInterface(ctx, buf, r.Srcs[val1]); err != nil {
				return err
			}
		}
	}
	return err
}

func (r *SourceFilesInfo) Decode(ctx gobtools.EncContext, buf *bytes.Reader) error {
	var err error

	var val3 int
	err = gobtools.DecodeInt(buf, &val3)
	if err != nil {
		return err
	}
	if val3 != -1 {
		r.Srcs = make([]Path, val3)
		for val4 := 0; val4 < int(val3); val4++ {
			if val6, err := gobtools.DecodeInterface(ctx, buf); err != nil {
				return err
			} else if val6 == nil {
				r.Srcs[val4] = nil
			} else {
				r.Srcs[val4] = val6.(Path)
			}
		}
	}

	return err
}

var SourceFilesInfoGobRegId int16

func (r SourceFilesInfo) GetTypeId() int16 {
	return SourceFilesInfoGobRegId
}

func (r ModuleBuildTargetsInfo) Encode(ctx gobtools.EncContext, buf *bytes.Buffer) error {
	var err error

	if err = gobtools.EncodeInterface(ctx, buf, r.InstallTarget); err != nil {
		return err
	}

	if err = gobtools.EncodeInterface(ctx, buf, r.OutputsTarget); err != nil {
		return err
	}

	if err = gobtools.EncodeInterface(ctx, buf, r.CheckbuildTarget); err != nil {
		return err
	}

	if err = gobtools.EncodeInterface(ctx, buf, r.ModulePhonyTarget); err != nil {
		return err
	}

	if err = gobtools.EncodeBool(buf, r.NamespaceExportedToMake); err != nil {
		return err
	}

	if err = gobtools.EncodeString(buf, r.BlueprintDir); err != nil {
		return err
	}
	return err
}

func (r *ModuleBuildTargetsInfo) Decode(ctx gobtools.EncContext, buf *bytes.Reader) error {
	var err error

	if val2, err := gobtools.DecodeInterface(ctx, buf); err != nil {
		return err
	} else if val2 == nil {
		r.InstallTarget = nil
	} else {
		r.InstallTarget = val2.(Path)
	}

	if val4, err := gobtools.DecodeInterface(ctx, buf); err != nil {
		return err
	} else if val4 == nil {
		r.OutputsTarget = nil
	} else {
		r.OutputsTarget = val4.(Path)
	}

	if val6, err := gobtools.DecodeInterface(ctx, buf); err != nil {
		return err
	} else if val6 == nil {
		r.CheckbuildTarget = nil
	} else {
		r.CheckbuildTarget = val6.(Path)
	}

	if val8, err := gobtools.DecodeInterface(ctx, buf); err != nil {
		return err
	} else if val8 == nil {
		r.ModulePhonyTarget = nil
	} else {
		r.ModulePhonyTarget = val8.(Path)
	}

	err = gobtools.DecodeBool(buf, &r.NamespaceExportedToMake)
	if err != nil {
		return err
	}

	err = gobtools.DecodeString(buf, &r.BlueprintDir)
	if err != nil {
		return err
	}

	return err
}

var ModuleBuildTargetsInfoGobRegId int16

func (r ModuleBuildTargetsInfo) GetTypeId() int16 {
	return ModuleBuildTargetsInfoGobRegId
}

func (r CommonModuleInfo) Encode(ctx gobtools.EncContext, buf *bytes.Buffer) error {
	var err error

	if err = gobtools.EncodeBool(buf, r.Enabled); err != nil {
		return err
	}

	if err = r.Target.Encode(ctx, buf); err != nil {
		return err
	}

	if err = gobtools.EncodeBool(buf, r.SkipAndroidMkProcessing); err != nil {
		return err
	}

	if err = gobtools.EncodeString(buf, r.BaseModuleName); err != nil {
		return err
	}

	if err = gobtools.EncodeBool(buf, r.CanHaveApexVariants); err != nil {
		return err
	}

	if err = r.MinSdkVersion.Encode(ctx, buf); err != nil {
		return err
	}

	if err = gobtools.EncodeString(buf, r.SdkVersion); err != nil {
		return err
	}

	if err = gobtools.EncodeBool(buf, r.NotInPlatform); err != nil {
		return err
	}

	if err = gobtools.EncodeBool(buf, r.UninstallableApexPlatformVariant); err != nil {
		return err
	}

	if err = r.MinSdkVersionSupported.Encode(ctx, buf); err != nil {
		return err
	}

	if err = gobtools.EncodeBool(buf, r.ModuleWithMinSdkVersionCheck); err != nil {
		return err
	}

	if err = gobtools.EncodeBool(buf, r.IsInstallableToApex); err != nil {
		return err
	}

	if err = gobtools.EncodeBool(buf, r.HideFromMake); err != nil {
		return err
	}

	if err = gobtools.EncodeBool(buf, r.SkipInstall); err != nil {
		return err
	}

	if err = gobtools.EncodeBool(buf, r.IsStubsModule); err != nil {
		return err
	}

	if err = gobtools.EncodeBool(buf, r.Host); err != nil {
		return err
	}

	if err = gobtools.EncodeBool(buf, r.IsApexModule); err != nil {
		return err
	}

	if err = gobtools.EncodeString(buf, r.Owner); err != nil {
		return err
	}

	if err = gobtools.EncodeBool(buf, r.Vendor); err != nil {
		return err
	}

	if err = gobtools.EncodeBool(buf, r.Proprietary); err != nil {
		return err
	}

	if err = gobtools.EncodeBool(buf, r.SocSpecific); err != nil {
		return err
	}

	if err = gobtools.EncodeBool(buf, r.ProductSpecific); err != nil {
		return err
	}

	if err = gobtools.EncodeBool(buf, r.SystemExtSpecific); err != nil {
		return err
	}

	if err = gobtools.EncodeBool(buf, r.DeviceSpecific); err != nil {
		return err
	}

	if err = gobtools.EncodeBool(buf, r.UseGenericConfig); err != nil {
		return err
	}

	if err = gobtools.EncodeBool(buf, r.NoFullInstall); err != nil {
		return err
	}

	if err = gobtools.EncodeBool(buf, r.InVendorRamdisk); err != nil {
		return err
	}

	if err = gobtools.EncodeBool(buf, r.ExemptFromRequiredApplicableLicensesProperty); err != nil {
		return err
	}

	if r.RequiredModuleNames == nil {
		if err = gobtools.EncodeInt(buf, -1); err != nil {
			return err
		}
	} else {
		if err = gobtools.EncodeInt(buf, len(r.RequiredModuleNames)); err != nil {
			return err
		}
		for val1 := 0; val1 < len(r.RequiredModuleNames); val1++ {
			if err = gobtools.EncodeString(buf, r.RequiredModuleNames[val1]); err != nil {
				return err
			}
		}
	}

	if r.HostRequiredModuleNames == nil {
		if err = gobtools.EncodeInt(buf, -1); err != nil {
			return err
		}
	} else {
		if err = gobtools.EncodeInt(buf, len(r.HostRequiredModuleNames)); err != nil {
			return err
		}
		for val2 := 0; val2 < len(r.HostRequiredModuleNames); val2++ {
			if err = gobtools.EncodeString(buf, r.HostRequiredModuleNames[val2]); err != nil {
				return err
			}
		}
	}

	if r.TargetRequiredModuleNames == nil {
		if err = gobtools.EncodeInt(buf, -1); err != nil {
			return err
		}
	} else {
		if err = gobtools.EncodeInt(buf, len(r.TargetRequiredModuleNames)); err != nil {
			return err
		}
		for val3 := 0; val3 < len(r.TargetRequiredModuleNames); val3++ {
			if err = gobtools.EncodeString(buf, r.TargetRequiredModuleNames[val3]); err != nil {
				return err
			}
		}
	}

	if r.VintfFragmentModuleNames == nil {
		if err = gobtools.EncodeInt(buf, -1); err != nil {
			return err
		}
	} else {
		if err = gobtools.EncodeInt(buf, len(r.VintfFragmentModuleNames)); err != nil {
			return err
		}
		for val4 := 0; val4 < len(r.VintfFragmentModuleNames); val4++ {
			if err = gobtools.EncodeString(buf, r.VintfFragmentModuleNames[val4]); err != nil {
				return err
			}
		}
	}

	if r.Dists == nil {
		if err = gobtools.EncodeInt(buf, -1); err != nil {
			return err
		}
	} else {
		if err = gobtools.EncodeInt(buf, len(r.Dists)); err != nil {
			return err
		}
		for val5 := 0; val5 < len(r.Dists); val5++ {
			if err = r.Dists[val5].Encode(ctx, buf); err != nil {
				return err
			}
		}
	}

	if err = gobtools.EncodeBool(buf, r.ExportedToMake); err != nil {
		return err
	}

	if err = gobtools.EncodeString(buf, r.Team); err != nil {
		return err
	}

	if err = gobtools.EncodeString(buf, r.PartitionTag); err != nil {
		return err
	}

	if r.ApexAvailable == nil {
		if err = gobtools.EncodeInt(buf, -1); err != nil {
			return err
		}
	} else {
		if err = gobtools.EncodeInt(buf, len(r.ApexAvailable)); err != nil {
			return err
		}
		for val6 := 0; val6 < len(r.ApexAvailable); val6++ {
			if err = gobtools.EncodeString(buf, r.ApexAvailable[val6]); err != nil {
				return err
			}
		}
	}

	if r.ApexAvailableFor == nil {
		if err = gobtools.EncodeInt(buf, -1); err != nil {
			return err
		}
	} else {
		if err = gobtools.EncodeInt(buf, len(r.ApexAvailableFor)); err != nil {
			return err
		}
		for val7 := 0; val7 < len(r.ApexAvailableFor); val7++ {
			if err = gobtools.EncodeString(buf, r.ApexAvailableFor[val7]); err != nil {
				return err
			}
		}
	}

	if err = r.ImageVariation.Encode(ctx, buf); err != nil {
		return err
	}

	if err = gobtools.EncodeBool(buf, r.IsNonPrimaryImageVariation); err != nil {
		return err
	}
	return err
}

func (r *CommonModuleInfo) Decode(ctx gobtools.EncContext, buf *bytes.Reader) error {
	var err error

	err = gobtools.DecodeBool(buf, &r.Enabled)
	if err != nil {
		return err
	}

	if err = r.Target.Decode(ctx, buf); err != nil {
		return err
	}

	err = gobtools.DecodeBool(buf, &r.SkipAndroidMkProcessing)
	if err != nil {
		return err
	}

	err = gobtools.DecodeString(buf, &r.BaseModuleName)
	if err != nil {
		return err
	}

	err = gobtools.DecodeBool(buf, &r.CanHaveApexVariants)
	if err != nil {
		return err
	}

	if err = r.MinSdkVersion.Decode(ctx, buf); err != nil {
		return err
	}

	err = gobtools.DecodeString(buf, &r.SdkVersion)
	if err != nil {
		return err
	}

	err = gobtools.DecodeBool(buf, &r.NotInPlatform)
	if err != nil {
		return err
	}

	err = gobtools.DecodeBool(buf, &r.UninstallableApexPlatformVariant)
	if err != nil {
		return err
	}

	if err = r.MinSdkVersionSupported.Decode(ctx, buf); err != nil {
		return err
	}

	err = gobtools.DecodeBool(buf, &r.ModuleWithMinSdkVersionCheck)
	if err != nil {
		return err
	}

	err = gobtools.DecodeBool(buf, &r.IsInstallableToApex)
	if err != nil {
		return err
	}

	err = gobtools.DecodeBool(buf, &r.HideFromMake)
	if err != nil {
		return err
	}

	err = gobtools.DecodeBool(buf, &r.SkipInstall)
	if err != nil {
		return err
	}

	err = gobtools.DecodeBool(buf, &r.IsStubsModule)
	if err != nil {
		return err
	}

	err = gobtools.DecodeBool(buf, &r.Host)
	if err != nil {
		return err
	}

	err = gobtools.DecodeBool(buf, &r.IsApexModule)
	if err != nil {
		return err
	}

	err = gobtools.DecodeString(buf, &r.Owner)
	if err != nil {
		return err
	}

	err = gobtools.DecodeBool(buf, &r.Vendor)
	if err != nil {
		return err
	}

	err = gobtools.DecodeBool(buf, &r.Proprietary)
	if err != nil {
		return err
	}

	err = gobtools.DecodeBool(buf, &r.SocSpecific)
	if err != nil {
		return err
	}

	err = gobtools.DecodeBool(buf, &r.ProductSpecific)
	if err != nil {
		return err
	}

	err = gobtools.DecodeBool(buf, &r.SystemExtSpecific)
	if err != nil {
		return err
	}

	err = gobtools.DecodeBool(buf, &r.DeviceSpecific)
	if err != nil {
		return err
	}

	err = gobtools.DecodeBool(buf, &r.UseGenericConfig)
	if err != nil {
		return err
	}

	err = gobtools.DecodeBool(buf, &r.NoFullInstall)
	if err != nil {
		return err
	}

	err = gobtools.DecodeBool(buf, &r.InVendorRamdisk)
	if err != nil {
		return err
	}

	err = gobtools.DecodeBool(buf, &r.ExemptFromRequiredApplicableLicensesProperty)
	if err != nil {
		return err
	}

	var val30 int
	err = gobtools.DecodeInt(buf, &val30)
	if err != nil {
		return err
	}
	if val30 != -1 {
		r.RequiredModuleNames = make([]string, val30)
		for val31 := 0; val31 < int(val30); val31++ {
			err = gobtools.DecodeString(buf, &r.RequiredModuleNames[val31])
			if err != nil {
				return err
			}
		}
	}

	var val34 int
	err = gobtools.DecodeInt(buf, &val34)
	if err != nil {
		return err
	}
	if val34 != -1 {
		r.HostRequiredModuleNames = make([]string, val34)
		for val35 := 0; val35 < int(val34); val35++ {
			err = gobtools.DecodeString(buf, &r.HostRequiredModuleNames[val35])
			if err != nil {
				return err
			}
		}
	}

	var val38 int
	err = gobtools.DecodeInt(buf, &val38)
	if err != nil {
		return err
	}
	if val38 != -1 {
		r.TargetRequiredModuleNames = make([]string, val38)
		for val39 := 0; val39 < int(val38); val39++ {
			err = gobtools.DecodeString(buf, &r.TargetRequiredModuleNames[val39])
			if err != nil {
				return err
			}
		}
	}

	var val42 int
	err = gobtools.DecodeInt(buf, &val42)
	if err != nil {
		return err
	}
	if val42 != -1 {
		r.VintfFragmentModuleNames = make([]string, val42)
		for val43 := 0; val43 < int(val42); val43++ {
			err = gobtools.DecodeString(buf, &r.VintfFragmentModuleNames[val43])
			if err != nil {
				return err
			}
		}
	}

	var val46 int
	err = gobtools.DecodeInt(buf, &val46)
	if err != nil {
		return err
	}
	if val46 != -1 {
		r.Dists = make([]Dist, val46)
		for val47 := 0; val47 < int(val46); val47++ {
			if err = r.Dists[val47].Decode(ctx, buf); err != nil {
				return err
			}
		}
	}

	err = gobtools.DecodeBool(buf, &r.ExportedToMake)
	if err != nil {
		return err
	}

	err = gobtools.DecodeString(buf, &r.Team)
	if err != nil {
		return err
	}

	err = gobtools.DecodeString(buf, &r.PartitionTag)
	if err != nil {
		return err
	}

	var val53 int
	err = gobtools.DecodeInt(buf, &val53)
	if err != nil {
		return err
	}
	if val53 != -1 {
		r.ApexAvailable = make([]string, val53)
		for val54 := 0; val54 < int(val53); val54++ {
			err = gobtools.DecodeString(buf, &r.ApexAvailable[val54])
			if err != nil {
				return err
			}
		}
	}

	var val57 int
	err = gobtools.DecodeInt(buf, &val57)
	if err != nil {
		return err
	}
	if val57 != -1 {
		r.ApexAvailableFor = make([]string, val57)
		for val58 := 0; val58 < int(val57); val58++ {
			err = gobtools.DecodeString(buf, &r.ApexAvailableFor[val58])
			if err != nil {
				return err
			}
		}
	}

	if err = r.ImageVariation.Decode(ctx, buf); err != nil {
		return err
	}

	err = gobtools.DecodeBool(buf, &r.IsNonPrimaryImageVariation)
	if err != nil {
		return err
	}

	return err
}

var CommonModuleInfoGobRegId int16

func (r CommonModuleInfo) GetTypeId() int16 {
	return CommonModuleInfoGobRegId
}

func (r ApiLevelOrPlatform) Encode(ctx gobtools.EncContext, buf *bytes.Buffer) error {
	var err error

	val1 := r.ApiLevel == nil
	if err = gobtools.EncodeBool(buf, val1); err != nil {
		return err
	}
	if !val1 {
		if err = (*r.ApiLevel).Encode(ctx, buf); err != nil {
			return err
		}
	}

	if err = gobtools.EncodeBool(buf, r.IsPlatform); err != nil {
		return err
	}
	return err
}

func (r *ApiLevelOrPlatform) Decode(ctx gobtools.EncContext, buf *bytes.Reader) error {
	var err error

	var val2 bool
	if err = gobtools.DecodeBool(buf, &val2); err != nil {
		return err
	}
	if !val2 {
		var val1 ApiLevel
		if err = val1.Decode(ctx, buf); err != nil {
			return err
		}
		r.ApiLevel = &val1
	}

	err = gobtools.DecodeBool(buf, &r.IsPlatform)
	if err != nil {
		return err
	}

	return err
}

var ApiLevelOrPlatformGobRegId int16

func (r ApiLevelOrPlatform) GetTypeId() int16 {
	return ApiLevelOrPlatformGobRegId
}

func (r HostToolProviderInfo) Encode(ctx gobtools.EncContext, buf *bytes.Buffer) error {
	var err error

	if err = r.HostToolPath.Encode(ctx, buf); err != nil {
		return err
	}
	return err
}

func (r *HostToolProviderInfo) Decode(ctx gobtools.EncContext, buf *bytes.Reader) error {
	var err error

	if err = r.HostToolPath.Decode(ctx, buf); err != nil {
		return err
	}

	return err
}

var HostToolProviderInfoGobRegId int16

func (r HostToolProviderInfo) GetTypeId() int16 {
	return HostToolProviderInfoGobRegId
}

func (r DistInfo) Encode(ctx gobtools.EncContext, buf *bytes.Buffer) error {
	var err error

	if r.Dists == nil {
		if err = gobtools.EncodeInt(buf, -1); err != nil {
			return err
		}
	} else {
		if err = gobtools.EncodeInt(buf, len(r.Dists)); err != nil {
			return err
		}
		for val1 := 0; val1 < len(r.Dists); val1++ {
			if err = r.Dists[val1].Encode(ctx, buf); err != nil {
				return err
			}
		}
	}
	return err
}

func (r *DistInfo) Decode(ctx gobtools.EncContext, buf *bytes.Reader) error {
	var err error

	var val2 int
	err = gobtools.DecodeInt(buf, &val2)
	if err != nil {
		return err
	}
	if val2 != -1 {
		r.Dists = make([]dist, val2)
		for val3 := 0; val3 < int(val2); val3++ {
			if err = r.Dists[val3].Decode(ctx, buf); err != nil {
				return err
			}
		}
	}

	return err
}

var DistInfoGobRegId int16

func (r DistInfo) GetTypeId() int16 {
	return DistInfoGobRegId
}

func (r GeneratedSourceInfo) Encode(ctx gobtools.EncContext, buf *bytes.Buffer) error {
	var err error

	if r.GeneratedSourceFiles == nil {
		if err = gobtools.EncodeInt(buf, -1); err != nil {
			return err
		}
	} else {
		if err = gobtools.EncodeInt(buf, len(r.GeneratedSourceFiles)); err != nil {
			return err
		}
		for val1 := 0; val1 < len(r.GeneratedSourceFiles); val1++ {
			if err = gobtools.EncodeInterface(ctx, buf, r.GeneratedSourceFiles[val1]); err != nil {
				return err
			}
		}
	}

	if r.GeneratedHeaderDirs == nil {
		if err = gobtools.EncodeInt(buf, -1); err != nil {
			return err
		}
	} else {
		if err = gobtools.EncodeInt(buf, len(r.GeneratedHeaderDirs)); err != nil {
			return err
		}
		for val2 := 0; val2 < len(r.GeneratedHeaderDirs); val2++ {
			if err = gobtools.EncodeInterface(ctx, buf, r.GeneratedHeaderDirs[val2]); err != nil {
				return err
			}
		}
	}

	if r.GeneratedDeps == nil {
		if err = gobtools.EncodeInt(buf, -1); err != nil {
			return err
		}
	} else {
		if err = gobtools.EncodeInt(buf, len(r.GeneratedDeps)); err != nil {
			return err
		}
		for val3 := 0; val3 < len(r.GeneratedDeps); val3++ {
			if err = gobtools.EncodeInterface(ctx, buf, r.GeneratedDeps[val3]); err != nil {
				return err
			}
		}
	}
	return err
}

func (r *GeneratedSourceInfo) Decode(ctx gobtools.EncContext, buf *bytes.Reader) error {
	var err error

	var val3 int
	err = gobtools.DecodeInt(buf, &val3)
	if err != nil {
		return err
	}
	if val3 != -1 {
		r.GeneratedSourceFiles = make([]Path, val3)
		for val4 := 0; val4 < int(val3); val4++ {
			if val6, err := gobtools.DecodeInterface(ctx, buf); err != nil {
				return err
			} else if val6 == nil {
				r.GeneratedSourceFiles[val4] = nil
			} else {
				r.GeneratedSourceFiles[val4] = val6.(Path)
			}
		}
	}

	var val9 int
	err = gobtools.DecodeInt(buf, &val9)
	if err != nil {
		return err
	}
	if val9 != -1 {
		r.GeneratedHeaderDirs = make([]Path, val9)
		for val10 := 0; val10 < int(val9); val10++ {
			if val12, err := gobtools.DecodeInterface(ctx, buf); err != nil {
				return err
			} else if val12 == nil {
				r.GeneratedHeaderDirs[val10] = nil
			} else {
				r.GeneratedHeaderDirs[val10] = val12.(Path)
			}
		}
	}

	var val15 int
	err = gobtools.DecodeInt(buf, &val15)
	if err != nil {
		return err
	}
	if val15 != -1 {
		r.GeneratedDeps = make([]Path, val15)
		for val16 := 0; val16 < int(val15); val16++ {
			if val18, err := gobtools.DecodeInterface(ctx, buf); err != nil {
				return err
			} else if val18 == nil {
				r.GeneratedDeps[val16] = nil
			} else {
				r.GeneratedDeps[val16] = val18.(Path)
			}
		}
	}

	return err
}

var GeneratedSourceInfoGobRegId int16

func (r GeneratedSourceInfo) GetTypeId() int16 {
	return GeneratedSourceInfoGobRegId
}

func (r katiInstall) Encode(ctx gobtools.EncContext, buf *bytes.Buffer) error {
	var err error

	if err = gobtools.EncodeInterface(ctx, buf, r.from); err != nil {
		return err
	}

	if err = r.to.Encode(ctx, buf); err != nil {
		return err
	}

	if r.implicitDeps == nil {
		if err = gobtools.EncodeInt(buf, -1); err != nil {
			return err
		}
	} else {
		if err = gobtools.EncodeInt(buf, len(r.implicitDeps)); err != nil {
			return err
		}
		for val1 := 0; val1 < len(r.implicitDeps); val1++ {
			if err = gobtools.EncodeInterface(ctx, buf, r.implicitDeps[val1]); err != nil {
				return err
			}
		}
	}

	if r.orderOnlyDeps == nil {
		if err = gobtools.EncodeInt(buf, -1); err != nil {
			return err
		}
	} else {
		if err = gobtools.EncodeInt(buf, len(r.orderOnlyDeps)); err != nil {
			return err
		}
		for val2 := 0; val2 < len(r.orderOnlyDeps); val2++ {
			if err = gobtools.EncodeInterface(ctx, buf, r.orderOnlyDeps[val2]); err != nil {
				return err
			}
		}
	}

	if err = gobtools.EncodeBool(buf, r.executable); err != nil {
		return err
	}

	val3 := r.extraFiles == nil
	if err = gobtools.EncodeBool(buf, val3); err != nil {
		return err
	}
	if !val3 {
		if err = (*r.extraFiles).Encode(ctx, buf); err != nil {
			return err
		}
	}

	if err = gobtools.EncodeString(buf, r.absFrom); err != nil {
		return err
	}
	return err
}

func (r *katiInstall) Decode(ctx gobtools.EncContext, buf *bytes.Reader) error {
	var err error

	if val2, err := gobtools.DecodeInterface(ctx, buf); err != nil {
		return err
	} else if val2 == nil {
		r.from = nil
	} else {
		r.from = val2.(Path)
	}

	if err = r.to.Decode(ctx, buf); err != nil {
		return err
	}

	var val6 int
	err = gobtools.DecodeInt(buf, &val6)
	if err != nil {
		return err
	}
	if val6 != -1 {
		r.implicitDeps = make([]Path, val6)
		for val7 := 0; val7 < int(val6); val7++ {
			if val9, err := gobtools.DecodeInterface(ctx, buf); err != nil {
				return err
			} else if val9 == nil {
				r.implicitDeps[val7] = nil
			} else {
				r.implicitDeps[val7] = val9.(Path)
			}
		}
	}

	var val12 int
	err = gobtools.DecodeInt(buf, &val12)
	if err != nil {
		return err
	}
	if val12 != -1 {
		r.orderOnlyDeps = make([]Path, val12)
		for val13 := 0; val13 < int(val12); val13++ {
			if val15, err := gobtools.DecodeInterface(ctx, buf); err != nil {
				return err
			} else if val15 == nil {
				r.orderOnlyDeps[val13] = nil
			} else {
				r.orderOnlyDeps[val13] = val15.(Path)
			}
		}
	}

	err = gobtools.DecodeBool(buf, &r.executable)
	if err != nil {
		return err
	}

	var val18 bool
	if err = gobtools.DecodeBool(buf, &val18); err != nil {
		return err
	}
	if !val18 {
		var val17 extraFilesZip
		if err = val17.Decode(ctx, buf); err != nil {
			return err
		}
		r.extraFiles = &val17
	}

	err = gobtools.DecodeString(buf, &r.absFrom)
	if err != nil {
		return err
	}

	return err
}

var katiInstallGobRegId int16

func (r katiInstall) GetTypeId() int16 {
	return katiInstallGobRegId
}

func (r extraFilesZip) Encode(ctx gobtools.EncContext, buf *bytes.Buffer) error {
	var err error

	if err = gobtools.EncodeInterface(ctx, buf, r.zip); err != nil {
		return err
	}

	if err = r.dir.Encode(ctx, buf); err != nil {
		return err
	}
	return err
}

func (r *extraFilesZip) Decode(ctx gobtools.EncContext, buf *bytes.Reader) error {
	var err error

	if val2, err := gobtools.DecodeInterface(ctx, buf); err != nil {
		return err
	} else if val2 == nil {
		r.zip = nil
	} else {
		r.zip = val2.(Path)
	}

	if err = r.dir.Decode(ctx, buf); err != nil {
		return err
	}

	return err
}

var extraFilesZipGobRegId int16

func (r extraFilesZip) GetTypeId() int16 {
	return extraFilesZipGobRegId
}

func (r OutputFilesInfo) Encode(ctx gobtools.EncContext, buf *bytes.Buffer) error {
	var err error

	if r.DefaultOutputFiles == nil {
		if err = gobtools.EncodeInt(buf, -1); err != nil {
			return err
		}
	} else {
		if err = gobtools.EncodeInt(buf, len(r.DefaultOutputFiles)); err != nil {
			return err
		}
		for val1 := 0; val1 < len(r.DefaultOutputFiles); val1++ {
			if err = gobtools.EncodeInterface(ctx, buf, r.DefaultOutputFiles[val1]); err != nil {
				return err
			}
		}
	}

	if r.TaggedOutputFiles == nil {
		if err = gobtools.EncodeInt(buf, -1); err != nil {
			return err
		}
	} else {
		if err = gobtools.EncodeInt(buf, len(r.TaggedOutputFiles)); err != nil {
			return err
		}
		for val2, val3 := range r.TaggedOutputFiles {
			if err = gobtools.EncodeString(buf, val2); err != nil {
				return err
			}
			if val3 == nil {
				if err = gobtools.EncodeInt(buf, -1); err != nil {
					return err
				}
			} else {
				if err = gobtools.EncodeInt(buf, len(val3)); err != nil {
					return err
				}
				for val4 := 0; val4 < len(val3); val4++ {
					if err = gobtools.EncodeInterface(ctx, buf, val3[val4]); err != nil {
						return err
					}
				}
			}
		}
	}
	return err
}

func (r *OutputFilesInfo) Decode(ctx gobtools.EncContext, buf *bytes.Reader) error {
	var err error

	var val3 int
	err = gobtools.DecodeInt(buf, &val3)
	if err != nil {
		return err
	}
	if val3 != -1 {
		r.DefaultOutputFiles = make([]Path, val3)
		for val4 := 0; val4 < int(val3); val4++ {
			if val6, err := gobtools.DecodeInterface(ctx, buf); err != nil {
				return err
			} else if val6 == nil {
				r.DefaultOutputFiles[val4] = nil
			} else {
				r.DefaultOutputFiles[val4] = val6.(Path)
			}
		}
	}

	var val7 int
	err = gobtools.DecodeInt(buf, &val7)
	if err != nil {
		return err
	}
	if val7 != -1 {
		r.TaggedOutputFiles = make(map[string]Paths, val7)
		for val8 := 0; val8 < int(val7); val8++ {
			var val9 string
			var val10 Paths
			err = gobtools.DecodeString(buf, &val9)
			if err != nil {
				return err
			}
			var val14 int
			err = gobtools.DecodeInt(buf, &val14)
			if err != nil {
				return err
			}
			if val14 != -1 {
				val10 = make([]Path, val14)
				for val15 := 0; val15 < int(val14); val15++ {
					if val17, err := gobtools.DecodeInterface(ctx, buf); err != nil {
						return err
					} else if val17 == nil {
						val10[val15] = nil
					} else {
						val10[val15] = val17.(Path)
					}
				}
			}
			r.TaggedOutputFiles[val9] = val10
		}
	}

	return err
}

var OutputFilesInfoGobRegId int16

func (r OutputFilesInfo) GetTypeId() int16 {
	return OutputFilesInfoGobRegId
}

func (r IdeInfo) Encode(ctx gobtools.EncContext, buf *bytes.Buffer) error {
	var err error

	if err = gobtools.EncodeString(buf, r.BaseModuleName); err != nil {
		return err
	}

	if r.Deps == nil {
		if err = gobtools.EncodeInt(buf, -1); err != nil {
			return err
		}
	} else {
		if err = gobtools.EncodeInt(buf, len(r.Deps)); err != nil {
			return err
		}
		for val1 := 0; val1 < len(r.Deps); val1++ {
			if err = gobtools.EncodeString(buf, r.Deps[val1]); err != nil {
				return err
			}
		}
	}

	if r.Srcs == nil {
		if err = gobtools.EncodeInt(buf, -1); err != nil {
			return err
		}
	} else {
		if err = gobtools.EncodeInt(buf, len(r.Srcs)); err != nil {
			return err
		}
		for val2 := 0; val2 < len(r.Srcs); val2++ {
			if err = gobtools.EncodeString(buf, r.Srcs[val2]); err != nil {
				return err
			}
		}
	}

	if r.Aidl_include_dirs == nil {
		if err = gobtools.EncodeInt(buf, -1); err != nil {
			return err
		}
	} else {
		if err = gobtools.EncodeInt(buf, len(r.Aidl_include_dirs)); err != nil {
			return err
		}
		for val3 := 0; val3 < len(r.Aidl_include_dirs); val3++ {
			if err = gobtools.EncodeString(buf, r.Aidl_include_dirs[val3]); err != nil {
				return err
			}
		}
	}

	if r.Jarjar_rules == nil {
		if err = gobtools.EncodeInt(buf, -1); err != nil {
			return err
		}
	} else {
		if err = gobtools.EncodeInt(buf, len(r.Jarjar_rules)); err != nil {
			return err
		}
		for val4 := 0; val4 < len(r.Jarjar_rules); val4++ {
			if err = gobtools.EncodeString(buf, r.Jarjar_rules[val4]); err != nil {
				return err
			}
		}
	}

	if r.Jars == nil {
		if err = gobtools.EncodeInt(buf, -1); err != nil {
			return err
		}
	} else {
		if err = gobtools.EncodeInt(buf, len(r.Jars)); err != nil {
			return err
		}
		for val5 := 0; val5 < len(r.Jars); val5++ {
			if err = gobtools.EncodeString(buf, r.Jars[val5]); err != nil {
				return err
			}
		}
	}

	if r.Classes == nil {
		if err = gobtools.EncodeInt(buf, -1); err != nil {
			return err
		}
	} else {
		if err = gobtools.EncodeInt(buf, len(r.Classes)); err != nil {
			return err
		}
		for val6 := 0; val6 < len(r.Classes); val6++ {
			if err = gobtools.EncodeString(buf, r.Classes[val6]); err != nil {
				return err
			}
		}
	}

	if r.Installed_paths == nil {
		if err = gobtools.EncodeInt(buf, -1); err != nil {
			return err
		}
	} else {
		if err = gobtools.EncodeInt(buf, len(r.Installed_paths)); err != nil {
			return err
		}
		for val7 := 0; val7 < len(r.Installed_paths); val7++ {
			if err = gobtools.EncodeString(buf, r.Installed_paths[val7]); err != nil {
				return err
			}
		}
	}

	if r.SrcJars == nil {
		if err = gobtools.EncodeInt(buf, -1); err != nil {
			return err
		}
	} else {
		if err = gobtools.EncodeInt(buf, len(r.SrcJars)); err != nil {
			return err
		}
		for val8 := 0; val8 < len(r.SrcJars); val8++ {
			if err = gobtools.EncodeString(buf, r.SrcJars[val8]); err != nil {
				return err
			}
		}
	}

	if r.Paths == nil {
		if err = gobtools.EncodeInt(buf, -1); err != nil {
			return err
		}
	} else {
		if err = gobtools.EncodeInt(buf, len(r.Paths)); err != nil {
			return err
		}
		for val9 := 0; val9 < len(r.Paths); val9++ {
			if err = gobtools.EncodeString(buf, r.Paths[val9]); err != nil {
				return err
			}
		}
	}

	if r.Static_libs == nil {
		if err = gobtools.EncodeInt(buf, -1); err != nil {
			return err
		}
	} else {
		if err = gobtools.EncodeInt(buf, len(r.Static_libs)); err != nil {
			return err
		}
		for val10 := 0; val10 < len(r.Static_libs); val10++ {
			if err = gobtools.EncodeString(buf, r.Static_libs[val10]); err != nil {
				return err
			}
		}
	}

	if r.Libs == nil {
		if err = gobtools.EncodeInt(buf, -1); err != nil {
			return err
		}
	} else {
		if err = gobtools.EncodeInt(buf, len(r.Libs)); err != nil {
			return err
		}
		for val11 := 0; val11 < len(r.Libs); val11++ {
			if err = gobtools.EncodeString(buf, r.Libs[val11]); err != nil {
				return err
			}
		}
	}

	if r.Asset_dirs == nil {
		if err = gobtools.EncodeInt(buf, -1); err != nil {
			return err
		}
	} else {
		if err = gobtools.EncodeInt(buf, len(r.Asset_dirs)); err != nil {
			return err
		}
		for val12 := 0; val12 < len(r.Asset_dirs); val12++ {
			if err = gobtools.EncodeString(buf, r.Asset_dirs[val12]); err != nil {
				return err
			}
		}
	}

	if r.Resource_dirs == nil {
		if err = gobtools.EncodeInt(buf, -1); err != nil {
			return err
		}
	} else {
		if err = gobtools.EncodeInt(buf, len(r.Resource_dirs)); err != nil {
			return err
		}
		for val13 := 0; val13 < len(r.Resource_dirs); val13++ {
			if err = gobtools.EncodeString(buf, r.Resource_dirs[val13]); err != nil {
				return err
			}
		}
	}
	return err
}

func (r *IdeInfo) Decode(ctx gobtools.EncContext, buf *bytes.Reader) error {
	var err error

	err = gobtools.DecodeString(buf, &r.BaseModuleName)
	if err != nil {
		return err
	}

	var val3 int
	err = gobtools.DecodeInt(buf, &val3)
	if err != nil {
		return err
	}
	if val3 != -1 {
		r.Deps = make([]string, val3)
		for val4 := 0; val4 < int(val3); val4++ {
			err = gobtools.DecodeString(buf, &r.Deps[val4])
			if err != nil {
				return err
			}
		}
	}

	var val7 int
	err = gobtools.DecodeInt(buf, &val7)
	if err != nil {
		return err
	}
	if val7 != -1 {
		r.Srcs = make([]string, val7)
		for val8 := 0; val8 < int(val7); val8++ {
			err = gobtools.DecodeString(buf, &r.Srcs[val8])
			if err != nil {
				return err
			}
		}
	}

	var val11 int
	err = gobtools.DecodeInt(buf, &val11)
	if err != nil {
		return err
	}
	if val11 != -1 {
		r.Aidl_include_dirs = make([]string, val11)
		for val12 := 0; val12 < int(val11); val12++ {
			err = gobtools.DecodeString(buf, &r.Aidl_include_dirs[val12])
			if err != nil {
				return err
			}
		}
	}

	var val15 int
	err = gobtools.DecodeInt(buf, &val15)
	if err != nil {
		return err
	}
	if val15 != -1 {
		r.Jarjar_rules = make([]string, val15)
		for val16 := 0; val16 < int(val15); val16++ {
			err = gobtools.DecodeString(buf, &r.Jarjar_rules[val16])
			if err != nil {
				return err
			}
		}
	}

	var val19 int
	err = gobtools.DecodeInt(buf, &val19)
	if err != nil {
		return err
	}
	if val19 != -1 {
		r.Jars = make([]string, val19)
		for val20 := 0; val20 < int(val19); val20++ {
			err = gobtools.DecodeString(buf, &r.Jars[val20])
			if err != nil {
				return err
			}
		}
	}

	var val23 int
	err = gobtools.DecodeInt(buf, &val23)
	if err != nil {
		return err
	}
	if val23 != -1 {
		r.Classes = make([]string, val23)
		for val24 := 0; val24 < int(val23); val24++ {
			err = gobtools.DecodeString(buf, &r.Classes[val24])
			if err != nil {
				return err
			}
		}
	}

	var val27 int
	err = gobtools.DecodeInt(buf, &val27)
	if err != nil {
		return err
	}
	if val27 != -1 {
		r.Installed_paths = make([]string, val27)
		for val28 := 0; val28 < int(val27); val28++ {
			err = gobtools.DecodeString(buf, &r.Installed_paths[val28])
			if err != nil {
				return err
			}
		}
	}

	var val31 int
	err = gobtools.DecodeInt(buf, &val31)
	if err != nil {
		return err
	}
	if val31 != -1 {
		r.SrcJars = make([]string, val31)
		for val32 := 0; val32 < int(val31); val32++ {
			err = gobtools.DecodeString(buf, &r.SrcJars[val32])
			if err != nil {
				return err
			}
		}
	}

	var val35 int
	err = gobtools.DecodeInt(buf, &val35)
	if err != nil {
		return err
	}
	if val35 != -1 {
		r.Paths = make([]string, val35)
		for val36 := 0; val36 < int(val35); val36++ {
			err = gobtools.DecodeString(buf, &r.Paths[val36])
			if err != nil {
				return err
			}
		}
	}

	var val39 int
	err = gobtools.DecodeInt(buf, &val39)
	if err != nil {
		return err
	}
	if val39 != -1 {
		r.Static_libs = make([]string, val39)
		for val40 := 0; val40 < int(val39); val40++ {
			err = gobtools.DecodeString(buf, &r.Static_libs[val40])
			if err != nil {
				return err
			}
		}
	}

	var val43 int
	err = gobtools.DecodeInt(buf, &val43)
	if err != nil {
		return err
	}
	if val43 != -1 {
		r.Libs = make([]string, val43)
		for val44 := 0; val44 < int(val43); val44++ {
			err = gobtools.DecodeString(buf, &r.Libs[val44])
			if err != nil {
				return err
			}
		}
	}

	var val47 int
	err = gobtools.DecodeInt(buf, &val47)
	if err != nil {
		return err
	}
	if val47 != -1 {
		r.Asset_dirs = make([]string, val47)
		for val48 := 0; val48 < int(val47); val48++ {
			err = gobtools.DecodeString(buf, &r.Asset_dirs[val48])
			if err != nil {
				return err
			}
		}
	}

	var val51 int
	err = gobtools.DecodeInt(buf, &val51)
	if err != nil {
		return err
	}
	if val51 != -1 {
		r.Resource_dirs = make([]string, val51)
		for val52 := 0; val52 < int(val51); val52++ {
			err = gobtools.DecodeString(buf, &r.Resource_dirs[val52])
			if err != nil {
				return err
			}
		}
	}

	return err
}

var IdeInfoGobRegId int16

func (r IdeInfo) GetTypeId() int16 {
	return IdeInfoGobRegId
}
