// Code generated by go run gob_gen.go; DO NOT EDIT.

package android

import (
	"bytes"
	"github.com/google/blueprint/gobtools"
)

func init() {
	PhonyInfoGobRegId = gobtools.RegisterType(func() gobtools.CustomDec { return new(PhonyInfo) })
}

func (r PhonyInfo) Encode(ctx gobtools.EncContext, buf *bytes.Buffer) error {
	var err error

	if r.Phonies == nil {
		if err = gobtools.EncodeInt(buf, -1); err != nil {
			return err
		}
	} else {
		if err = gobtools.EncodeInt(buf, len(r.Phonies)); err != nil {
			return err
		}
		for val1, val2 := range r.Phonies {
			if err = gobtools.EncodeString(buf, val1); err != nil {
				return err
			}
			if val2 == nil {
				if err = gobtools.EncodeInt(buf, -1); err != nil {
					return err
				}
			} else {
				if err = gobtools.EncodeInt(buf, len(val2)); err != nil {
					return err
				}
				for val3 := 0; val3 < len(val2); val3++ {
					if err = gobtools.EncodeInterface(ctx, buf, val2[val3]); err != nil {
						return err
					}
				}
			}
		}
	}
	return err
}

func (r *PhonyInfo) Decode(ctx gobtools.EncContext, buf *bytes.Reader) error {
	var err error

	var val2 int
	err = gobtools.DecodeInt(buf, &val2)
	if err != nil {
		return err
	}
	if val2 != -1 {
		r.Phonies = make(map[string]Paths, val2)
		for val3 := 0; val3 < int(val2); val3++ {
			var val4 string
			var val5 Paths
			err = gobtools.DecodeString(buf, &val4)
			if err != nil {
				return err
			}
			var val9 int
			err = gobtools.DecodeInt(buf, &val9)
			if err != nil {
				return err
			}
			if val9 != -1 {
				val5 = make([]Path, val9)
				for val10 := 0; val10 < int(val9); val10++ {
					if val12, err := gobtools.DecodeInterface(ctx, buf); err != nil {
						return err
					} else if val12 == nil {
						val5[val10] = nil
					} else {
						val5[val10] = val12.(Path)
					}
				}
			}
			r.Phonies[val4] = val5
		}
	}

	return err
}

var PhonyInfoGobRegId int16

func (r PhonyInfo) GetTypeId() int16 {
	return PhonyInfoGobRegId
}
