// Code generated by go run gob_gen.go; DO NOT EDIT.

package android

import (
	"bytes"
	"github.com/google/blueprint/gobtools"
)

func init() {
	SdkSpecGobRegId = gobtools.RegisterType(func() gobtools.CustomDec { return new(SdkSpec) })
}

func (r SdkSpec) Encode(ctx gobtools.EncContext, buf *bytes.Buffer) error {
	var err error

	if err = gobtools.EncodeSimple(buf, int64(int(r.Kind))); err != nil {
		return err
	}

	if err = r.ApiLevel.Encode(ctx, buf); err != nil {
		return err
	}

	if err = gobtools.EncodeString(buf, r.Raw); err != nil {
		return err
	}
	return err
}

func (r *SdkSpec) Decode(ctx gobtools.EncContext, buf *bytes.Reader) error {
	var err error

	var val2 int
	var val3 int64
	err = gobtools.DecodeSimple[int64](buf, &val3)
	if err != nil {
		return err
	}
	val2 = int(val3)
	r.Kind = SdkKind(val2)

	if err = r.ApiLevel.Decode(ctx, buf); err != nil {
		return err
	}

	err = gobtools.DecodeString(buf, &r.Raw)
	if err != nil {
		return err
	}

	return err
}

var SdkSpecGobRegId int16

func (r SdkSpec) GetTypeId() int16 {
	return SdkSpecGobRegId
}
