// Code generated by go run gob_gen.go; DO NOT EDIT.

package android

import (
	"bytes"
	"github.com/google/blueprint/gobtools"
)

func init() {
	BpPrintableBaseGobRegId = gobtools.RegisterType(func() gobtools.CustomDec { return new(BpPrintableBase) })
	SdkMemberTraitBaseGobRegId = gobtools.RegisterType(func() gobtools.CustomDec { return new(SdkMemberTraitBase) })
	SdkMemberTypeBaseGobRegId = gobtools.RegisterType(func() gobtools.CustomDec { return new(SdkMemberTypeBase) })
	ExportedComponentsInfoGobRegId = gobtools.RegisterType(func() gobtools.CustomDec { return new(ExportedComponentsInfo) })
	AdditionalSdkInfoGobRegId = gobtools.RegisterType(func() gobtools.CustomDec { return new(AdditionalSdkInfo) })
	AdditionalSdkInfoPropertiesGobRegId = gobtools.RegisterType(func() gobtools.CustomDec { return new(AdditionalSdkInfoProperties) })
}

func (r BpPrintableBase) Encode(ctx gobtools.EncContext, buf *bytes.Buffer) error {
	var err error
	return err
}

func (r *BpPrintableBase) Decode(ctx gobtools.EncContext, buf *bytes.Reader) error {
	var err error

	return err
}

var BpPrintableBaseGobRegId int16

func (r BpPrintableBase) GetTypeId() int16 {
	return BpPrintableBaseGobRegId
}

func (r SdkMemberTraitBase) Encode(ctx gobtools.EncContext, buf *bytes.Buffer) error {
	var err error

	if err = gobtools.EncodeString(buf, r.PropertyName); err != nil {
		return err
	}
	return err
}

func (r *SdkMemberTraitBase) Decode(ctx gobtools.EncContext, buf *bytes.Reader) error {
	var err error

	err = gobtools.DecodeString(buf, &r.PropertyName)
	if err != nil {
		return err
	}

	return err
}

var SdkMemberTraitBaseGobRegId int16

func (r SdkMemberTraitBase) GetTypeId() int16 {
	return SdkMemberTraitBaseGobRegId
}

func (r SdkMemberTypeBase) Encode(ctx gobtools.EncContext, buf *bytes.Buffer) error {
	var err error

	if err = gobtools.EncodeString(buf, r.PropertyName); err != nil {
		return err
	}

	if r.OverridesPropertyNames == nil {
		if err = gobtools.EncodeInt(buf, -1); err != nil {
			return err
		}
	} else {
		if err = gobtools.EncodeInt(buf, len(r.OverridesPropertyNames)); err != nil {
			return err
		}
		for k, v := range r.OverridesPropertyNames {
			if err = gobtools.EncodeString(buf, k); err != nil {
				return err
			}
			if err = gobtools.EncodeBool(buf, v); err != nil {
				return err
			}
		}
	}

	if r.SupportedLinkageNames == nil {
		if err = gobtools.EncodeInt(buf, -1); err != nil {
			return err
		}
	} else {
		if err = gobtools.EncodeInt(buf, len(r.SupportedLinkageNames)); err != nil {
			return err
		}
		for val1 := 0; val1 < len(r.SupportedLinkageNames); val1++ {
			if err = gobtools.EncodeString(buf, r.SupportedLinkageNames[val1]); err != nil {
				return err
			}
		}
	}

	if err = gobtools.EncodeBool(buf, r.StripDisabled); err != nil {
		return err
	}

	if err = gobtools.EncodeBool(buf, r.BpPropertyNotRequired); err != nil {
		return err
	}

	if err = gobtools.EncodeString(buf, r.SupportedBuildReleaseSpecification); err != nil {
		return err
	}

	if err = gobtools.EncodeBool(buf, r.SupportsSdk); err != nil {
		return err
	}

	if err = gobtools.EncodeBool(buf, r.HostOsDependent); err != nil {
		return err
	}

	if err = gobtools.EncodeBool(buf, r.UseSourceModuleTypeInSnapshot); err != nil {
		return err
	}

	val2 := r.PrebuiltsRequired == nil
	if err = gobtools.EncodeBool(buf, val2); err != nil {
		return err
	}
	if !val2 {
		if err = gobtools.EncodeBool(buf, (*r.PrebuiltsRequired)); err != nil {
			return err
		}
	}

	if r.Traits == nil {
		if err = gobtools.EncodeInt(buf, -1); err != nil {
			return err
		}
	} else {
		if err = gobtools.EncodeInt(buf, len(r.Traits)); err != nil {
			return err
		}
		for val3 := 0; val3 < len(r.Traits); val3++ {
			if err = gobtools.EncodeInterface(ctx, buf, r.Traits[val3]); err != nil {
				return err
			}
		}
	}
	return err
}

func (r *SdkMemberTypeBase) Decode(ctx gobtools.EncContext, buf *bytes.Reader) error {
	var err error

	err = gobtools.DecodeString(buf, &r.PropertyName)
	if err != nil {
		return err
	}

	var val2 int
	err = gobtools.DecodeInt(buf, &val2)
	if err != nil {
		return err
	}
	if val2 != -1 {
		r.OverridesPropertyNames = make(map[string]bool, val2)
		for val3 := 0; val3 < int(val2); val3++ {
			var k string
			var v bool
			err = gobtools.DecodeString(buf, &k)
			if err != nil {
				return err
			}
			err = gobtools.DecodeBool(buf, &v)
			if err != nil {
				return err
			}
			r.OverridesPropertyNames[k] = v
		}
	}

	var val7 int
	err = gobtools.DecodeInt(buf, &val7)
	if err != nil {
		return err
	}
	if val7 != -1 {
		r.SupportedLinkageNames = make([]string, val7)
		for val8 := 0; val8 < int(val7); val8++ {
			err = gobtools.DecodeString(buf, &r.SupportedLinkageNames[val8])
			if err != nil {
				return err
			}
		}
	}

	err = gobtools.DecodeBool(buf, &r.StripDisabled)
	if err != nil {
		return err
	}

	err = gobtools.DecodeBool(buf, &r.BpPropertyNotRequired)
	if err != nil {
		return err
	}

	err = gobtools.DecodeString(buf, &r.SupportedBuildReleaseSpecification)
	if err != nil {
		return err
	}

	err = gobtools.DecodeBool(buf, &r.SupportsSdk)
	if err != nil {
		return err
	}

	err = gobtools.DecodeBool(buf, &r.HostOsDependent)
	if err != nil {
		return err
	}

	err = gobtools.DecodeBool(buf, &r.UseSourceModuleTypeInSnapshot)
	if err != nil {
		return err
	}

	var val17 bool
	if err = gobtools.DecodeBool(buf, &val17); err != nil {
		return err
	}
	if !val17 {
		var val16 bool
		err = gobtools.DecodeBool(buf, &val16)
		if err != nil {
			return err
		}
		r.PrebuiltsRequired = &val16
	}

	var val20 int
	err = gobtools.DecodeInt(buf, &val20)
	if err != nil {
		return err
	}
	if val20 != -1 {
		r.Traits = make([]SdkMemberTrait, val20)
		for val21 := 0; val21 < int(val20); val21++ {
			if val23, err := gobtools.DecodeInterface(ctx, buf); err != nil {
				return err
			} else if val23 == nil {
				r.Traits[val21] = nil
			} else {
				r.Traits[val21] = val23.(SdkMemberTrait)
			}
		}
	}

	return err
}

var SdkMemberTypeBaseGobRegId int16

func (r SdkMemberTypeBase) GetTypeId() int16 {
	return SdkMemberTypeBaseGobRegId
}

func (r ExportedComponentsInfo) Encode(ctx gobtools.EncContext, buf *bytes.Buffer) error {
	var err error

	if r.Components == nil {
		if err = gobtools.EncodeInt(buf, -1); err != nil {
			return err
		}
	} else {
		if err = gobtools.EncodeInt(buf, len(r.Components)); err != nil {
			return err
		}
		for val1 := 0; val1 < len(r.Components); val1++ {
			if err = gobtools.EncodeString(buf, r.Components[val1]); err != nil {
				return err
			}
		}
	}
	return err
}

func (r *ExportedComponentsInfo) Decode(ctx gobtools.EncContext, buf *bytes.Reader) error {
	var err error

	var val2 int
	err = gobtools.DecodeInt(buf, &val2)
	if err != nil {
		return err
	}
	if val2 != -1 {
		r.Components = make([]string, val2)
		for val3 := 0; val3 < int(val2); val3++ {
			err = gobtools.DecodeString(buf, &r.Components[val3])
			if err != nil {
				return err
			}
		}
	}

	return err
}

var ExportedComponentsInfoGobRegId int16

func (r ExportedComponentsInfo) GetTypeId() int16 {
	return ExportedComponentsInfoGobRegId
}

func (r AdditionalSdkInfo) Encode(ctx gobtools.EncContext, buf *bytes.Buffer) error {
	var err error

	if err = r.Properties.Encode(ctx, buf); err != nil {
		return err
	}
	return err
}

func (r *AdditionalSdkInfo) Decode(ctx gobtools.EncContext, buf *bytes.Reader) error {
	var err error

	if err = r.Properties.Decode(ctx, buf); err != nil {
		return err
	}

	return err
}

var AdditionalSdkInfoGobRegId int16

func (r AdditionalSdkInfo) GetTypeId() int16 {
	return AdditionalSdkInfoGobRegId
}

func (r AdditionalSdkInfoProperties) Encode(ctx gobtools.EncContext, buf *bytes.Buffer) error {
	var err error

	if r.Nested == nil {
		if err = gobtools.EncodeInt(buf, -1); err != nil {
			return err
		}
	} else {
		if err = gobtools.EncodeInt(buf, len(r.Nested)); err != nil {
			return err
		}
		for k, v := range r.Nested {
			if err = gobtools.EncodeString(buf, k); err != nil {
				return err
			}
			if err = v.Encode(ctx, buf); err != nil {
				return err
			}
		}
	}

	if r.Properties == nil {
		if err = gobtools.EncodeInt(buf, -1); err != nil {
			return err
		}
	} else {
		if err = gobtools.EncodeInt(buf, len(r.Properties)); err != nil {
			return err
		}
		for k, v := range r.Properties {
			if err = gobtools.EncodeString(buf, k); err != nil {
				return err
			}
			if err = gobtools.EncodeString(buf, v); err != nil {
				return err
			}
		}
	}
	return err
}

func (r *AdditionalSdkInfoProperties) Decode(ctx gobtools.EncContext, buf *bytes.Reader) error {
	var err error

	var val1 int
	err = gobtools.DecodeInt(buf, &val1)
	if err != nil {
		return err
	}
	if val1 != -1 {
		r.Nested = make(map[string]AdditionalSdkInfoProperties, val1)
		for val2 := 0; val2 < int(val1); val2++ {
			var k string
			var v AdditionalSdkInfoProperties
			err = gobtools.DecodeString(buf, &k)
			if err != nil {
				return err
			}
			if err = v.Decode(ctx, buf); err != nil {
				return err
			}
			r.Nested[k] = v
		}
	}

	var val5 int
	err = gobtools.DecodeInt(buf, &val5)
	if err != nil {
		return err
	}
	if val5 != -1 {
		r.Properties = make(map[string]string, val5)
		for val6 := 0; val6 < int(val5); val6++ {
			var k string
			var v string
			err = gobtools.DecodeString(buf, &k)
			if err != nil {
				return err
			}
			err = gobtools.DecodeString(buf, &v)
			if err != nil {
				return err
			}
			r.Properties[k] = v
		}
	}

	return err
}

var AdditionalSdkInfoPropertiesGobRegId int16

func (r AdditionalSdkInfoProperties) GetTypeId() int16 {
	return AdditionalSdkInfoPropertiesGobRegId
}
