// Code generated by go run gob_gen.go; DO NOT EDIT.

package android

import (
	"bytes"
	"github.com/google/blueprint/gobtools"
)

func init() {
	BpPrintableBaseGobRegId = gobtools.RegisterType(func() gobtools.CustomDec { return new(BpPrintableBase) })
	SdkMemberTraitBaseGobRegId = gobtools.RegisterType(func() gobtools.CustomDec { return new(SdkMemberTraitBase) })
	SdkMemberTypeBaseGobRegId = gobtools.RegisterType(func() gobtools.CustomDec { return new(SdkMemberTypeBase) })
	ExportedComponentsInfoGobRegId = gobtools.RegisterType(func() gobtools.CustomDec { return new(ExportedComponentsInfo) })
	AdditionalSdkInfoGobRegId = gobtools.RegisterType(func() gobtools.CustomDec { return new(AdditionalSdkInfo) })
	AdditionalSdkInfoPropertiesGobRegId = gobtools.RegisterType(func() gobtools.CustomDec { return new(AdditionalSdkInfoProperties) })
}

func (r BpPrintableBase) Encode(ctx gobtools.EncContext, buf *bytes.Buffer) error {
	var err error
	return err
}

func (r *BpPrintableBase) Decode(ctx gobtools.EncContext, buf *bytes.Reader) error {
	var err error

	return err
}

var BpPrintableBaseGobRegId int16

func (r BpPrintableBase) GetTypeId() int16 {
	return BpPrintableBaseGobRegId
}

func (r SdkMemberTraitBase) Encode(ctx gobtools.EncContext, buf *bytes.Buffer) error {
	var err error

	if err = gobtools.EncodeString(buf, r.PropertyName); err != nil {
		return err
	}
	return err
}

func (r *SdkMemberTraitBase) Decode(ctx gobtools.EncContext, buf *bytes.Reader) error {
	var err error

	err = gobtools.DecodeString(buf, &r.PropertyName)
	if err != nil {
		return err
	}

	return err
}

var SdkMemberTraitBaseGobRegId int16

func (r SdkMemberTraitBase) GetTypeId() int16 {
	return SdkMemberTraitBaseGobRegId
}

func (r SdkMemberTypeBase) Encode(ctx gobtools.EncContext, buf *bytes.Buffer) error {
	var err error

	if err = gobtools.EncodeString(buf, r.PropertyName); err != nil {
		return err
	}

	if r.OverridesPropertyNames == nil {
		if err = gobtools.EncodeInt(buf, -1); err != nil {
			return err
		}
	} else {
		if err = gobtools.EncodeInt(buf, len(r.OverridesPropertyNames)); err != nil {
			return err
		}
		for val1, val2 := range r.OverridesPropertyNames {
			if err = gobtools.EncodeString(buf, val1); err != nil {
				return err
			}
			if err = gobtools.EncodeBool(buf, val2); err != nil {
				return err
			}
		}
	}

	if r.SupportedLinkageNames == nil {
		if err = gobtools.EncodeInt(buf, -1); err != nil {
			return err
		}
	} else {
		if err = gobtools.EncodeInt(buf, len(r.SupportedLinkageNames)); err != nil {
			return err
		}
		for val3 := 0; val3 < len(r.SupportedLinkageNames); val3++ {
			if err = gobtools.EncodeString(buf, r.SupportedLinkageNames[val3]); err != nil {
				return err
			}
		}
	}

	if err = gobtools.EncodeBool(buf, r.StripDisabled); err != nil {
		return err
	}

	if err = gobtools.EncodeBool(buf, r.BpPropertyNotRequired); err != nil {
		return err
	}

	if err = gobtools.EncodeString(buf, r.SupportedBuildReleaseSpecification); err != nil {
		return err
	}

	if err = gobtools.EncodeBool(buf, r.SupportsSdk); err != nil {
		return err
	}

	if err = gobtools.EncodeBool(buf, r.HostOsDependent); err != nil {
		return err
	}

	if err = gobtools.EncodeBool(buf, r.UseSourceModuleTypeInSnapshot); err != nil {
		return err
	}

	val4 := r.PrebuiltsRequired == nil
	if err = gobtools.EncodeBool(buf, val4); err != nil {
		return err
	}
	if !val4 {
		if err = gobtools.EncodeBool(buf, (*r.PrebuiltsRequired)); err != nil {
			return err
		}
	}

	if r.Traits == nil {
		if err = gobtools.EncodeInt(buf, -1); err != nil {
			return err
		}
	} else {
		if err = gobtools.EncodeInt(buf, len(r.Traits)); err != nil {
			return err
		}
		for val5 := 0; val5 < len(r.Traits); val5++ {
			if err = gobtools.EncodeInterface(ctx, buf, r.Traits[val5]); err != nil {
				return err
			}
		}
	}
	return err
}

func (r *SdkMemberTypeBase) Decode(ctx gobtools.EncContext, buf *bytes.Reader) error {
	var err error

	err = gobtools.DecodeString(buf, &r.PropertyName)
	if err != nil {
		return err
	}

	var val2 int
	err = gobtools.DecodeInt(buf, &val2)
	if err != nil {
		return err
	}
	if val2 != -1 {
		r.OverridesPropertyNames = make(map[string]bool, val2)
		for val3 := 0; val3 < int(val2); val3++ {
			var val4 string
			var val5 bool
			err = gobtools.DecodeString(buf, &val4)
			if err != nil {
				return err
			}
			err = gobtools.DecodeBool(buf, &val5)
			if err != nil {
				return err
			}
			r.OverridesPropertyNames[val4] = val5
		}
	}

	var val9 int
	err = gobtools.DecodeInt(buf, &val9)
	if err != nil {
		return err
	}
	if val9 != -1 {
		r.SupportedLinkageNames = make([]string, val9)
		for val10 := 0; val10 < int(val9); val10++ {
			err = gobtools.DecodeString(buf, &r.SupportedLinkageNames[val10])
			if err != nil {
				return err
			}
		}
	}

	err = gobtools.DecodeBool(buf, &r.StripDisabled)
	if err != nil {
		return err
	}

	err = gobtools.DecodeBool(buf, &r.BpPropertyNotRequired)
	if err != nil {
		return err
	}

	err = gobtools.DecodeString(buf, &r.SupportedBuildReleaseSpecification)
	if err != nil {
		return err
	}

	err = gobtools.DecodeBool(buf, &r.SupportsSdk)
	if err != nil {
		return err
	}

	err = gobtools.DecodeBool(buf, &r.HostOsDependent)
	if err != nil {
		return err
	}

	err = gobtools.DecodeBool(buf, &r.UseSourceModuleTypeInSnapshot)
	if err != nil {
		return err
	}

	var val19 bool
	if err = gobtools.DecodeBool(buf, &val19); err != nil {
		return err
	}
	if !val19 {
		var val18 bool
		err = gobtools.DecodeBool(buf, &val18)
		if err != nil {
			return err
		}
		r.PrebuiltsRequired = &val18
	}

	var val22 int
	err = gobtools.DecodeInt(buf, &val22)
	if err != nil {
		return err
	}
	if val22 != -1 {
		r.Traits = make([]SdkMemberTrait, val22)
		for val23 := 0; val23 < int(val22); val23++ {
			if val25, err := gobtools.DecodeInterface(ctx, buf); err != nil {
				return err
			} else if val25 == nil {
				r.Traits[val23] = nil
			} else {
				r.Traits[val23] = val25.(SdkMemberTrait)
			}
		}
	}

	return err
}

var SdkMemberTypeBaseGobRegId int16

func (r SdkMemberTypeBase) GetTypeId() int16 {
	return SdkMemberTypeBaseGobRegId
}

func (r ExportedComponentsInfo) Encode(ctx gobtools.EncContext, buf *bytes.Buffer) error {
	var err error

	if r.Components == nil {
		if err = gobtools.EncodeInt(buf, -1); err != nil {
			return err
		}
	} else {
		if err = gobtools.EncodeInt(buf, len(r.Components)); err != nil {
			return err
		}
		for val1 := 0; val1 < len(r.Components); val1++ {
			if err = gobtools.EncodeString(buf, r.Components[val1]); err != nil {
				return err
			}
		}
	}
	return err
}

func (r *ExportedComponentsInfo) Decode(ctx gobtools.EncContext, buf *bytes.Reader) error {
	var err error

	var val2 int
	err = gobtools.DecodeInt(buf, &val2)
	if err != nil {
		return err
	}
	if val2 != -1 {
		r.Components = make([]string, val2)
		for val3 := 0; val3 < int(val2); val3++ {
			err = gobtools.DecodeString(buf, &r.Components[val3])
			if err != nil {
				return err
			}
		}
	}

	return err
}

var ExportedComponentsInfoGobRegId int16

func (r ExportedComponentsInfo) GetTypeId() int16 {
	return ExportedComponentsInfoGobRegId
}

func (r AdditionalSdkInfo) Encode(ctx gobtools.EncContext, buf *bytes.Buffer) error {
	var err error

	if err = r.Properties.Encode(ctx, buf); err != nil {
		return err
	}
	return err
}

func (r *AdditionalSdkInfo) Decode(ctx gobtools.EncContext, buf *bytes.Reader) error {
	var err error

	if err = r.Properties.Decode(ctx, buf); err != nil {
		return err
	}

	return err
}

var AdditionalSdkInfoGobRegId int16

func (r AdditionalSdkInfo) GetTypeId() int16 {
	return AdditionalSdkInfoGobRegId
}

func (r AdditionalSdkInfoProperties) Encode(ctx gobtools.EncContext, buf *bytes.Buffer) error {
	var err error

	if r.Nested == nil {
		if err = gobtools.EncodeInt(buf, -1); err != nil {
			return err
		}
	} else {
		if err = gobtools.EncodeInt(buf, len(r.Nested)); err != nil {
			return err
		}
		for val1, val2 := range r.Nested {
			if err = gobtools.EncodeString(buf, val1); err != nil {
				return err
			}
			if err = val2.Encode(ctx, buf); err != nil {
				return err
			}
		}
	}

	if r.Properties == nil {
		if err = gobtools.EncodeInt(buf, -1); err != nil {
			return err
		}
	} else {
		if err = gobtools.EncodeInt(buf, len(r.Properties)); err != nil {
			return err
		}
		for val3, val4 := range r.Properties {
			if err = gobtools.EncodeString(buf, val3); err != nil {
				return err
			}
			if err = gobtools.EncodeString(buf, val4); err != nil {
				return err
			}
		}
	}
	return err
}

func (r *AdditionalSdkInfoProperties) Decode(ctx gobtools.EncContext, buf *bytes.Reader) error {
	var err error

	var val1 int
	err = gobtools.DecodeInt(buf, &val1)
	if err != nil {
		return err
	}
	if val1 != -1 {
		r.Nested = make(map[string]AdditionalSdkInfoProperties, val1)
		for val2 := 0; val2 < int(val1); val2++ {
			var val3 string
			var val4 AdditionalSdkInfoProperties
			err = gobtools.DecodeString(buf, &val3)
			if err != nil {
				return err
			}
			if err = val4.Decode(ctx, buf); err != nil {
				return err
			}
			r.Nested[val3] = val4
		}
	}

	var val7 int
	err = gobtools.DecodeInt(buf, &val7)
	if err != nil {
		return err
	}
	if val7 != -1 {
		r.Properties = make(map[string]string, val7)
		for val8 := 0; val8 < int(val7); val8++ {
			var val9 string
			var val10 string
			err = gobtools.DecodeString(buf, &val9)
			if err != nil {
				return err
			}
			err = gobtools.DecodeString(buf, &val10)
			if err != nil {
				return err
			}
			r.Properties[val9] = val10
		}
	}

	return err
}

var AdditionalSdkInfoPropertiesGobRegId int16

func (r AdditionalSdkInfoProperties) GetTypeId() int16 {
	return AdditionalSdkInfoPropertiesGobRegId
}
