// Code generated by go run gob_gen.go; DO NOT EDIT.

package java

import (
	"android/soong/android"
	"bytes"
	"github.com/google/blueprint/gobtools"
	"github.com/google/blueprint/uniquelist"
)

func init() {
	resourcesNodeGobRegId = gobtools.RegisterType(func() gobtools.CustomDec { return new(resourcesNode) })
	AndroidLibraryInfoGobRegId = gobtools.RegisterType(func() gobtools.CustomDec { return new(AndroidLibraryInfo) })
	JniPackageInfoGobRegId = gobtools.RegisterType(func() gobtools.CustomDec { return new(JniPackageInfo) })
	AARInfoGobRegId = gobtools.RegisterType(func() gobtools.CustomDec { return new(AARInfo) })
}

func (r resourcesNode) Encode(ctx gobtools.EncContext, buf *bytes.Buffer) error {
	var err error

	if err = gobtools.EncodeInterface(ctx, buf, r.resPackage); err != nil {
		return err
	}

	if err = gobtools.EncodeInterface(ctx, buf, r.manifest); err != nil {
		return err
	}

	val1 := r.additionalManifests.ToSlice()
	if val1 == nil {
		if err = gobtools.EncodeSimple(buf, int32(-1)); err != nil {
			return err
		}
	} else {
		if err = gobtools.EncodeSimple(buf, int32(len(val1))); err != nil {
			return err
		}
		for val2 := 0; val2 < len(val1); val2++ {
			if err = gobtools.EncodeInterface(ctx, buf, val1[val2]); err != nil {
				return err
			}
		}
	}

	if err = gobtools.EncodeInterface(ctx, buf, r.rTxt); err != nil {
		return err
	}

	if err = gobtools.EncodeInterface(ctx, buf, r.rJar); err != nil {
		return err
	}

	if err = r.assets.Encode(ctx, buf); err != nil {
		return err
	}

	if err = gobtools.EncodeSimple(buf, r.usedResourceProcessor); err != nil {
		return err
	}
	return err
}

func (r *resourcesNode) Decode(ctx gobtools.EncContext, buf *bytes.Reader) error {
	var err error

	if val2, err := gobtools.DecodeInterface(ctx, buf); err != nil {
		return err
	} else if val2 == nil {
		r.resPackage = nil
	} else {
		r.resPackage = val2.(android.Path)
	}

	if val4, err := gobtools.DecodeInterface(ctx, buf); err != nil {
		return err
	} else if val4 == nil {
		r.manifest = nil
	} else {
		r.manifest = val4.(android.Path)
	}

	var val6 []android.Path
	var val7 int32
	err = gobtools.DecodeSimple[int32](buf, &val7)
	if err != nil {
		return err
	}
	if val7 != -1 {
		val6 = make([]android.Path, val7)
		for val8 := 0; val8 < int(val7); val8++ {
			if val10, err := gobtools.DecodeInterface(ctx, buf); err != nil {
				return err
			} else if val10 == nil {
				val6[val8] = nil
			} else {
				val6[val8] = val10.(android.Path)
			}
		}
	}
	r.additionalManifests = uniquelist.Make(val6)

	if val12, err := gobtools.DecodeInterface(ctx, buf); err != nil {
		return err
	} else if val12 == nil {
		r.rTxt = nil
	} else {
		r.rTxt = val12.(android.Path)
	}

	if val14, err := gobtools.DecodeInterface(ctx, buf); err != nil {
		return err
	} else if val14 == nil {
		r.rJar = nil
	} else {
		r.rJar = val14.(android.Path)
	}

	if err = r.assets.Decode(ctx, buf); err != nil {
		return err
	}

	err = gobtools.DecodeSimple[bool](buf, &r.usedResourceProcessor)
	if err != nil {
		return err
	}

	return err
}

var resourcesNodeGobRegId int16

func (r resourcesNode) GetTypeId() int16 {
	return resourcesNodeGobRegId
}

func (r AndroidLibraryInfo) Encode(ctx gobtools.EncContext, buf *bytes.Buffer) error {
	var err error
	return err
}

func (r *AndroidLibraryInfo) Decode(ctx gobtools.EncContext, buf *bytes.Reader) error {
	var err error

	return err
}

var AndroidLibraryInfoGobRegId int16

func (r AndroidLibraryInfo) GetTypeId() int16 {
	return AndroidLibraryInfoGobRegId
}

func (r JniPackageInfo) Encode(ctx gobtools.EncContext, buf *bytes.Buffer) error {
	var err error

	if r.JniPackages == nil {
		if err = gobtools.EncodeSimple(buf, int32(-1)); err != nil {
			return err
		}
	} else {
		if err = gobtools.EncodeSimple(buf, int32(len(r.JniPackages))); err != nil {
			return err
		}
		for val1 := 0; val1 < len(r.JniPackages); val1++ {
			if err = gobtools.EncodeInterface(ctx, buf, r.JniPackages[val1]); err != nil {
				return err
			}
		}
	}
	return err
}

func (r *JniPackageInfo) Decode(ctx gobtools.EncContext, buf *bytes.Reader) error {
	var err error

	var val3 int32
	err = gobtools.DecodeSimple[int32](buf, &val3)
	if err != nil {
		return err
	}
	if val3 != -1 {
		r.JniPackages = make([]android.Path, val3)
		for val4 := 0; val4 < int(val3); val4++ {
			if val6, err := gobtools.DecodeInterface(ctx, buf); err != nil {
				return err
			} else if val6 == nil {
				r.JniPackages[val4] = nil
			} else {
				r.JniPackages[val4] = val6.(android.Path)
			}
		}
	}

	return err
}

var JniPackageInfoGobRegId int16

func (r JniPackageInfo) GetTypeId() int16 {
	return JniPackageInfoGobRegId
}

func (r AARInfo) Encode(ctx gobtools.EncContext, buf *bytes.Buffer) error {
	var err error

	if err = gobtools.EncodeInterface(ctx, buf, r.Aar); err != nil {
		return err
	}
	return err
}

func (r *AARInfo) Decode(ctx gobtools.EncContext, buf *bytes.Reader) error {
	var err error

	if val2, err := gobtools.DecodeInterface(ctx, buf); err != nil {
		return err
	} else if val2 == nil {
		r.Aar = nil
	} else {
		r.Aar = val2.(android.Path)
	}

	return err
}

var AARInfoGobRegId int16

func (r AARInfo) GetTypeId() int16 {
	return AARInfoGobRegId
}
