// Code generated by go run gob_gen.go; DO NOT EDIT.

package java

import (
	"android/soong/android"
	"bytes"
	"github.com/google/blueprint/gobtools"
)

func init() {
	FlagsPackagesGobRegId = gobtools.RegisterType(func() gobtools.CustomDec { return new(FlagsPackages) })
	AppInfoGobRegId = gobtools.RegisterType(func() gobtools.CustomDec { return new(AppInfo) })
	CertificateGobRegId = gobtools.RegisterType(func() gobtools.CustomDec { return new(Certificate) })
	AndroidAppCertificateInfoGobRegId = gobtools.RegisterType(func() gobtools.CustomDec { return new(AndroidAppCertificateInfo) })
	BundleInfoGobRegId = gobtools.RegisterType(func() gobtools.CustomDec { return new(BundleInfo) })
}

func (r FlagsPackages) Encode(ctx gobtools.EncContext, buf *bytes.Buffer) error {
	var err error

	if r.AconfigTextFiles == nil {
		if err = gobtools.EncodeInt(buf, -1); err != nil {
			return err
		}
	} else {
		if err = gobtools.EncodeInt(buf, len(r.AconfigTextFiles)); err != nil {
			return err
		}
		for val1 := 0; val1 < len(r.AconfigTextFiles); val1++ {
			if err = gobtools.EncodeInterface(ctx, buf, r.AconfigTextFiles[val1]); err != nil {
				return err
			}
		}
	}
	return err
}

func (r *FlagsPackages) Decode(ctx gobtools.EncContext, buf *bytes.Reader) error {
	var err error

	var val3 int
	err = gobtools.DecodeInt(buf, &val3)
	if err != nil {
		return err
	}
	if val3 != -1 {
		r.AconfigTextFiles = make([]android.Path, val3)
		for val4 := 0; val4 < int(val3); val4++ {
			if val6, err := gobtools.DecodeInterface(ctx, buf); err != nil {
				return err
			} else if val6 == nil {
				r.AconfigTextFiles[val4] = nil
			} else {
				r.AconfigTextFiles[val4] = val6.(android.Path)
			}
		}
	}

	return err
}

var FlagsPackagesGobRegId int16

func (r FlagsPackages) GetTypeId() int16 {
	return FlagsPackagesGobRegId
}

func (r AppInfo) Encode(ctx gobtools.EncContext, buf *bytes.Buffer) error {
	var err error

	if err = gobtools.EncodeBool(buf, r.Updatable); err != nil {
		return err
	}

	if err = gobtools.EncodeBool(buf, r.TestHelperApp); err != nil {
		return err
	}

	if r.EmbeddedJNILibs == nil {
		if err = gobtools.EncodeInt(buf, -1); err != nil {
			return err
		}
	} else {
		if err = gobtools.EncodeInt(buf, len(r.EmbeddedJNILibs)); err != nil {
			return err
		}
		for val1 := 0; val1 < len(r.EmbeddedJNILibs); val1++ {
			if err = gobtools.EncodeInterface(ctx, buf, r.EmbeddedJNILibs[val1]); err != nil {
				return err
			}
		}
	}

	if err = gobtools.EncodeInterface(ctx, buf, r.MergedManifestFile); err != nil {
		return err
	}

	if err = gobtools.EncodeBool(buf, r.Prebuilt); err != nil {
		return err
	}

	if err = gobtools.EncodeBool(buf, r.AppSet); err != nil {
		return err
	}

	if err = gobtools.EncodeBool(buf, r.Privileged); err != nil {
		return err
	}

	if err = gobtools.EncodeInterface(ctx, buf, r.OutputFile); err != nil {
		return err
	}

	if err = gobtools.EncodeString(buf, r.InstallApkName); err != nil {
		return err
	}

	if err = r.JacocoInfo.Encode(ctx, buf); err != nil {
		return err
	}

	if err = r.Certificate.Encode(ctx, buf); err != nil {
		return err
	}

	if err = r.PrivAppAllowlist.Encode(ctx, buf); err != nil {
		return err
	}

	val2 := r.OverriddenManifestPackageName == nil
	if err = gobtools.EncodeBool(buf, val2); err != nil {
		return err
	}
	if !val2 {
		if err = gobtools.EncodeString(buf, (*r.OverriddenManifestPackageName)); err != nil {
			return err
		}
	}

	if err = gobtools.EncodeInterface(ctx, buf, r.ApkCertsFile); err != nil {
		return err
	}

	if r.JniLibs == nil {
		if err = gobtools.EncodeInt(buf, -1); err != nil {
			return err
		}
	} else {
		if err = gobtools.EncodeInt(buf, len(r.JniLibs)); err != nil {
			return err
		}
		for val3 := 0; val3 < len(r.JniLibs); val3++ {
			if err = r.JniLibs[val3].Encode(ctx, buf); err != nil {
				return err
			}
		}
	}

	if r.JniCoverageOutputs == nil {
		if err = gobtools.EncodeInt(buf, -1); err != nil {
			return err
		}
	} else {
		if err = gobtools.EncodeInt(buf, len(r.JniCoverageOutputs)); err != nil {
			return err
		}
		for val4 := 0; val4 < len(r.JniCoverageOutputs); val4++ {
			if err = gobtools.EncodeInterface(ctx, buf, r.JniCoverageOutputs[val4]); err != nil {
				return err
			}
		}
	}

	if err = gobtools.EncodeInterface(ctx, buf, r.PackedAdditionalOutputs); err != nil {
		return err
	}
	return err
}

func (r *AppInfo) Decode(ctx gobtools.EncContext, buf *bytes.Reader) error {
	var err error

	err = gobtools.DecodeBool(buf, &r.Updatable)
	if err != nil {
		return err
	}

	err = gobtools.DecodeBool(buf, &r.TestHelperApp)
	if err != nil {
		return err
	}

	var val5 int
	err = gobtools.DecodeInt(buf, &val5)
	if err != nil {
		return err
	}
	if val5 != -1 {
		r.EmbeddedJNILibs = make([]android.Path, val5)
		for val6 := 0; val6 < int(val5); val6++ {
			if val8, err := gobtools.DecodeInterface(ctx, buf); err != nil {
				return err
			} else if val8 == nil {
				r.EmbeddedJNILibs[val6] = nil
			} else {
				r.EmbeddedJNILibs[val6] = val8.(android.Path)
			}
		}
	}

	if val10, err := gobtools.DecodeInterface(ctx, buf); err != nil {
		return err
	} else if val10 == nil {
		r.MergedManifestFile = nil
	} else {
		r.MergedManifestFile = val10.(android.Path)
	}

	err = gobtools.DecodeBool(buf, &r.Prebuilt)
	if err != nil {
		return err
	}

	err = gobtools.DecodeBool(buf, &r.AppSet)
	if err != nil {
		return err
	}

	err = gobtools.DecodeBool(buf, &r.Privileged)
	if err != nil {
		return err
	}

	if val15, err := gobtools.DecodeInterface(ctx, buf); err != nil {
		return err
	} else if val15 == nil {
		r.OutputFile = nil
	} else {
		r.OutputFile = val15.(android.Path)
	}

	err = gobtools.DecodeString(buf, &r.InstallApkName)
	if err != nil {
		return err
	}

	if err = r.JacocoInfo.Decode(ctx, buf); err != nil {
		return err
	}

	if err = r.Certificate.Decode(ctx, buf); err != nil {
		return err
	}

	if err = r.PrivAppAllowlist.Decode(ctx, buf); err != nil {
		return err
	}

	var val21 bool
	if err = gobtools.DecodeBool(buf, &val21); err != nil {
		return err
	}
	if !val21 {
		var val20 string
		err = gobtools.DecodeString(buf, &val20)
		if err != nil {
			return err
		}
		r.OverriddenManifestPackageName = &val20
	}

	if val24, err := gobtools.DecodeInterface(ctx, buf); err != nil {
		return err
	} else if val24 == nil {
		r.ApkCertsFile = nil
	} else {
		r.ApkCertsFile = val24.(android.Path)
	}

	var val26 int
	err = gobtools.DecodeInt(buf, &val26)
	if err != nil {
		return err
	}
	if val26 != -1 {
		r.JniLibs = make([]jniLib, val26)
		for val27 := 0; val27 < int(val26); val27++ {
			if err = r.JniLibs[val27].Decode(ctx, buf); err != nil {
				return err
			}
		}
	}

	var val31 int
	err = gobtools.DecodeInt(buf, &val31)
	if err != nil {
		return err
	}
	if val31 != -1 {
		r.JniCoverageOutputs = make([]android.Path, val31)
		for val32 := 0; val32 < int(val31); val32++ {
			if val34, err := gobtools.DecodeInterface(ctx, buf); err != nil {
				return err
			} else if val34 == nil {
				r.JniCoverageOutputs[val32] = nil
			} else {
				r.JniCoverageOutputs[val32] = val34.(android.Path)
			}
		}
	}

	if val36, err := gobtools.DecodeInterface(ctx, buf); err != nil {
		return err
	} else if val36 == nil {
		r.PackedAdditionalOutputs = nil
	} else {
		r.PackedAdditionalOutputs = val36.(android.Path)
	}

	return err
}

var AppInfoGobRegId int16

func (r AppInfo) GetTypeId() int16 {
	return AppInfoGobRegId
}

func (r Certificate) Encode(ctx gobtools.EncContext, buf *bytes.Buffer) error {
	var err error

	if err = gobtools.EncodeInterface(ctx, buf, r.Pem); err != nil {
		return err
	}
	if err = gobtools.EncodeInterface(ctx, buf, r.Key); err != nil {
		return err
	}

	if err = gobtools.EncodeBool(buf, r.presigned); err != nil {
		return err
	}
	return err
}

func (r *Certificate) Decode(ctx gobtools.EncContext, buf *bytes.Reader) error {
	var err error

	if val2, err := gobtools.DecodeInterface(ctx, buf); err != nil {
		return err
	} else if val2 == nil {
		r.Pem = nil
	} else {
		r.Pem = val2.(android.Path)
	}
	if val4, err := gobtools.DecodeInterface(ctx, buf); err != nil {
		return err
	} else if val4 == nil {
		r.Key = nil
	} else {
		r.Key = val4.(android.Path)
	}

	err = gobtools.DecodeBool(buf, &r.presigned)
	if err != nil {
		return err
	}

	return err
}

var CertificateGobRegId int16

func (r Certificate) GetTypeId() int16 {
	return CertificateGobRegId
}

func (r AndroidAppCertificateInfo) Encode(ctx gobtools.EncContext, buf *bytes.Buffer) error {
	var err error

	if err = r.Certificate.Encode(ctx, buf); err != nil {
		return err
	}
	return err
}

func (r *AndroidAppCertificateInfo) Decode(ctx gobtools.EncContext, buf *bytes.Reader) error {
	var err error

	if err = r.Certificate.Decode(ctx, buf); err != nil {
		return err
	}

	return err
}

var AndroidAppCertificateInfoGobRegId int16

func (r AndroidAppCertificateInfo) GetTypeId() int16 {
	return AndroidAppCertificateInfoGobRegId
}

func (r BundleInfo) Encode(ctx gobtools.EncContext, buf *bytes.Buffer) error {
	var err error

	if err = gobtools.EncodeInterface(ctx, buf, r.Bundle); err != nil {
		return err
	}
	return err
}

func (r *BundleInfo) Decode(ctx gobtools.EncContext, buf *bytes.Reader) error {
	var err error

	if val2, err := gobtools.DecodeInterface(ctx, buf); err != nil {
		return err
	} else if val2 == nil {
		r.Bundle = nil
	} else {
		r.Bundle = val2.(android.Path)
	}

	return err
}

var BundleInfoGobRegId int16

func (r BundleInfo) GetTypeId() int16 {
	return BundleInfoGobRegId
}
