// Code generated by go run gob_gen.go; DO NOT EDIT.

package java

import (
	"bytes"
	"github.com/google/blueprint/gobtools"
)

func init() {
	ApexVariantReferenceGobRegId = gobtools.RegisterType(func() gobtools.CustomDec { return new(ApexVariantReference) })
}

func (r ApexVariantReference) Encode(ctx gobtools.EncContext, buf *bytes.Buffer) error {
	var err error

	if err = r.BpPrintableBase.Encode(ctx, buf); err != nil {
		return err
	}

	val1 := r.Apex == nil
	if err = gobtools.EncodeBool(buf, val1); err != nil {
		return err
	}
	if !val1 {
		if err = gobtools.EncodeString(buf, (*r.Apex)); err != nil {
			return err
		}
	}

	val2 := r.Module == nil
	if err = gobtools.EncodeBool(buf, val2); err != nil {
		return err
	}
	if !val2 {
		if err = gobtools.EncodeString(buf, (*r.Module)); err != nil {
			return err
		}
	}
	return err
}

func (r *ApexVariantReference) Decode(ctx gobtools.EncContext, buf *bytes.Reader) error {
	var err error

	if err = r.BpPrintableBase.Decode(ctx, buf); err != nil {
		return err
	}

	var val3 bool
	if err = gobtools.DecodeBool(buf, &val3); err != nil {
		return err
	}
	if !val3 {
		var val2 string
		err = gobtools.DecodeString(buf, &val2)
		if err != nil {
			return err
		}
		r.Apex = &val2
	}

	var val6 bool
	if err = gobtools.DecodeBool(buf, &val6); err != nil {
		return err
	}
	if !val6 {
		var val5 string
		err = gobtools.DecodeString(buf, &val5)
		if err != nil {
			return err
		}
		r.Module = &val5
	}

	return err
}

var ApexVariantReferenceGobRegId int16

func (r ApexVariantReference) GetTypeId() int16 {
	return ApexVariantReferenceGobRegId
}
