// Code generated by go run gob_gen.go; DO NOT EDIT.

package java

import (
	"android/soong/android"
	"bytes"
	"github.com/google/blueprint/gobtools"
)

func init() {
	BootclasspathFragmentInfoGobRegId = gobtools.RegisterType(func() gobtools.CustomDec { return new(BootclasspathFragmentInfo) })
	BootclasspathFragmentApexContentInfoGobRegId = gobtools.RegisterType(func() gobtools.CustomDec { return new(BootclasspathFragmentApexContentInfo) })
}

func (r BootclasspathFragmentInfo) Encode(ctx gobtools.EncContext, buf *bytes.Buffer) error {
	var err error

	val1 := r.ImageName == nil
	if err = gobtools.EncodeBool(buf, val1); err != nil {
		return err
	}
	if !val1 {
		if err = gobtools.EncodeString(buf, (*r.ImageName)); err != nil {
			return err
		}
	}

	if r.Contents == nil {
		if err = gobtools.EncodeInt(buf, -1); err != nil {
			return err
		}
	} else {
		if err = gobtools.EncodeInt(buf, len(r.Contents)); err != nil {
			return err
		}
		for val2 := 0; val2 < len(r.Contents); val2++ {
			if err = gobtools.EncodeString(buf, r.Contents[val2]); err != nil {
				return err
			}
		}
	}

	if r.ApiStubLibs == nil {
		if err = gobtools.EncodeInt(buf, -1); err != nil {
			return err
		}
	} else {
		if err = gobtools.EncodeInt(buf, len(r.ApiStubLibs)); err != nil {
			return err
		}
		for val3 := 0; val3 < len(r.ApiStubLibs); val3++ {
			if err = gobtools.EncodeString(buf, r.ApiStubLibs[val3]); err != nil {
				return err
			}
		}
	}

	if r.CorePlatformApiStubLibs == nil {
		if err = gobtools.EncodeInt(buf, -1); err != nil {
			return err
		}
	} else {
		if err = gobtools.EncodeInt(buf, len(r.CorePlatformApiStubLibs)); err != nil {
			return err
		}
		for val4 := 0; val4 < len(r.CorePlatformApiStubLibs); val4++ {
			if err = gobtools.EncodeString(buf, r.CorePlatformApiStubLibs[val4]); err != nil {
				return err
			}
		}
	}

	if r.Fragments == nil {
		if err = gobtools.EncodeInt(buf, -1); err != nil {
			return err
		}
	} else {
		if err = gobtools.EncodeInt(buf, len(r.Fragments)); err != nil {
			return err
		}
		for val5 := 0; val5 < len(r.Fragments); val5++ {
			if err = r.Fragments[val5].Encode(ctx, buf); err != nil {
				return err
			}
		}
	}

	if err = gobtools.EncodeInterface(ctx, buf, r.ProfilePathOnHost); err != nil {
		return err
	}
	return err
}

func (r *BootclasspathFragmentInfo) Decode(ctx gobtools.EncContext, buf *bytes.Reader) error {
	var err error

	var val2 bool
	if err = gobtools.DecodeBool(buf, &val2); err != nil {
		return err
	}
	if !val2 {
		var val1 string
		err = gobtools.DecodeString(buf, &val1)
		if err != nil {
			return err
		}
		r.ImageName = &val1
	}

	var val5 int
	err = gobtools.DecodeInt(buf, &val5)
	if err != nil {
		return err
	}
	if val5 != -1 {
		r.Contents = make([]string, val5)
		for val6 := 0; val6 < int(val5); val6++ {
			err = gobtools.DecodeString(buf, &r.Contents[val6])
			if err != nil {
				return err
			}
		}
	}

	var val9 int
	err = gobtools.DecodeInt(buf, &val9)
	if err != nil {
		return err
	}
	if val9 != -1 {
		r.ApiStubLibs = make([]string, val9)
		for val10 := 0; val10 < int(val9); val10++ {
			err = gobtools.DecodeString(buf, &r.ApiStubLibs[val10])
			if err != nil {
				return err
			}
		}
	}

	var val13 int
	err = gobtools.DecodeInt(buf, &val13)
	if err != nil {
		return err
	}
	if val13 != -1 {
		r.CorePlatformApiStubLibs = make([]string, val13)
		for val14 := 0; val14 < int(val13); val14++ {
			err = gobtools.DecodeString(buf, &r.CorePlatformApiStubLibs[val14])
			if err != nil {
				return err
			}
		}
	}

	var val17 int
	err = gobtools.DecodeInt(buf, &val17)
	if err != nil {
		return err
	}
	if val17 != -1 {
		r.Fragments = make([]ApexVariantReference, val17)
		for val18 := 0; val18 < int(val17); val18++ {
			if err = r.Fragments[val18].Decode(ctx, buf); err != nil {
				return err
			}
		}
	}

	if val21, err := gobtools.DecodeInterface(ctx, buf); err != nil {
		return err
	} else if val21 == nil {
		r.ProfilePathOnHost = nil
	} else {
		r.ProfilePathOnHost = val21.(android.Path)
	}

	return err
}

var BootclasspathFragmentInfoGobRegId int16

func (r BootclasspathFragmentInfo) GetTypeId() int16 {
	return BootclasspathFragmentInfoGobRegId
}

func (r BootclasspathFragmentApexContentInfo) Encode(ctx gobtools.EncContext, buf *bytes.Buffer) error {
	var err error

	if r.contentModuleDexJarPaths == nil {
		if err = gobtools.EncodeInt(buf, -1); err != nil {
			return err
		}
	} else {
		if err = gobtools.EncodeInt(buf, len(r.contentModuleDexJarPaths)); err != nil {
			return err
		}
		for k, v := range r.contentModuleDexJarPaths {
			if err = gobtools.EncodeString(buf, k); err != nil {
				return err
			}
			if err = gobtools.EncodeInterface(ctx, buf, v); err != nil {
				return err
			}
		}
	}

	if err = gobtools.EncodeInterface(ctx, buf, r.profilePathOnHost); err != nil {
		return err
	}

	if err = gobtools.EncodeString(buf, r.profileInstallPathInApex); err != nil {
		return err
	}
	return err
}

func (r *BootclasspathFragmentApexContentInfo) Decode(ctx gobtools.EncContext, buf *bytes.Reader) error {
	var err error

	var val2 int
	err = gobtools.DecodeInt(buf, &val2)
	if err != nil {
		return err
	}
	if val2 != -1 {
		r.contentModuleDexJarPaths = make(map[string]android.Path, val2)
		for val3 := 0; val3 < int(val2); val3++ {
			var k string
			var v android.Path
			err = gobtools.DecodeString(buf, &k)
			if err != nil {
				return err
			}
			if val6, err := gobtools.DecodeInterface(ctx, buf); err != nil {
				return err
			} else if val6 == nil {
				v = nil
			} else {
				v = val6.(android.Path)
			}
			r.contentModuleDexJarPaths[k] = v
		}
	}

	if val8, err := gobtools.DecodeInterface(ctx, buf); err != nil {
		return err
	} else if val8 == nil {
		r.profilePathOnHost = nil
	} else {
		r.profilePathOnHost = val8.(android.Path)
	}

	err = gobtools.DecodeString(buf, &r.profileInstallPathInApex)
	if err != nil {
		return err
	}

	return err
}

var BootclasspathFragmentApexContentInfoGobRegId int16

func (r BootclasspathFragmentApexContentInfo) GetTypeId() int16 {
	return BootclasspathFragmentApexContentInfoGobRegId
}
