// Code generated by go run gob_gen.go; DO NOT EDIT.

package java

import (
	"android/soong/android"
	"bytes"
	"github.com/google/blueprint/gobtools"
)

func init() {
	ProguardInfoGobRegId = gobtools.RegisterType(func() gobtools.CustomDec { return new(ProguardInfo) })
}

func (r ProguardInfo) Encode(ctx gobtools.EncContext, buf *bytes.Buffer) error {
	var err error

	if err = gobtools.EncodeString(buf, r.ModuleName); err != nil {
		return err
	}

	if err = gobtools.EncodeString(buf, r.Class); err != nil {
		return err
	}

	if err = gobtools.EncodeInterface(ctx, buf, r.ProguardDictionary); err != nil {
		return err
	}

	if err = gobtools.EncodeInterface(ctx, buf, r.ProguardUsageZip); err != nil {
		return err
	}

	if err = gobtools.EncodeInterface(ctx, buf, r.ClassesJar); err != nil {
		return err
	}
	return err
}

func (r *ProguardInfo) Decode(ctx gobtools.EncContext, buf *bytes.Reader) error {
	var err error

	err = gobtools.DecodeString(buf, &r.ModuleName)
	if err != nil {
		return err
	}

	err = gobtools.DecodeString(buf, &r.Class)
	if err != nil {
		return err
	}

	if val4, err := gobtools.DecodeInterface(ctx, buf); err != nil {
		return err
	} else if val4 == nil {
		r.ProguardDictionary = nil
	} else {
		r.ProguardDictionary = val4.(android.Path)
	}

	if val6, err := gobtools.DecodeInterface(ctx, buf); err != nil {
		return err
	} else if val6 == nil {
		r.ProguardUsageZip = nil
	} else {
		r.ProguardUsageZip = val6.(android.Path)
	}

	if val8, err := gobtools.DecodeInterface(ctx, buf); err != nil {
		return err
	} else if val8 == nil {
		r.ClassesJar = nil
	} else {
		r.ClassesJar = val8.(android.Path)
	}

	return err
}

var ProguardInfoGobRegId int16

func (r ProguardInfo) GetTypeId() int16 {
	return ProguardInfoGobRegId
}
