// Code generated by go run gob_gen.go; DO NOT EDIT.

package java

import (
	"android/soong/android"
	"bytes"
	"github.com/google/blueprint/gobtools"
)

func init() {
	StubsInfoGobRegId = gobtools.RegisterType(func() gobtools.CustomDec { return new(StubsInfo) })
	DroidStubsInfoGobRegId = gobtools.RegisterType(func() gobtools.CustomDec { return new(DroidStubsInfo) })
	StubsSrcInfoGobRegId = gobtools.RegisterType(func() gobtools.CustomDec { return new(StubsSrcInfo) })
	UpdateApiInfoGobRegId = gobtools.RegisterType(func() gobtools.CustomDec { return new(UpdateApiInfo) })
}

func (r StubsInfo) Encode(ctx gobtools.EncContext, buf *bytes.Buffer) error {
	var err error

	if err = gobtools.EncodeInterface(ctx, buf, r.ApiVersionsXml); err != nil {
		return err
	}

	if err = gobtools.EncodeInterface(ctx, buf, r.AnnotationsZip); err != nil {
		return err
	}

	if err = gobtools.EncodeInterface(ctx, buf, r.ApiFile); err != nil {
		return err
	}

	if err = gobtools.EncodeInterface(ctx, buf, r.RemovedApiFile); err != nil {
		return err
	}
	return err
}

func (r *StubsInfo) Decode(ctx gobtools.EncContext, buf *bytes.Reader) error {
	var err error

	if val2, err := gobtools.DecodeInterface(ctx, buf); err != nil {
		return err
	} else if val2 == nil {
		r.ApiVersionsXml = nil
	} else {
		r.ApiVersionsXml = val2.(android.Path)
	}

	if val4, err := gobtools.DecodeInterface(ctx, buf); err != nil {
		return err
	} else if val4 == nil {
		r.AnnotationsZip = nil
	} else {
		r.AnnotationsZip = val4.(android.Path)
	}

	if val6, err := gobtools.DecodeInterface(ctx, buf); err != nil {
		return err
	} else if val6 == nil {
		r.ApiFile = nil
	} else {
		r.ApiFile = val6.(android.Path)
	}

	if val8, err := gobtools.DecodeInterface(ctx, buf); err != nil {
		return err
	} else if val8 == nil {
		r.RemovedApiFile = nil
	} else {
		r.RemovedApiFile = val8.(android.Path)
	}

	return err
}

var StubsInfoGobRegId int16

func (r StubsInfo) GetTypeId() int16 {
	return StubsInfoGobRegId
}

func (r DroidStubsInfo) Encode(ctx gobtools.EncContext, buf *bytes.Buffer) error {
	var err error

	if err = gobtools.EncodeInterface(ctx, buf, r.CheckedInApiFile); err != nil {
		return err
	}

	if err = gobtools.EncodeInterface(ctx, buf, r.CheckedInRemovedApiFile); err != nil {
		return err
	}

	if r.AconfigProtoFiles == nil {
		if err = gobtools.EncodeInt(buf, -1); err != nil {
			return err
		}
	} else {
		if err = gobtools.EncodeInt(buf, len(r.AconfigProtoFiles)); err != nil {
			return err
		}
		for val1 := 0; val1 < len(r.AconfigProtoFiles); val1++ {
			if err = gobtools.EncodeInterface(ctx, buf, r.AconfigProtoFiles[val1]); err != nil {
				return err
			}
		}
	}

	if err = gobtools.EncodeInterface(ctx, buf, r.CurrentApiTimestamp); err != nil {
		return err
	}

	if err = r.EverythingStubsInfo.Encode(ctx, buf); err != nil {
		return err
	}

	if err = r.ExportableStubsInfo.Encode(ctx, buf); err != nil {
		return err
	}
	return err
}

func (r *DroidStubsInfo) Decode(ctx gobtools.EncContext, buf *bytes.Reader) error {
	var err error

	if val2, err := gobtools.DecodeInterface(ctx, buf); err != nil {
		return err
	} else if val2 == nil {
		r.CheckedInApiFile = nil
	} else {
		r.CheckedInApiFile = val2.(android.Path)
	}

	if val4, err := gobtools.DecodeInterface(ctx, buf); err != nil {
		return err
	} else if val4 == nil {
		r.CheckedInRemovedApiFile = nil
	} else {
		r.CheckedInRemovedApiFile = val4.(android.Path)
	}

	var val7 int
	err = gobtools.DecodeInt(buf, &val7)
	if err != nil {
		return err
	}
	if val7 != -1 {
		r.AconfigProtoFiles = make([]android.Path, val7)
		for val8 := 0; val8 < int(val7); val8++ {
			if val10, err := gobtools.DecodeInterface(ctx, buf); err != nil {
				return err
			} else if val10 == nil {
				r.AconfigProtoFiles[val8] = nil
			} else {
				r.AconfigProtoFiles[val8] = val10.(android.Path)
			}
		}
	}

	if val12, err := gobtools.DecodeInterface(ctx, buf); err != nil {
		return err
	} else if val12 == nil {
		r.CurrentApiTimestamp = nil
	} else {
		r.CurrentApiTimestamp = val12.(android.Path)
	}

	if err = r.EverythingStubsInfo.Decode(ctx, buf); err != nil {
		return err
	}

	if err = r.ExportableStubsInfo.Decode(ctx, buf); err != nil {
		return err
	}

	return err
}

var DroidStubsInfoGobRegId int16

func (r DroidStubsInfo) GetTypeId() int16 {
	return DroidStubsInfoGobRegId
}

func (r StubsSrcInfo) Encode(ctx gobtools.EncContext, buf *bytes.Buffer) error {
	var err error

	if err = gobtools.EncodeInterface(ctx, buf, r.EverythingStubsSrcJar); err != nil {
		return err
	}

	if err = gobtools.EncodeInterface(ctx, buf, r.ExportableStubsSrcJar); err != nil {
		return err
	}
	return err
}

func (r *StubsSrcInfo) Decode(ctx gobtools.EncContext, buf *bytes.Reader) error {
	var err error

	if val2, err := gobtools.DecodeInterface(ctx, buf); err != nil {
		return err
	} else if val2 == nil {
		r.EverythingStubsSrcJar = nil
	} else {
		r.EverythingStubsSrcJar = val2.(android.Path)
	}

	if val4, err := gobtools.DecodeInterface(ctx, buf); err != nil {
		return err
	} else if val4 == nil {
		r.ExportableStubsSrcJar = nil
	} else {
		r.ExportableStubsSrcJar = val4.(android.Path)
	}

	return err
}

var StubsSrcInfoGobRegId int16

func (r StubsSrcInfo) GetTypeId() int16 {
	return StubsSrcInfoGobRegId
}

func (r UpdateApiInfo) Encode(ctx gobtools.EncContext, buf *bytes.Buffer) error {
	var err error

	if err = gobtools.EncodeString(buf, r.Name); err != nil {
		return err
	}

	if err = gobtools.EncodeInterface(ctx, buf, r.SourceApiFile); err != nil {
		return err
	}

	if err = gobtools.EncodeInterface(ctx, buf, r.GeneratedApiFile); err != nil {
		return err
	}

	if err = gobtools.EncodeInterface(ctx, buf, r.SourceRemovedFile); err != nil {
		return err
	}

	if err = gobtools.EncodeInterface(ctx, buf, r.GeneratedRemovedFile); err != nil {
		return err
	}
	return err
}

func (r *UpdateApiInfo) Decode(ctx gobtools.EncContext, buf *bytes.Reader) error {
	var err error

	err = gobtools.DecodeString(buf, &r.Name)
	if err != nil {
		return err
	}

	if val3, err := gobtools.DecodeInterface(ctx, buf); err != nil {
		return err
	} else if val3 == nil {
		r.SourceApiFile = nil
	} else {
		r.SourceApiFile = val3.(android.Path)
	}

	if val5, err := gobtools.DecodeInterface(ctx, buf); err != nil {
		return err
	} else if val5 == nil {
		r.GeneratedApiFile = nil
	} else {
		r.GeneratedApiFile = val5.(android.Path)
	}

	if val7, err := gobtools.DecodeInterface(ctx, buf); err != nil {
		return err
	} else if val7 == nil {
		r.SourceRemovedFile = nil
	} else {
		r.SourceRemovedFile = val7.(android.Path)
	}

	if val9, err := gobtools.DecodeInterface(ctx, buf); err != nil {
		return err
	} else if val9 == nil {
		r.GeneratedRemovedFile = nil
	} else {
		r.GeneratedRemovedFile = val9.(android.Path)
	}

	return err
}

var UpdateApiInfoGobRegId int16

func (r UpdateApiInfo) GetTypeId() int16 {
	return UpdateApiInfoGobRegId
}
