// Code generated by go run gob_gen.go; DO NOT EDIT.

package java

import (
	"android/soong/android"
	"bytes"
	"github.com/google/blueprint/gobtools"
)

func init() {
	HiddenAPIScopeGobRegId = gobtools.RegisterType(func() gobtools.CustomDec { return new(HiddenAPIScope) })
	FlagFilesByCategoryGobRegId = gobtools.RegisterType(func() gobtools.CustomDec { return new(FlagFilesByCategory) })
	HiddenAPIInfoGobRegId = gobtools.RegisterType(func() gobtools.CustomDec { return new(HiddenAPIInfo) })
	HiddenAPIInfoForSdkGobRegId = gobtools.RegisterType(func() gobtools.CustomDec { return new(HiddenAPIInfoForSdk) })
	ModuleStubDexJarsGobRegId = gobtools.RegisterType(func() gobtools.CustomDec { return new(ModuleStubDexJars) })
	HiddenAPIPropertyInfoGobRegId = gobtools.RegisterType(func() gobtools.CustomDec { return new(HiddenAPIPropertyInfo) })
	HiddenAPIFlagOutputGobRegId = gobtools.RegisterType(func() gobtools.CustomDec { return new(HiddenAPIFlagOutput) })
	SignatureCsvSubsetGobRegId = gobtools.RegisterType(func() gobtools.CustomDec { return new(SignatureCsvSubset) })
	SignatureCsvSubsetsGobRegId = gobtools.RegisterType(func() gobtools.CustomDec { return new(SignatureCsvSubsets) })
}

func (r HiddenAPIScope) Encode(ctx gobtools.EncContext, buf *bytes.Buffer) error {
	var err error

	if err = gobtools.EncodeString(buf, r.name); err != nil {
		return err
	}

	if err = gobtools.EncodeInt(buf, int(r.sdkKind)); err != nil {
		return err
	}

	if err = gobtools.EncodeString(buf, r.hiddenAPIListOption); err != nil {
		return err
	}

	if err = gobtools.EncodeString(buf, r.nonUpdatableSourceModule); err != nil {
		return err
	}

	if err = gobtools.EncodeString(buf, r.nonUpdatableFromTextModule); err != nil {
		return err
	}

	if err = gobtools.EncodeString(buf, r.nonUpdatablePrebuiltModule); err != nil {
		return err
	}
	return err
}

func (r *HiddenAPIScope) Decode(ctx gobtools.EncContext, buf *bytes.Reader) error {
	var err error

	err = gobtools.DecodeString(buf, &r.name)
	if err != nil {
		return err
	}

	var val3 int
	err = gobtools.DecodeInt(buf, &val3)
	if err != nil {
		return err
	}
	r.sdkKind = android.SdkKind(val3)

	err = gobtools.DecodeString(buf, &r.hiddenAPIListOption)
	if err != nil {
		return err
	}

	err = gobtools.DecodeString(buf, &r.nonUpdatableSourceModule)
	if err != nil {
		return err
	}

	err = gobtools.DecodeString(buf, &r.nonUpdatableFromTextModule)
	if err != nil {
		return err
	}

	err = gobtools.DecodeString(buf, &r.nonUpdatablePrebuiltModule)
	if err != nil {
		return err
	}

	return err
}

var HiddenAPIScopeGobRegId int16

func (r HiddenAPIScope) GetTypeId() int16 {
	return HiddenAPIScopeGobRegId
}

func (r FlagFilesByCategory) Encode(ctx gobtools.EncContext, buf *bytes.Buffer) error {
	var err error

	if r == nil {
		if err = gobtools.EncodeInt(buf, -1); err != nil {
			return err
		}
	} else {
		if err = gobtools.EncodeInt(buf, len(r)); err != nil {
			return err
		}
		for val1, val2 := range r {
			if err = gobtools.EncodeInt(buf, int(val1)); err != nil {
				return err
			}
			if val2 == nil {
				if err = gobtools.EncodeInt(buf, -1); err != nil {
					return err
				}
			} else {
				if err = gobtools.EncodeInt(buf, len(val2)); err != nil {
					return err
				}
				for val3 := 0; val3 < len(val2); val3++ {
					if err = gobtools.EncodeInterface(ctx, buf, val2[val3]); err != nil {
						return err
					}
				}
			}
		}
	}
	return err
}

func (r *FlagFilesByCategory) Decode(ctx gobtools.EncContext, buf *bytes.Reader) error {
	var err error

	var val1 int
	err = gobtools.DecodeInt(buf, &val1)
	if err != nil {
		return err
	}
	if val1 != -1 {
		(*r) = make(map[hiddenAPIFlagFileCategory]android.Paths, val1)
		for val2 := 0; val2 < int(val1); val2++ {
			var val3 hiddenAPIFlagFileCategory
			var val4 android.Paths
			var val6 int
			err = gobtools.DecodeInt(buf, &val6)
			if err != nil {
				return err
			}
			val3 = hiddenAPIFlagFileCategory(val6)
			var val10 int
			err = gobtools.DecodeInt(buf, &val10)
			if err != nil {
				return err
			}
			if val10 != -1 {
				val4 = make([]android.Path, val10)
				for val11 := 0; val11 < int(val10); val11++ {
					if val13, err := gobtools.DecodeInterface(ctx, buf); err != nil {
						return err
					} else if val13 == nil {
						val4[val11] = nil
					} else {
						val4[val11] = val13.(android.Path)
					}
				}
			}
			(*r)[val3] = val4
		}
	}

	return err
}

var FlagFilesByCategoryGobRegId int16

func (r FlagFilesByCategory) GetTypeId() int16 {
	return FlagFilesByCategoryGobRegId
}

func (r HiddenAPIInfo) Encode(ctx gobtools.EncContext, buf *bytes.Buffer) error {
	var err error

	if r.FlagFilesByCategory == nil {
		if err = gobtools.EncodeInt(buf, -1); err != nil {
			return err
		}
	} else {
		if err = gobtools.EncodeInt(buf, len(r.FlagFilesByCategory)); err != nil {
			return err
		}
		for val1, val2 := range r.FlagFilesByCategory {
			if err = gobtools.EncodeInt(buf, int(val1)); err != nil {
				return err
			}
			if val2 == nil {
				if err = gobtools.EncodeInt(buf, -1); err != nil {
					return err
				}
			} else {
				if err = gobtools.EncodeInt(buf, len(val2)); err != nil {
					return err
				}
				for val3 := 0; val3 < len(val2); val3++ {
					if err = gobtools.EncodeInterface(ctx, buf, val2[val3]); err != nil {
						return err
					}
				}
			}
		}
	}

	if r.TransitiveStubDexJarsByScope == nil {
		if err = gobtools.EncodeInt(buf, -1); err != nil {
			return err
		}
	} else {
		if err = gobtools.EncodeInt(buf, len(r.TransitiveStubDexJarsByScope)); err != nil {
			return err
		}
		for val4, val5 := range r.TransitiveStubDexJarsByScope {
			if err = gobtools.EncodeString(buf, val4); err != nil {
				return err
			}
			if val5 == nil {
				if err = gobtools.EncodeInt(buf, -1); err != nil {
					return err
				}
			} else {
				if err = gobtools.EncodeInt(buf, len(val5)); err != nil {
					return err
				}
				for val6, val7 := range val5 {
					val8 := val6 == nil
					if err = gobtools.EncodeBool(buf, val8); err != nil {
						return err
					}
					if !val8 {
						if err = (*val6).Encode(ctx, buf); err != nil {
							return err
						}
					}
					if err = gobtools.EncodeInterface(ctx, buf, val7); err != nil {
						return err
					}
				}
			}
		}
	}

	if err = r.HiddenAPIFlagOutput.Encode(ctx, buf); err != nil {
		return err
	}
	return err
}

func (r *HiddenAPIInfo) Decode(ctx gobtools.EncContext, buf *bytes.Reader) error {
	var err error

	var val2 int
	err = gobtools.DecodeInt(buf, &val2)
	if err != nil {
		return err
	}
	if val2 != -1 {
		r.FlagFilesByCategory = make(map[hiddenAPIFlagFileCategory]android.Paths, val2)
		for val3 := 0; val3 < int(val2); val3++ {
			var val4 hiddenAPIFlagFileCategory
			var val5 android.Paths
			var val7 int
			err = gobtools.DecodeInt(buf, &val7)
			if err != nil {
				return err
			}
			val4 = hiddenAPIFlagFileCategory(val7)
			var val11 int
			err = gobtools.DecodeInt(buf, &val11)
			if err != nil {
				return err
			}
			if val11 != -1 {
				val5 = make([]android.Path, val11)
				for val12 := 0; val12 < int(val11); val12++ {
					if val14, err := gobtools.DecodeInterface(ctx, buf); err != nil {
						return err
					} else if val14 == nil {
						val5[val12] = nil
					} else {
						val5[val12] = val14.(android.Path)
					}
				}
			}
			r.FlagFilesByCategory[val4] = val5
		}
	}

	var val16 int
	err = gobtools.DecodeInt(buf, &val16)
	if err != nil {
		return err
	}
	if val16 != -1 {
		r.TransitiveStubDexJarsByScope = make(map[string]ModuleStubDexJars, val16)
		for val17 := 0; val17 < int(val16); val17++ {
			var val18 string
			var val19 ModuleStubDexJars
			err = gobtools.DecodeString(buf, &val18)
			if err != nil {
				return err
			}
			var val22 int
			err = gobtools.DecodeInt(buf, &val22)
			if err != nil {
				return err
			}
			if val22 != -1 {
				val19 = make(map[*HiddenAPIScope]android.Path, val22)
				for val23 := 0; val23 < int(val22); val23++ {
					var val24 *HiddenAPIScope
					var val25 android.Path
					var val27 bool
					if err = gobtools.DecodeBool(buf, &val27); err != nil {
						return err
					}
					if !val27 {
						var val26 HiddenAPIScope
						if err = val26.Decode(ctx, buf); err != nil {
							return err
						}
						val24 = &val26
					}
					if val30, err := gobtools.DecodeInterface(ctx, buf); err != nil {
						return err
					} else if val30 == nil {
						val25 = nil
					} else {
						val25 = val30.(android.Path)
					}
					val19[val24] = val25
				}
			}
			r.TransitiveStubDexJarsByScope[val18] = val19
		}
	}

	if err = r.HiddenAPIFlagOutput.Decode(ctx, buf); err != nil {
		return err
	}

	return err
}

var HiddenAPIInfoGobRegId int16

func (r HiddenAPIInfo) GetTypeId() int16 {
	return HiddenAPIInfoGobRegId
}

func (r HiddenAPIInfoForSdk) Encode(ctx gobtools.EncContext, buf *bytes.Buffer) error {
	var err error

	if r.FlagFilesByCategory == nil {
		if err = gobtools.EncodeInt(buf, -1); err != nil {
			return err
		}
	} else {
		if err = gobtools.EncodeInt(buf, len(r.FlagFilesByCategory)); err != nil {
			return err
		}
		for val1, val2 := range r.FlagFilesByCategory {
			if err = gobtools.EncodeInt(buf, int(val1)); err != nil {
				return err
			}
			if val2 == nil {
				if err = gobtools.EncodeInt(buf, -1); err != nil {
					return err
				}
			} else {
				if err = gobtools.EncodeInt(buf, len(val2)); err != nil {
					return err
				}
				for val3 := 0; val3 < len(val2); val3++ {
					if err = gobtools.EncodeInterface(ctx, buf, val2[val3]); err != nil {
						return err
					}
				}
			}
		}
	}

	if err = r.HiddenAPIFlagOutput.Encode(ctx, buf); err != nil {
		return err
	}
	return err
}

func (r *HiddenAPIInfoForSdk) Decode(ctx gobtools.EncContext, buf *bytes.Reader) error {
	var err error

	var val2 int
	err = gobtools.DecodeInt(buf, &val2)
	if err != nil {
		return err
	}
	if val2 != -1 {
		r.FlagFilesByCategory = make(map[hiddenAPIFlagFileCategory]android.Paths, val2)
		for val3 := 0; val3 < int(val2); val3++ {
			var val4 hiddenAPIFlagFileCategory
			var val5 android.Paths
			var val7 int
			err = gobtools.DecodeInt(buf, &val7)
			if err != nil {
				return err
			}
			val4 = hiddenAPIFlagFileCategory(val7)
			var val11 int
			err = gobtools.DecodeInt(buf, &val11)
			if err != nil {
				return err
			}
			if val11 != -1 {
				val5 = make([]android.Path, val11)
				for val12 := 0; val12 < int(val11); val12++ {
					if val14, err := gobtools.DecodeInterface(ctx, buf); err != nil {
						return err
					} else if val14 == nil {
						val5[val12] = nil
					} else {
						val5[val12] = val14.(android.Path)
					}
				}
			}
			r.FlagFilesByCategory[val4] = val5
		}
	}

	if err = r.HiddenAPIFlagOutput.Decode(ctx, buf); err != nil {
		return err
	}

	return err
}

var HiddenAPIInfoForSdkGobRegId int16

func (r HiddenAPIInfoForSdk) GetTypeId() int16 {
	return HiddenAPIInfoForSdkGobRegId
}

func (r ModuleStubDexJars) Encode(ctx gobtools.EncContext, buf *bytes.Buffer) error {
	var err error

	if r == nil {
		if err = gobtools.EncodeInt(buf, -1); err != nil {
			return err
		}
	} else {
		if err = gobtools.EncodeInt(buf, len(r)); err != nil {
			return err
		}
		for val1, val2 := range r {
			val3 := val1 == nil
			if err = gobtools.EncodeBool(buf, val3); err != nil {
				return err
			}
			if !val3 {
				if err = (*val1).Encode(ctx, buf); err != nil {
					return err
				}
			}
			if err = gobtools.EncodeInterface(ctx, buf, val2); err != nil {
				return err
			}
		}
	}
	return err
}

func (r *ModuleStubDexJars) Decode(ctx gobtools.EncContext, buf *bytes.Reader) error {
	var err error

	var val1 int
	err = gobtools.DecodeInt(buf, &val1)
	if err != nil {
		return err
	}
	if val1 != -1 {
		(*r) = make(map[*HiddenAPIScope]android.Path, val1)
		for val2 := 0; val2 < int(val1); val2++ {
			var val3 *HiddenAPIScope
			var val4 android.Path
			var val6 bool
			if err = gobtools.DecodeBool(buf, &val6); err != nil {
				return err
			}
			if !val6 {
				var val5 HiddenAPIScope
				if err = val5.Decode(ctx, buf); err != nil {
					return err
				}
				val3 = &val5
			}
			if val9, err := gobtools.DecodeInterface(ctx, buf); err != nil {
				return err
			} else if val9 == nil {
				val4 = nil
			} else {
				val4 = val9.(android.Path)
			}
			(*r)[val3] = val4
		}
	}

	return err
}

var ModuleStubDexJarsGobRegId int16

func (r ModuleStubDexJars) GetTypeId() int16 {
	return ModuleStubDexJarsGobRegId
}

func (r HiddenAPIPropertyInfo) Encode(ctx gobtools.EncContext, buf *bytes.Buffer) error {
	var err error

	if r.FlagFilesByCategory == nil {
		if err = gobtools.EncodeInt(buf, -1); err != nil {
			return err
		}
	} else {
		if err = gobtools.EncodeInt(buf, len(r.FlagFilesByCategory)); err != nil {
			return err
		}
		for val1, val2 := range r.FlagFilesByCategory {
			if err = gobtools.EncodeInt(buf, int(val1)); err != nil {
				return err
			}
			if val2 == nil {
				if err = gobtools.EncodeInt(buf, -1); err != nil {
					return err
				}
			} else {
				if err = gobtools.EncodeInt(buf, len(val2)); err != nil {
					return err
				}
				for val3 := 0; val3 < len(val2); val3++ {
					if err = gobtools.EncodeInterface(ctx, buf, val2[val3]); err != nil {
						return err
					}
				}
			}
		}
	}

	if r.PackagePrefixes == nil {
		if err = gobtools.EncodeInt(buf, -1); err != nil {
			return err
		}
	} else {
		if err = gobtools.EncodeInt(buf, len(r.PackagePrefixes)); err != nil {
			return err
		}
		for val4 := 0; val4 < len(r.PackagePrefixes); val4++ {
			if err = gobtools.EncodeString(buf, r.PackagePrefixes[val4]); err != nil {
				return err
			}
		}
	}

	if r.SinglePackages == nil {
		if err = gobtools.EncodeInt(buf, -1); err != nil {
			return err
		}
	} else {
		if err = gobtools.EncodeInt(buf, len(r.SinglePackages)); err != nil {
			return err
		}
		for val5 := 0; val5 < len(r.SinglePackages); val5++ {
			if err = gobtools.EncodeString(buf, r.SinglePackages[val5]); err != nil {
				return err
			}
		}
	}

	if r.SplitPackages == nil {
		if err = gobtools.EncodeInt(buf, -1); err != nil {
			return err
		}
	} else {
		if err = gobtools.EncodeInt(buf, len(r.SplitPackages)); err != nil {
			return err
		}
		for val6 := 0; val6 < len(r.SplitPackages); val6++ {
			if err = gobtools.EncodeString(buf, r.SplitPackages[val6]); err != nil {
				return err
			}
		}
	}
	return err
}

func (r *HiddenAPIPropertyInfo) Decode(ctx gobtools.EncContext, buf *bytes.Reader) error {
	var err error

	var val2 int
	err = gobtools.DecodeInt(buf, &val2)
	if err != nil {
		return err
	}
	if val2 != -1 {
		r.FlagFilesByCategory = make(map[hiddenAPIFlagFileCategory]android.Paths, val2)
		for val3 := 0; val3 < int(val2); val3++ {
			var val4 hiddenAPIFlagFileCategory
			var val5 android.Paths
			var val7 int
			err = gobtools.DecodeInt(buf, &val7)
			if err != nil {
				return err
			}
			val4 = hiddenAPIFlagFileCategory(val7)
			var val11 int
			err = gobtools.DecodeInt(buf, &val11)
			if err != nil {
				return err
			}
			if val11 != -1 {
				val5 = make([]android.Path, val11)
				for val12 := 0; val12 < int(val11); val12++ {
					if val14, err := gobtools.DecodeInterface(ctx, buf); err != nil {
						return err
					} else if val14 == nil {
						val5[val12] = nil
					} else {
						val5[val12] = val14.(android.Path)
					}
				}
			}
			r.FlagFilesByCategory[val4] = val5
		}
	}

	var val16 int
	err = gobtools.DecodeInt(buf, &val16)
	if err != nil {
		return err
	}
	if val16 != -1 {
		r.PackagePrefixes = make([]string, val16)
		for val17 := 0; val17 < int(val16); val17++ {
			err = gobtools.DecodeString(buf, &r.PackagePrefixes[val17])
			if err != nil {
				return err
			}
		}
	}

	var val20 int
	err = gobtools.DecodeInt(buf, &val20)
	if err != nil {
		return err
	}
	if val20 != -1 {
		r.SinglePackages = make([]string, val20)
		for val21 := 0; val21 < int(val20); val21++ {
			err = gobtools.DecodeString(buf, &r.SinglePackages[val21])
			if err != nil {
				return err
			}
		}
	}

	var val24 int
	err = gobtools.DecodeInt(buf, &val24)
	if err != nil {
		return err
	}
	if val24 != -1 {
		r.SplitPackages = make([]string, val24)
		for val25 := 0; val25 < int(val24); val25++ {
			err = gobtools.DecodeString(buf, &r.SplitPackages[val25])
			if err != nil {
				return err
			}
		}
	}

	return err
}

var HiddenAPIPropertyInfoGobRegId int16

func (r HiddenAPIPropertyInfo) GetTypeId() int16 {
	return HiddenAPIPropertyInfoGobRegId
}

func (r HiddenAPIFlagOutput) Encode(ctx gobtools.EncContext, buf *bytes.Buffer) error {
	var err error

	if err = gobtools.EncodeInterface(ctx, buf, r.AnnotationFlagsPath); err != nil {
		return err
	}

	if err = gobtools.EncodeInterface(ctx, buf, r.MetadataPath); err != nil {
		return err
	}

	if err = gobtools.EncodeInterface(ctx, buf, r.IndexPath); err != nil {
		return err
	}

	if err = gobtools.EncodeInterface(ctx, buf, r.StubFlagsPath); err != nil {
		return err
	}

	if err = gobtools.EncodeInterface(ctx, buf, r.AllFlagsPath); err != nil {
		return err
	}

	if err = gobtools.EncodeInterface(ctx, buf, r.SignaturePatternsPath); err != nil {
		return err
	}

	if err = gobtools.EncodeInterface(ctx, buf, r.FilteredStubFlagsPath); err != nil {
		return err
	}

	if err = gobtools.EncodeInterface(ctx, buf, r.FilteredFlagsPath); err != nil {
		return err
	}
	return err
}

func (r *HiddenAPIFlagOutput) Decode(ctx gobtools.EncContext, buf *bytes.Reader) error {
	var err error

	if val2, err := gobtools.DecodeInterface(ctx, buf); err != nil {
		return err
	} else if val2 == nil {
		r.AnnotationFlagsPath = nil
	} else {
		r.AnnotationFlagsPath = val2.(android.Path)
	}

	if val4, err := gobtools.DecodeInterface(ctx, buf); err != nil {
		return err
	} else if val4 == nil {
		r.MetadataPath = nil
	} else {
		r.MetadataPath = val4.(android.Path)
	}

	if val6, err := gobtools.DecodeInterface(ctx, buf); err != nil {
		return err
	} else if val6 == nil {
		r.IndexPath = nil
	} else {
		r.IndexPath = val6.(android.Path)
	}

	if val8, err := gobtools.DecodeInterface(ctx, buf); err != nil {
		return err
	} else if val8 == nil {
		r.StubFlagsPath = nil
	} else {
		r.StubFlagsPath = val8.(android.Path)
	}

	if val10, err := gobtools.DecodeInterface(ctx, buf); err != nil {
		return err
	} else if val10 == nil {
		r.AllFlagsPath = nil
	} else {
		r.AllFlagsPath = val10.(android.Path)
	}

	if val12, err := gobtools.DecodeInterface(ctx, buf); err != nil {
		return err
	} else if val12 == nil {
		r.SignaturePatternsPath = nil
	} else {
		r.SignaturePatternsPath = val12.(android.Path)
	}

	if val14, err := gobtools.DecodeInterface(ctx, buf); err != nil {
		return err
	} else if val14 == nil {
		r.FilteredStubFlagsPath = nil
	} else {
		r.FilteredStubFlagsPath = val14.(android.Path)
	}

	if val16, err := gobtools.DecodeInterface(ctx, buf); err != nil {
		return err
	} else if val16 == nil {
		r.FilteredFlagsPath = nil
	} else {
		r.FilteredFlagsPath = val16.(android.Path)
	}

	return err
}

var HiddenAPIFlagOutputGobRegId int16

func (r HiddenAPIFlagOutput) GetTypeId() int16 {
	return HiddenAPIFlagOutputGobRegId
}

func (r SignatureCsvSubset) Encode(ctx gobtools.EncContext, buf *bytes.Buffer) error {
	var err error

	if err = gobtools.EncodeInterface(ctx, buf, r.CsvFile); err != nil {
		return err
	}

	if err = gobtools.EncodeInterface(ctx, buf, r.SignaturePatternsFile); err != nil {
		return err
	}
	return err
}

func (r *SignatureCsvSubset) Decode(ctx gobtools.EncContext, buf *bytes.Reader) error {
	var err error

	if val2, err := gobtools.DecodeInterface(ctx, buf); err != nil {
		return err
	} else if val2 == nil {
		r.CsvFile = nil
	} else {
		r.CsvFile = val2.(android.Path)
	}

	if val4, err := gobtools.DecodeInterface(ctx, buf); err != nil {
		return err
	} else if val4 == nil {
		r.SignaturePatternsFile = nil
	} else {
		r.SignaturePatternsFile = val4.(android.Path)
	}

	return err
}

var SignatureCsvSubsetGobRegId int16

func (r SignatureCsvSubset) GetTypeId() int16 {
	return SignatureCsvSubsetGobRegId
}

func (r SignatureCsvSubsets) Encode(ctx gobtools.EncContext, buf *bytes.Buffer) error {
	var err error

	if r == nil {
		if err = gobtools.EncodeInt(buf, -1); err != nil {
			return err
		}
	} else {
		if err = gobtools.EncodeInt(buf, len(r)); err != nil {
			return err
		}
		for val1 := 0; val1 < len(r); val1++ {
			if err = r[val1].Encode(ctx, buf); err != nil {
				return err
			}
		}
	}
	return err
}

func (r *SignatureCsvSubsets) Decode(ctx gobtools.EncContext, buf *bytes.Reader) error {
	var err error

	var val2 int
	err = gobtools.DecodeInt(buf, &val2)
	if err != nil {
		return err
	}
	if val2 != -1 {
		(*r) = make([]SignatureCsvSubset, val2)
		for val3 := 0; val3 < int(val2); val3++ {
			if err = (*r)[val3].Decode(ctx, buf); err != nil {
				return err
			}
		}
	}

	return err
}

var SignatureCsvSubsetsGobRegId int16

func (r SignatureCsvSubsets) GetTypeId() int16 {
	return SignatureCsvSubsetsGobRegId
}
