// Code generated by go run gob_gen.go; DO NOT EDIT.

package java

import (
	"android/soong/android"
	"bytes"
	"github.com/google/blueprint/gobtools"
)

func init() {
	HiddenAPIPropertyInfoGobRegId = gobtools.RegisterType(func() gobtools.CustomDec { return new(HiddenAPIPropertyInfo) })
}

func (r HiddenAPIPropertyInfo) Encode(ctx gobtools.EncContext, buf *bytes.Buffer) error {
	var err error

	if r.FlagFilesByCategory == nil {
		if err = gobtools.EncodeInt(buf, -1); err != nil {
			return err
		}
	} else {
		if err = gobtools.EncodeInt(buf, len(r.FlagFilesByCategory)); err != nil {
			return err
		}
		for k, v := range r.FlagFilesByCategory {
			if err = gobtools.EncodeInt(buf, int(k)); err != nil {
				return err
			}
			if v == nil {
				if err = gobtools.EncodeInt(buf, -1); err != nil {
					return err
				}
			} else {
				if err = gobtools.EncodeInt(buf, len(v)); err != nil {
					return err
				}
				for val1 := 0; val1 < len(v); val1++ {
					if err = gobtools.EncodeInterface(ctx, buf, v[val1]); err != nil {
						return err
					}
				}
			}
		}
	}

	if r.PackagePrefixes == nil {
		if err = gobtools.EncodeInt(buf, -1); err != nil {
			return err
		}
	} else {
		if err = gobtools.EncodeInt(buf, len(r.PackagePrefixes)); err != nil {
			return err
		}
		for val2 := 0; val2 < len(r.PackagePrefixes); val2++ {
			if err = gobtools.EncodeString(buf, r.PackagePrefixes[val2]); err != nil {
				return err
			}
		}
	}

	if r.SinglePackages == nil {
		if err = gobtools.EncodeInt(buf, -1); err != nil {
			return err
		}
	} else {
		if err = gobtools.EncodeInt(buf, len(r.SinglePackages)); err != nil {
			return err
		}
		for val3 := 0; val3 < len(r.SinglePackages); val3++ {
			if err = gobtools.EncodeString(buf, r.SinglePackages[val3]); err != nil {
				return err
			}
		}
	}

	if r.SplitPackages == nil {
		if err = gobtools.EncodeInt(buf, -1); err != nil {
			return err
		}
	} else {
		if err = gobtools.EncodeInt(buf, len(r.SplitPackages)); err != nil {
			return err
		}
		for val4 := 0; val4 < len(r.SplitPackages); val4++ {
			if err = gobtools.EncodeString(buf, r.SplitPackages[val4]); err != nil {
				return err
			}
		}
	}
	return err
}

func (r *HiddenAPIPropertyInfo) Decode(ctx gobtools.EncContext, buf *bytes.Reader) error {
	var err error

	var val2 int
	err = gobtools.DecodeInt(buf, &val2)
	if err != nil {
		return err
	}
	if val2 != -1 {
		r.FlagFilesByCategory = make(map[hiddenAPIFlagFileCategory]android.Paths, val2)
		for val3 := 0; val3 < int(val2); val3++ {
			var k hiddenAPIFlagFileCategory
			var v android.Paths
			var val5 int
			err = gobtools.DecodeInt(buf, &val5)
			if err != nil {
				return err
			}
			k = hiddenAPIFlagFileCategory(val5)
			var val9 int
			err = gobtools.DecodeInt(buf, &val9)
			if err != nil {
				return err
			}
			if val9 != -1 {
				v = make([]android.Path, val9)
				for val10 := 0; val10 < int(val9); val10++ {
					if val12, err := gobtools.DecodeInterface(ctx, buf); err != nil {
						return err
					} else if val12 == nil {
						v[val10] = nil
					} else {
						v[val10] = val12.(android.Path)
					}
				}
			}
			r.FlagFilesByCategory[k] = v
		}
	}

	var val14 int
	err = gobtools.DecodeInt(buf, &val14)
	if err != nil {
		return err
	}
	if val14 != -1 {
		r.PackagePrefixes = make([]string, val14)
		for val15 := 0; val15 < int(val14); val15++ {
			err = gobtools.DecodeString(buf, &r.PackagePrefixes[val15])
			if err != nil {
				return err
			}
		}
	}

	var val18 int
	err = gobtools.DecodeInt(buf, &val18)
	if err != nil {
		return err
	}
	if val18 != -1 {
		r.SinglePackages = make([]string, val18)
		for val19 := 0; val19 < int(val18); val19++ {
			err = gobtools.DecodeString(buf, &r.SinglePackages[val19])
			if err != nil {
				return err
			}
		}
	}

	var val22 int
	err = gobtools.DecodeInt(buf, &val22)
	if err != nil {
		return err
	}
	if val22 != -1 {
		r.SplitPackages = make([]string, val22)
		for val23 := 0; val23 < int(val22); val23++ {
			err = gobtools.DecodeString(buf, &r.SplitPackages[val23])
			if err != nil {
				return err
			}
		}
	}

	return err
}

var HiddenAPIPropertyInfoGobRegId int16

func (r HiddenAPIPropertyInfo) GetTypeId() int16 {
	return HiddenAPIPropertyInfoGobRegId
}
