// Code generated by go run gob_gen.go; DO NOT EDIT.

package java

import (
	"android/soong/android"
	"bytes"
	"github.com/google/blueprint/gobtools"
)

func init() {
	MonolithicHiddenAPIInfoGobRegId = gobtools.RegisterType(func() gobtools.CustomDec { return new(MonolithicHiddenAPIInfo) })
}

func (r MonolithicHiddenAPIInfo) Encode(ctx gobtools.EncContext, buf *bytes.Buffer) error {
	var err error

	if r.FlagsFilesByCategory == nil {
		if err = gobtools.EncodeInt(buf, -1); err != nil {
			return err
		}
	} else {
		if err = gobtools.EncodeInt(buf, len(r.FlagsFilesByCategory)); err != nil {
			return err
		}
		for val1, val2 := range r.FlagsFilesByCategory {
			if err = gobtools.EncodeInt(buf, int(val1)); err != nil {
				return err
			}
			if val2 == nil {
				if err = gobtools.EncodeInt(buf, -1); err != nil {
					return err
				}
			} else {
				if err = gobtools.EncodeInt(buf, len(val2)); err != nil {
					return err
				}
				for val3 := 0; val3 < len(val2); val3++ {
					if err = gobtools.EncodeInterface(ctx, buf, val2[val3]); err != nil {
						return err
					}
				}
			}
		}
	}

	if r.AnnotationFlagsPaths == nil {
		if err = gobtools.EncodeInt(buf, -1); err != nil {
			return err
		}
	} else {
		if err = gobtools.EncodeInt(buf, len(r.AnnotationFlagsPaths)); err != nil {
			return err
		}
		for val4 := 0; val4 < len(r.AnnotationFlagsPaths); val4++ {
			if err = gobtools.EncodeInterface(ctx, buf, r.AnnotationFlagsPaths[val4]); err != nil {
				return err
			}
		}
	}

	if r.MetadataPaths == nil {
		if err = gobtools.EncodeInt(buf, -1); err != nil {
			return err
		}
	} else {
		if err = gobtools.EncodeInt(buf, len(r.MetadataPaths)); err != nil {
			return err
		}
		for val5 := 0; val5 < len(r.MetadataPaths); val5++ {
			if err = gobtools.EncodeInterface(ctx, buf, r.MetadataPaths[val5]); err != nil {
				return err
			}
		}
	}

	if r.IndexPaths == nil {
		if err = gobtools.EncodeInt(buf, -1); err != nil {
			return err
		}
	} else {
		if err = gobtools.EncodeInt(buf, len(r.IndexPaths)); err != nil {
			return err
		}
		for val6 := 0; val6 < len(r.IndexPaths); val6++ {
			if err = gobtools.EncodeInterface(ctx, buf, r.IndexPaths[val6]); err != nil {
				return err
			}
		}
	}

	if r.StubFlagSubsets == nil {
		if err = gobtools.EncodeInt(buf, -1); err != nil {
			return err
		}
	} else {
		if err = gobtools.EncodeInt(buf, len(r.StubFlagSubsets)); err != nil {
			return err
		}
		for val7 := 0; val7 < len(r.StubFlagSubsets); val7++ {
			if err = r.StubFlagSubsets[val7].Encode(ctx, buf); err != nil {
				return err
			}
		}
	}

	if r.FlagSubsets == nil {
		if err = gobtools.EncodeInt(buf, -1); err != nil {
			return err
		}
	} else {
		if err = gobtools.EncodeInt(buf, len(r.FlagSubsets)); err != nil {
			return err
		}
		for val8 := 0; val8 < len(r.FlagSubsets); val8++ {
			if err = r.FlagSubsets[val8].Encode(ctx, buf); err != nil {
				return err
			}
		}
	}

	if r.ClassesJars == nil {
		if err = gobtools.EncodeInt(buf, -1); err != nil {
			return err
		}
	} else {
		if err = gobtools.EncodeInt(buf, len(r.ClassesJars)); err != nil {
			return err
		}
		for val9 := 0; val9 < len(r.ClassesJars); val9++ {
			if err = gobtools.EncodeInterface(ctx, buf, r.ClassesJars[val9]); err != nil {
				return err
			}
		}
	}
	return err
}

func (r *MonolithicHiddenAPIInfo) Decode(ctx gobtools.EncContext, buf *bytes.Reader) error {
	var err error

	var val2 int
	err = gobtools.DecodeInt(buf, &val2)
	if err != nil {
		return err
	}
	if val2 != -1 {
		r.FlagsFilesByCategory = make(map[hiddenAPIFlagFileCategory]android.Paths, val2)
		for val3 := 0; val3 < int(val2); val3++ {
			var val4 hiddenAPIFlagFileCategory
			var val5 android.Paths
			var val7 int
			err = gobtools.DecodeInt(buf, &val7)
			if err != nil {
				return err
			}
			val4 = hiddenAPIFlagFileCategory(val7)
			var val11 int
			err = gobtools.DecodeInt(buf, &val11)
			if err != nil {
				return err
			}
			if val11 != -1 {
				val5 = make([]android.Path, val11)
				for val12 := 0; val12 < int(val11); val12++ {
					if val14, err := gobtools.DecodeInterface(ctx, buf); err != nil {
						return err
					} else if val14 == nil {
						val5[val12] = nil
					} else {
						val5[val12] = val14.(android.Path)
					}
				}
			}
			r.FlagsFilesByCategory[val4] = val5
		}
	}

	var val17 int
	err = gobtools.DecodeInt(buf, &val17)
	if err != nil {
		return err
	}
	if val17 != -1 {
		r.AnnotationFlagsPaths = make([]android.Path, val17)
		for val18 := 0; val18 < int(val17); val18++ {
			if val20, err := gobtools.DecodeInterface(ctx, buf); err != nil {
				return err
			} else if val20 == nil {
				r.AnnotationFlagsPaths[val18] = nil
			} else {
				r.AnnotationFlagsPaths[val18] = val20.(android.Path)
			}
		}
	}

	var val23 int
	err = gobtools.DecodeInt(buf, &val23)
	if err != nil {
		return err
	}
	if val23 != -1 {
		r.MetadataPaths = make([]android.Path, val23)
		for val24 := 0; val24 < int(val23); val24++ {
			if val26, err := gobtools.DecodeInterface(ctx, buf); err != nil {
				return err
			} else if val26 == nil {
				r.MetadataPaths[val24] = nil
			} else {
				r.MetadataPaths[val24] = val26.(android.Path)
			}
		}
	}

	var val29 int
	err = gobtools.DecodeInt(buf, &val29)
	if err != nil {
		return err
	}
	if val29 != -1 {
		r.IndexPaths = make([]android.Path, val29)
		for val30 := 0; val30 < int(val29); val30++ {
			if val32, err := gobtools.DecodeInterface(ctx, buf); err != nil {
				return err
			} else if val32 == nil {
				r.IndexPaths[val30] = nil
			} else {
				r.IndexPaths[val30] = val32.(android.Path)
			}
		}
	}

	var val35 int
	err = gobtools.DecodeInt(buf, &val35)
	if err != nil {
		return err
	}
	if val35 != -1 {
		r.StubFlagSubsets = make([]SignatureCsvSubset, val35)
		for val36 := 0; val36 < int(val35); val36++ {
			if err = r.StubFlagSubsets[val36].Decode(ctx, buf); err != nil {
				return err
			}
		}
	}

	var val40 int
	err = gobtools.DecodeInt(buf, &val40)
	if err != nil {
		return err
	}
	if val40 != -1 {
		r.FlagSubsets = make([]SignatureCsvSubset, val40)
		for val41 := 0; val41 < int(val40); val41++ {
			if err = r.FlagSubsets[val41].Decode(ctx, buf); err != nil {
				return err
			}
		}
	}

	var val45 int
	err = gobtools.DecodeInt(buf, &val45)
	if err != nil {
		return err
	}
	if val45 != -1 {
		r.ClassesJars = make([]android.Path, val45)
		for val46 := 0; val46 < int(val45); val46++ {
			if val48, err := gobtools.DecodeInterface(ctx, buf); err != nil {
				return err
			} else if val48 == nil {
				r.ClassesJars[val46] = nil
			} else {
				r.ClassesJars[val46] = val48.(android.Path)
			}
		}
	}

	return err
}

var MonolithicHiddenAPIInfoGobRegId int16

func (r MonolithicHiddenAPIInfo) GetTypeId() int16 {
	return MonolithicHiddenAPIInfoGobRegId
}
