// Code generated by go run gob_gen.go; DO NOT EDIT.

package java

import (
	"android/soong/android"
	"android/soong/dexpreopt"
	"bytes"
	"github.com/google/blueprint/gobtools"
)

func init() {
	ProguardSpecInfoGobRegId = gobtools.RegisterType(func() gobtools.CustomDec { return new(ProguardSpecInfo) })
	AndroidLibraryDependencyInfoGobRegId = gobtools.RegisterType(func() gobtools.CustomDec { return new(AndroidLibraryDependencyInfo) })
	UsesLibraryDependencyInfoGobRegId = gobtools.RegisterType(func() gobtools.CustomDec { return new(UsesLibraryDependencyInfo) })
	ProvidesUsesLibInfoGobRegId = gobtools.RegisterType(func() gobtools.CustomDec { return new(ProvidesUsesLibInfo) })
	ModuleWithSdkDepInfoGobRegId = gobtools.RegisterType(func() gobtools.CustomDec { return new(ModuleWithSdkDepInfo) })
	ApexDependencyInfoGobRegId = gobtools.RegisterType(func() gobtools.CustomDec { return new(ApexDependencyInfo) })
	JavaInfoGobRegId = gobtools.RegisterType(func() gobtools.CustomDec { return new(JavaInfo) })
	DexpreopterInfoGobRegId = gobtools.RegisterType(func() gobtools.CustomDec { return new(DexpreopterInfo) })
	JavaLibraryInfoGobRegId = gobtools.RegisterType(func() gobtools.CustomDec { return new(JavaLibraryInfo) })
	JavaDexImportInfoGobRegId = gobtools.RegisterType(func() gobtools.CustomDec { return new(JavaDexImportInfo) })
	SyspropPublicStubInfoGobRegId = gobtools.RegisterType(func() gobtools.CustomDec { return new(SyspropPublicStubInfo) })
	jniLibGobRegId = gobtools.RegisterType(func() gobtools.CustomDec { return new(jniLib) })
	JavaTestInfoGobRegId = gobtools.RegisterType(func() gobtools.CustomDec { return new(JavaTestInfo) })
	JavaApiImportInfoGobRegId = gobtools.RegisterType(func() gobtools.CustomDec { return new(JavaApiImportInfo) })
}

func (r ProguardSpecInfo) Encode(ctx gobtools.EncContext, buf *bytes.Buffer) error {
	var err error

	if err = gobtools.EncodeBool(buf, r.Export_proguard_flags_files); err != nil {
		return err
	}

	if err = r.ProguardFlagsFiles.EncodeInterface(ctx, buf); err != nil {
		return err
	}

	if err = r.UnconditionallyExportedProguardFlags.EncodeInterface(ctx, buf); err != nil {
		return err
	}
	return err
}

func (r *ProguardSpecInfo) Decode(ctx gobtools.EncContext, buf *bytes.Reader) error {
	var err error

	err = gobtools.DecodeBool(buf, &r.Export_proguard_flags_files)
	if err != nil {
		return err
	}

	if err = r.ProguardFlagsFiles.DecodeInterface(ctx, buf); err != nil {
		return err
	}

	if err = r.UnconditionallyExportedProguardFlags.DecodeInterface(ctx, buf); err != nil {
		return err
	}

	return err
}

var ProguardSpecInfoGobRegId int16

func (r ProguardSpecInfo) GetTypeId() int16 {
	return ProguardSpecInfoGobRegId
}

func (r AndroidLibraryDependencyInfo) Encode(ctx gobtools.EncContext, buf *bytes.Buffer) error {
	var err error

	if err = gobtools.EncodeInterface(ctx, buf, r.ExportPackage); err != nil {
		return err
	}

	if err = r.ResourcesNodeDepSet.Encode(ctx, buf); err != nil {
		return err
	}

	if err = r.RRODirsDepSet.Encode(ctx, buf); err != nil {
		return err
	}

	if err = r.ManifestsDepSet.EncodeInterface(ctx, buf); err != nil {
		return err
	}
	return err
}

func (r *AndroidLibraryDependencyInfo) Decode(ctx gobtools.EncContext, buf *bytes.Reader) error {
	var err error

	if val2, err := gobtools.DecodeInterface(ctx, buf); err != nil {
		return err
	} else if val2 == nil {
		r.ExportPackage = nil
	} else {
		r.ExportPackage = val2.(android.Path)
	}

	if err = r.ResourcesNodeDepSet.Decode(ctx, buf); err != nil {
		return err
	}

	if err = r.RRODirsDepSet.Decode(ctx, buf); err != nil {
		return err
	}

	if err = r.ManifestsDepSet.DecodeInterface(ctx, buf); err != nil {
		return err
	}

	return err
}

var AndroidLibraryDependencyInfoGobRegId int16

func (r AndroidLibraryDependencyInfo) GetTypeId() int16 {
	return AndroidLibraryDependencyInfoGobRegId
}

func (r UsesLibraryDependencyInfo) Encode(ctx gobtools.EncContext, buf *bytes.Buffer) error {
	var err error

	if err = gobtools.EncodeInterface(ctx, buf, r.DexJarInstallPath); err != nil {
		return err
	}

	if r.ClassLoaderContexts == nil {
		if err = gobtools.EncodeInt(buf, -1); err != nil {
			return err
		}
	} else {
		if err = gobtools.EncodeInt(buf, len(r.ClassLoaderContexts)); err != nil {
			return err
		}
		for val1, val2 := range r.ClassLoaderContexts {
			if err = gobtools.EncodeInt(buf, val1); err != nil {
				return err
			}
			if val2 == nil {
				if err = gobtools.EncodeInt(buf, -1); err != nil {
					return err
				}
			} else {
				if err = gobtools.EncodeInt(buf, len(val2)); err != nil {
					return err
				}
				for val3 := 0; val3 < len(val2); val3++ {
					val4 := val2[val3] == nil
					if err = gobtools.EncodeBool(buf, val4); err != nil {
						return err
					}
					if !val4 {
						if err = (*val2[val3]).Encode(ctx, buf); err != nil {
							return err
						}
					}
				}
			}
		}
	}
	return err
}

func (r *UsesLibraryDependencyInfo) Decode(ctx gobtools.EncContext, buf *bytes.Reader) error {
	var err error

	if val2, err := gobtools.DecodeInterface(ctx, buf); err != nil {
		return err
	} else if val2 == nil {
		r.DexJarInstallPath = nil
	} else {
		r.DexJarInstallPath = val2.(android.Path)
	}

	var val4 int
	err = gobtools.DecodeInt(buf, &val4)
	if err != nil {
		return err
	}
	if val4 != -1 {
		r.ClassLoaderContexts = make(map[int][]*dexpreopt.ClassLoaderContext, val4)
		for val5 := 0; val5 < int(val4); val5++ {
			var val6 int
			var val7 []*dexpreopt.ClassLoaderContext
			err = gobtools.DecodeInt(buf, &val6)
			if err != nil {
				return err
			}
			var val10 int
			err = gobtools.DecodeInt(buf, &val10)
			if err != nil {
				return err
			}
			if val10 != -1 {
				val7 = make([]*dexpreopt.ClassLoaderContext, val10)
				for val11 := 0; val11 < int(val10); val11++ {
					var val13 bool
					if err = gobtools.DecodeBool(buf, &val13); err != nil {
						return err
					}
					if !val13 {
						var val12 dexpreopt.ClassLoaderContext
						if err = val12.Decode(ctx, buf); err != nil {
							return err
						}
						val7[val11] = &val12
					}
				}
			}
			r.ClassLoaderContexts[val6] = val7
		}
	}

	return err
}

var UsesLibraryDependencyInfoGobRegId int16

func (r UsesLibraryDependencyInfo) GetTypeId() int16 {
	return UsesLibraryDependencyInfoGobRegId
}

func (r ProvidesUsesLibInfo) Encode(ctx gobtools.EncContext, buf *bytes.Buffer) error {
	var err error

	val1 := r.ProvidesUsesLib == nil
	if err = gobtools.EncodeBool(buf, val1); err != nil {
		return err
	}
	if !val1 {
		if err = gobtools.EncodeString(buf, (*r.ProvidesUsesLib)); err != nil {
			return err
		}
	}
	return err
}

func (r *ProvidesUsesLibInfo) Decode(ctx gobtools.EncContext, buf *bytes.Reader) error {
	var err error

	var val2 bool
	if err = gobtools.DecodeBool(buf, &val2); err != nil {
		return err
	}
	if !val2 {
		var val1 string
		err = gobtools.DecodeString(buf, &val1)
		if err != nil {
			return err
		}
		r.ProvidesUsesLib = &val1
	}

	return err
}

var ProvidesUsesLibInfoGobRegId int16

func (r ProvidesUsesLibInfo) GetTypeId() int16 {
	return ProvidesUsesLibInfoGobRegId
}

func (r ModuleWithSdkDepInfo) Encode(ctx gobtools.EncContext, buf *bytes.Buffer) error {
	var err error

	if err = gobtools.EncodeInt(buf, int(r.SdkLinkType)); err != nil {
		return err
	}

	if err = gobtools.EncodeBool(buf, r.Stubs); err != nil {
		return err
	}
	return err
}

func (r *ModuleWithSdkDepInfo) Decode(ctx gobtools.EncContext, buf *bytes.Reader) error {
	var err error

	var val2 int
	err = gobtools.DecodeInt(buf, &val2)
	if err != nil {
		return err
	}
	r.SdkLinkType = sdkLinkType(val2)

	err = gobtools.DecodeBool(buf, &r.Stubs)
	if err != nil {
		return err
	}

	return err
}

var ModuleWithSdkDepInfoGobRegId int16

func (r ModuleWithSdkDepInfo) GetTypeId() int16 {
	return ModuleWithSdkDepInfoGobRegId
}

func (r ApexDependencyInfo) Encode(ctx gobtools.EncContext, buf *bytes.Buffer) error {
	var err error

	if r.HeaderJars == nil {
		if err = gobtools.EncodeInt(buf, -1); err != nil {
			return err
		}
	} else {
		if err = gobtools.EncodeInt(buf, len(r.HeaderJars)); err != nil {
			return err
		}
		for val1 := 0; val1 < len(r.HeaderJars); val1++ {
			if err = gobtools.EncodeInterface(ctx, buf, r.HeaderJars[val1]); err != nil {
				return err
			}
		}
	}

	if r.ImplementationAndResourcesJars == nil {
		if err = gobtools.EncodeInt(buf, -1); err != nil {
			return err
		}
	} else {
		if err = gobtools.EncodeInt(buf, len(r.ImplementationAndResourcesJars)); err != nil {
			return err
		}
		for val2 := 0; val2 < len(r.ImplementationAndResourcesJars); val2++ {
			if err = gobtools.EncodeInterface(ctx, buf, r.ImplementationAndResourcesJars[val2]); err != nil {
				return err
			}
		}
	}
	return err
}

func (r *ApexDependencyInfo) Decode(ctx gobtools.EncContext, buf *bytes.Reader) error {
	var err error

	var val3 int
	err = gobtools.DecodeInt(buf, &val3)
	if err != nil {
		return err
	}
	if val3 != -1 {
		r.HeaderJars = make([]android.Path, val3)
		for val4 := 0; val4 < int(val3); val4++ {
			if val6, err := gobtools.DecodeInterface(ctx, buf); err != nil {
				return err
			} else if val6 == nil {
				r.HeaderJars[val4] = nil
			} else {
				r.HeaderJars[val4] = val6.(android.Path)
			}
		}
	}

	var val9 int
	err = gobtools.DecodeInt(buf, &val9)
	if err != nil {
		return err
	}
	if val9 != -1 {
		r.ImplementationAndResourcesJars = make([]android.Path, val9)
		for val10 := 0; val10 < int(val9); val10++ {
			if val12, err := gobtools.DecodeInterface(ctx, buf); err != nil {
				return err
			} else if val12 == nil {
				r.ImplementationAndResourcesJars[val10] = nil
			} else {
				r.ImplementationAndResourcesJars[val10] = val12.(android.Path)
			}
		}
	}

	return err
}

var ApexDependencyInfoGobRegId int16

func (r ApexDependencyInfo) GetTypeId() int16 {
	return ApexDependencyInfoGobRegId
}

func (r JavaInfo) Encode(ctx gobtools.EncContext, buf *bytes.Buffer) error {
	var err error

	if r.HeaderJars == nil {
		if err = gobtools.EncodeInt(buf, -1); err != nil {
			return err
		}
	} else {
		if err = gobtools.EncodeInt(buf, len(r.HeaderJars)); err != nil {
			return err
		}
		for val1 := 0; val1 < len(r.HeaderJars); val1++ {
			if err = gobtools.EncodeInterface(ctx, buf, r.HeaderJars[val1]); err != nil {
				return err
			}
		}
	}

	if r.RepackagedHeaderJars == nil {
		if err = gobtools.EncodeInt(buf, -1); err != nil {
			return err
		}
	} else {
		if err = gobtools.EncodeInt(buf, len(r.RepackagedHeaderJars)); err != nil {
			return err
		}
		for val2 := 0; val2 < len(r.RepackagedHeaderJars); val2++ {
			if err = gobtools.EncodeInterface(ctx, buf, r.RepackagedHeaderJars[val2]); err != nil {
				return err
			}
		}
	}

	if r.LocalHeaderJarsPreJarjar == nil {
		if err = gobtools.EncodeInt(buf, -1); err != nil {
			return err
		}
	} else {
		if err = gobtools.EncodeInt(buf, len(r.LocalHeaderJarsPreJarjar)); err != nil {
			return err
		}
		for val3 := 0; val3 < len(r.LocalHeaderJarsPreJarjar); val3++ {
			if err = gobtools.EncodeInterface(ctx, buf, r.LocalHeaderJarsPreJarjar[val3]); err != nil {
				return err
			}
		}
	}

	if err = r.TransitiveLibsHeaderJarsForR8.EncodeInterface(ctx, buf); err != nil {
		return err
	}

	if err = r.TransitiveStaticLibsHeaderJarsForR8.EncodeInterface(ctx, buf); err != nil {
		return err
	}

	if err = r.TransitiveStaticLibsHeaderJars.EncodeInterface(ctx, buf); err != nil {
		return err
	}

	if err = r.TransitiveStaticLibsImplementationJars.EncodeInterface(ctx, buf); err != nil {
		return err
	}

	if err = r.TransitiveStaticLibsResourceJars.EncodeInterface(ctx, buf); err != nil {
		return err
	}

	if r.ImplementationAndResourcesJars == nil {
		if err = gobtools.EncodeInt(buf, -1); err != nil {
			return err
		}
	} else {
		if err = gobtools.EncodeInt(buf, len(r.ImplementationAndResourcesJars)); err != nil {
			return err
		}
		for val4 := 0; val4 < len(r.ImplementationAndResourcesJars); val4++ {
			if err = gobtools.EncodeInterface(ctx, buf, r.ImplementationAndResourcesJars[val4]); err != nil {
				return err
			}
		}
	}

	if r.ImplementationJars == nil {
		if err = gobtools.EncodeInt(buf, -1); err != nil {
			return err
		}
	} else {
		if err = gobtools.EncodeInt(buf, len(r.ImplementationJars)); err != nil {
			return err
		}
		for val5 := 0; val5 < len(r.ImplementationJars); val5++ {
			if err = gobtools.EncodeInterface(ctx, buf, r.ImplementationJars[val5]); err != nil {
				return err
			}
		}
	}

	if r.ResourceJars == nil {
		if err = gobtools.EncodeInt(buf, -1); err != nil {
			return err
		}
	} else {
		if err = gobtools.EncodeInt(buf, len(r.ResourceJars)); err != nil {
			return err
		}
		for val6 := 0; val6 < len(r.ResourceJars); val6++ {
			if err = gobtools.EncodeInterface(ctx, buf, r.ResourceJars[val6]); err != nil {
				return err
			}
		}
	}

	if r.LocalHeaderJars == nil {
		if err = gobtools.EncodeInt(buf, -1); err != nil {
			return err
		}
	} else {
		if err = gobtools.EncodeInt(buf, len(r.LocalHeaderJars)); err != nil {
			return err
		}
		for val7 := 0; val7 < len(r.LocalHeaderJars); val7++ {
			if err = gobtools.EncodeInterface(ctx, buf, r.LocalHeaderJars[val7]); err != nil {
				return err
			}
		}
	}

	if r.KotlinHeaderJars == nil {
		if err = gobtools.EncodeInt(buf, -1); err != nil {
			return err
		}
	} else {
		if err = gobtools.EncodeInt(buf, len(r.KotlinHeaderJars)); err != nil {
			return err
		}
		for val8 := 0; val8 < len(r.KotlinHeaderJars); val8++ {
			if err = gobtools.EncodeInterface(ctx, buf, r.KotlinHeaderJars[val8]); err != nil {
				return err
			}
		}
	}

	if r.AidlIncludeDirs == nil {
		if err = gobtools.EncodeInt(buf, -1); err != nil {
			return err
		}
	} else {
		if err = gobtools.EncodeInt(buf, len(r.AidlIncludeDirs)); err != nil {
			return err
		}
		for val9 := 0; val9 < len(r.AidlIncludeDirs); val9++ {
			if err = gobtools.EncodeInterface(ctx, buf, r.AidlIncludeDirs[val9]); err != nil {
				return err
			}
		}
	}

	if r.SrcJarArgs == nil {
		if err = gobtools.EncodeInt(buf, -1); err != nil {
			return err
		}
	} else {
		if err = gobtools.EncodeInt(buf, len(r.SrcJarArgs)); err != nil {
			return err
		}
		for val10 := 0; val10 < len(r.SrcJarArgs); val10++ {
			if err = gobtools.EncodeString(buf, r.SrcJarArgs[val10]); err != nil {
				return err
			}
		}
	}

	if r.SrcJarDeps == nil {
		if err = gobtools.EncodeInt(buf, -1); err != nil {
			return err
		}
	} else {
		if err = gobtools.EncodeInt(buf, len(r.SrcJarDeps)); err != nil {
			return err
		}
		for val11 := 0; val11 < len(r.SrcJarDeps); val11++ {
			if err = gobtools.EncodeInterface(ctx, buf, r.SrcJarDeps[val11]); err != nil {
				return err
			}
		}
	}

	if r.KSnapshotFiles == nil {
		if err = gobtools.EncodeInt(buf, -1); err != nil {
			return err
		}
	} else {
		if err = gobtools.EncodeInt(buf, len(r.KSnapshotFiles)); err != nil {
			return err
		}
		for val12, val13 := range r.KSnapshotFiles {
			if err = gobtools.EncodeString(buf, val12); err != nil {
				return err
			}
			if err = gobtools.EncodeInterface(ctx, buf, val13); err != nil {
				return err
			}
		}
	}

	if err = r.TransitiveSrcFiles.EncodeInterface(ctx, buf); err != nil {
		return err
	}

	if r.ExportedPlugins == nil {
		if err = gobtools.EncodeInt(buf, -1); err != nil {
			return err
		}
	} else {
		if err = gobtools.EncodeInt(buf, len(r.ExportedPlugins)); err != nil {
			return err
		}
		for val14 := 0; val14 < len(r.ExportedPlugins); val14++ {
			if err = gobtools.EncodeInterface(ctx, buf, r.ExportedPlugins[val14]); err != nil {
				return err
			}
		}
	}

	if r.ExportedPluginClasses == nil {
		if err = gobtools.EncodeInt(buf, -1); err != nil {
			return err
		}
	} else {
		if err = gobtools.EncodeInt(buf, len(r.ExportedPluginClasses)); err != nil {
			return err
		}
		for val15 := 0; val15 < len(r.ExportedPluginClasses); val15++ {
			if err = gobtools.EncodeString(buf, r.ExportedPluginClasses[val15]); err != nil {
				return err
			}
		}
	}

	if err = gobtools.EncodeBool(buf, r.ExportedPluginDisableTurbine); err != nil {
		return err
	}

	if err = r.JacocoInfo.Encode(ctx, buf); err != nil {
		return err
	}

	if err = gobtools.EncodeInt(buf, int(r.StubsLinkType)); err != nil {
		return err
	}

	if r.AconfigIntermediateCacheOutputPaths == nil {
		if err = gobtools.EncodeInt(buf, -1); err != nil {
			return err
		}
	} else {
		if err = gobtools.EncodeInt(buf, len(r.AconfigIntermediateCacheOutputPaths)); err != nil {
			return err
		}
		for val16 := 0; val16 < len(r.AconfigIntermediateCacheOutputPaths); val16++ {
			if err = gobtools.EncodeInterface(ctx, buf, r.AconfigIntermediateCacheOutputPaths[val16]); err != nil {
				return err
			}
		}
	}

	if err = r.SdkVersion.Encode(ctx, buf); err != nil {
		return err
	}

	if err = gobtools.EncodeInterface(ctx, buf, r.OutputFile); err != nil {
		return err
	}

	if r.ExtraOutputFiles == nil {
		if err = gobtools.EncodeInt(buf, -1); err != nil {
			return err
		}
	} else {
		if err = gobtools.EncodeInt(buf, len(r.ExtraOutputFiles)); err != nil {
			return err
		}
		for val17 := 0; val17 < len(r.ExtraOutputFiles); val17++ {
			if err = gobtools.EncodeInterface(ctx, buf, r.ExtraOutputFiles[val17]); err != nil {
				return err
			}
		}
	}

	val18 := r.AndroidLibraryDependencyInfo == nil
	if err = gobtools.EncodeBool(buf, val18); err != nil {
		return err
	}
	if !val18 {
		if err = (*r.AndroidLibraryDependencyInfo).Encode(ctx, buf); err != nil {
			return err
		}
	}

	val19 := r.UsesLibraryDependencyInfo == nil
	if err = gobtools.EncodeBool(buf, val19); err != nil {
		return err
	}
	if !val19 {
		if err = (*r.UsesLibraryDependencyInfo).Encode(ctx, buf); err != nil {
			return err
		}
	}

	val20 := r.ProvidesUsesLibInfo == nil
	if err = gobtools.EncodeBool(buf, val20); err != nil {
		return err
	}
	if !val20 {
		if err = (*r.ProvidesUsesLibInfo).Encode(ctx, buf); err != nil {
			return err
		}
	}

	if r.MissingOptionalUsesLibs == nil {
		if err = gobtools.EncodeInt(buf, -1); err != nil {
			return err
		}
	} else {
		if err = gobtools.EncodeInt(buf, len(r.MissingOptionalUsesLibs)); err != nil {
			return err
		}
		for val21 := 0; val21 < len(r.MissingOptionalUsesLibs); val21++ {
			if err = gobtools.EncodeString(buf, r.MissingOptionalUsesLibs[val21]); err != nil {
				return err
			}
		}
	}

	val22 := r.ModuleWithSdkDepInfo == nil
	if err = gobtools.EncodeBool(buf, val22); err != nil {
		return err
	}
	if !val22 {
		if err = (*r.ModuleWithSdkDepInfo).Encode(ctx, buf); err != nil {
			return err
		}
	}

	if err = r.DexJarFile.Encode(ctx, buf); err != nil {
		return err
	}

	if err = gobtools.EncodeInterface(ctx, buf, r.InstallFile); err != nil {
		return err
	}

	if err = r.BootDexJarPath.Encode(ctx, buf); err != nil {
		return err
	}

	if r.HiddenapiClassesJarPaths == nil {
		if err = gobtools.EncodeInt(buf, -1); err != nil {
			return err
		}
	} else {
		if err = gobtools.EncodeInt(buf, len(r.HiddenapiClassesJarPaths)); err != nil {
			return err
		}
		for val23 := 0; val23 < len(r.HiddenapiClassesJarPaths); val23++ {
			if err = gobtools.EncodeInterface(ctx, buf, r.HiddenapiClassesJarPaths[val23]); err != nil {
				return err
			}
		}
	}

	val24 := r.UncompressDexState == nil
	if err = gobtools.EncodeBool(buf, val24); err != nil {
		return err
	}
	if !val24 {
		if err = gobtools.EncodeBool(buf, (*r.UncompressDexState)); err != nil {
			return err
		}
	}

	if err = gobtools.EncodeBool(buf, r.Active); err != nil {
		return err
	}

	if err = gobtools.EncodeString(buf, r.BuiltInstalled); err != nil {
		return err
	}

	if err = gobtools.EncodeInterface(ctx, buf, r.ConfigPath); err != nil {
		return err
	}

	if r.LogtagsSrcs == nil {
		if err = gobtools.EncodeInt(buf, -1); err != nil {
			return err
		}
	} else {
		if err = gobtools.EncodeInt(buf, len(r.LogtagsSrcs)); err != nil {
			return err
		}
		for val25 := 0; val25 < len(r.LogtagsSrcs); val25++ {
			if err = gobtools.EncodeInterface(ctx, buf, r.LogtagsSrcs[val25]); err != nil {
				return err
			}
		}
	}

	if err = r.ProguardDictionary.Encode(ctx, buf); err != nil {
		return err
	}

	if err = r.ProguardUsageZip.Encode(ctx, buf); err != nil {
		return err
	}

	if r.LinterReports == nil {
		if err = gobtools.EncodeInt(buf, -1); err != nil {
			return err
		}
	} else {
		if err = gobtools.EncodeInt(buf, len(r.LinterReports)); err != nil {
			return err
		}
		for val26 := 0; val26 < len(r.LinterReports); val26++ {
			if err = gobtools.EncodeInterface(ctx, buf, r.LinterReports[val26]); err != nil {
				return err
			}
		}
	}

	if err = r.HostdexInstallFile.Encode(ctx, buf); err != nil {
		return err
	}

	if r.GeneratedSrcjars == nil {
		if err = gobtools.EncodeInt(buf, -1); err != nil {
			return err
		}
	} else {
		if err = gobtools.EncodeInt(buf, len(r.GeneratedSrcjars)); err != nil {
			return err
		}
		for val27 := 0; val27 < len(r.GeneratedSrcjars); val27++ {
			if err = gobtools.EncodeInterface(ctx, buf, r.GeneratedSrcjars[val27]); err != nil {
				return err
			}
		}
	}

	if err = gobtools.EncodeBool(buf, r.ProfileGuided); err != nil {
		return err
	}

	if err = gobtools.EncodeString(buf, r.Stem); err != nil {
		return err
	}

	if err = r.DexJarBuildPath.Encode(ctx, buf); err != nil {
		return err
	}

	val28 := r.DexpreopterInfo == nil
	if err = gobtools.EncodeBool(buf, val28); err != nil {
		return err
	}
	if !val28 {
		if err = (*r.DexpreopterInfo).Encode(ctx, buf); err != nil {
			return err
		}
	}

	if r.XrefJavaFiles == nil {
		if err = gobtools.EncodeInt(buf, -1); err != nil {
			return err
		}
	} else {
		if err = gobtools.EncodeInt(buf, len(r.XrefJavaFiles)); err != nil {
			return err
		}
		for val29 := 0; val29 < len(r.XrefJavaFiles); val29++ {
			if err = gobtools.EncodeInterface(ctx, buf, r.XrefJavaFiles[val29]); err != nil {
				return err
			}
		}
	}

	if r.XrefKotlinFiles == nil {
		if err = gobtools.EncodeInt(buf, -1); err != nil {
			return err
		}
	} else {
		if err = gobtools.EncodeInt(buf, len(r.XrefKotlinFiles)); err != nil {
			return err
		}
		for val30 := 0; val30 < len(r.XrefKotlinFiles); val30++ {
			if err = gobtools.EncodeInterface(ctx, buf, r.XrefKotlinFiles[val30]); err != nil {
				return err
			}
		}
	}

	if err = gobtools.EncodeBool(buf, r.HasOverrideMinSdkVersion); err != nil {
		return err
	}

	val31 := r.CompileDex == nil
	if err = gobtools.EncodeBool(buf, val31); err != nil {
		return err
	}
	if !val31 {
		if err = gobtools.EncodeBool(buf, (*r.CompileDex)); err != nil {
			return err
		}
	}

	if err = gobtools.EncodeString(buf, r.SystemModules); err != nil {
		return err
	}

	if err = gobtools.EncodeBool(buf, r.Installable); err != nil {
		return err
	}

	val32 := r.ApexDependencyInfo == nil
	if err = gobtools.EncodeBool(buf, val32); err != nil {
		return err
	}
	if !val32 {
		if err = (*r.ApexDependencyInfo).Encode(ctx, buf); err != nil {
			return err
		}
	}

	if err = r.MaxSdkVersion.Encode(ctx, buf); err != nil {
		return err
	}
	return err
}

func (r *JavaInfo) Decode(ctx gobtools.EncContext, buf *bytes.Reader) error {
	var err error

	var val3 int
	err = gobtools.DecodeInt(buf, &val3)
	if err != nil {
		return err
	}
	if val3 != -1 {
		r.HeaderJars = make([]android.Path, val3)
		for val4 := 0; val4 < int(val3); val4++ {
			if val6, err := gobtools.DecodeInterface(ctx, buf); err != nil {
				return err
			} else if val6 == nil {
				r.HeaderJars[val4] = nil
			} else {
				r.HeaderJars[val4] = val6.(android.Path)
			}
		}
	}

	var val9 int
	err = gobtools.DecodeInt(buf, &val9)
	if err != nil {
		return err
	}
	if val9 != -1 {
		r.RepackagedHeaderJars = make([]android.Path, val9)
		for val10 := 0; val10 < int(val9); val10++ {
			if val12, err := gobtools.DecodeInterface(ctx, buf); err != nil {
				return err
			} else if val12 == nil {
				r.RepackagedHeaderJars[val10] = nil
			} else {
				r.RepackagedHeaderJars[val10] = val12.(android.Path)
			}
		}
	}

	var val15 int
	err = gobtools.DecodeInt(buf, &val15)
	if err != nil {
		return err
	}
	if val15 != -1 {
		r.LocalHeaderJarsPreJarjar = make([]android.Path, val15)
		for val16 := 0; val16 < int(val15); val16++ {
			if val18, err := gobtools.DecodeInterface(ctx, buf); err != nil {
				return err
			} else if val18 == nil {
				r.LocalHeaderJarsPreJarjar[val16] = nil
			} else {
				r.LocalHeaderJarsPreJarjar[val16] = val18.(android.Path)
			}
		}
	}

	if err = r.TransitiveLibsHeaderJarsForR8.DecodeInterface(ctx, buf); err != nil {
		return err
	}

	if err = r.TransitiveStaticLibsHeaderJarsForR8.DecodeInterface(ctx, buf); err != nil {
		return err
	}

	if err = r.TransitiveStaticLibsHeaderJars.DecodeInterface(ctx, buf); err != nil {
		return err
	}

	if err = r.TransitiveStaticLibsImplementationJars.DecodeInterface(ctx, buf); err != nil {
		return err
	}

	if err = r.TransitiveStaticLibsResourceJars.DecodeInterface(ctx, buf); err != nil {
		return err
	}

	var val26 int
	err = gobtools.DecodeInt(buf, &val26)
	if err != nil {
		return err
	}
	if val26 != -1 {
		r.ImplementationAndResourcesJars = make([]android.Path, val26)
		for val27 := 0; val27 < int(val26); val27++ {
			if val29, err := gobtools.DecodeInterface(ctx, buf); err != nil {
				return err
			} else if val29 == nil {
				r.ImplementationAndResourcesJars[val27] = nil
			} else {
				r.ImplementationAndResourcesJars[val27] = val29.(android.Path)
			}
		}
	}

	var val32 int
	err = gobtools.DecodeInt(buf, &val32)
	if err != nil {
		return err
	}
	if val32 != -1 {
		r.ImplementationJars = make([]android.Path, val32)
		for val33 := 0; val33 < int(val32); val33++ {
			if val35, err := gobtools.DecodeInterface(ctx, buf); err != nil {
				return err
			} else if val35 == nil {
				r.ImplementationJars[val33] = nil
			} else {
				r.ImplementationJars[val33] = val35.(android.Path)
			}
		}
	}

	var val38 int
	err = gobtools.DecodeInt(buf, &val38)
	if err != nil {
		return err
	}
	if val38 != -1 {
		r.ResourceJars = make([]android.Path, val38)
		for val39 := 0; val39 < int(val38); val39++ {
			if val41, err := gobtools.DecodeInterface(ctx, buf); err != nil {
				return err
			} else if val41 == nil {
				r.ResourceJars[val39] = nil
			} else {
				r.ResourceJars[val39] = val41.(android.Path)
			}
		}
	}

	var val44 int
	err = gobtools.DecodeInt(buf, &val44)
	if err != nil {
		return err
	}
	if val44 != -1 {
		r.LocalHeaderJars = make([]android.Path, val44)
		for val45 := 0; val45 < int(val44); val45++ {
			if val47, err := gobtools.DecodeInterface(ctx, buf); err != nil {
				return err
			} else if val47 == nil {
				r.LocalHeaderJars[val45] = nil
			} else {
				r.LocalHeaderJars[val45] = val47.(android.Path)
			}
		}
	}

	var val50 int
	err = gobtools.DecodeInt(buf, &val50)
	if err != nil {
		return err
	}
	if val50 != -1 {
		r.KotlinHeaderJars = make([]android.Path, val50)
		for val51 := 0; val51 < int(val50); val51++ {
			if val53, err := gobtools.DecodeInterface(ctx, buf); err != nil {
				return err
			} else if val53 == nil {
				r.KotlinHeaderJars[val51] = nil
			} else {
				r.KotlinHeaderJars[val51] = val53.(android.Path)
			}
		}
	}

	var val56 int
	err = gobtools.DecodeInt(buf, &val56)
	if err != nil {
		return err
	}
	if val56 != -1 {
		r.AidlIncludeDirs = make([]android.Path, val56)
		for val57 := 0; val57 < int(val56); val57++ {
			if val59, err := gobtools.DecodeInterface(ctx, buf); err != nil {
				return err
			} else if val59 == nil {
				r.AidlIncludeDirs[val57] = nil
			} else {
				r.AidlIncludeDirs[val57] = val59.(android.Path)
			}
		}
	}

	var val61 int
	err = gobtools.DecodeInt(buf, &val61)
	if err != nil {
		return err
	}
	if val61 != -1 {
		r.SrcJarArgs = make([]string, val61)
		for val62 := 0; val62 < int(val61); val62++ {
			err = gobtools.DecodeString(buf, &r.SrcJarArgs[val62])
			if err != nil {
				return err
			}
		}
	}

	var val66 int
	err = gobtools.DecodeInt(buf, &val66)
	if err != nil {
		return err
	}
	if val66 != -1 {
		r.SrcJarDeps = make([]android.Path, val66)
		for val67 := 0; val67 < int(val66); val67++ {
			if val69, err := gobtools.DecodeInterface(ctx, buf); err != nil {
				return err
			} else if val69 == nil {
				r.SrcJarDeps[val67] = nil
			} else {
				r.SrcJarDeps[val67] = val69.(android.Path)
			}
		}
	}

	var val70 int
	err = gobtools.DecodeInt(buf, &val70)
	if err != nil {
		return err
	}
	if val70 != -1 {
		r.KSnapshotFiles = make(map[string]android.Path, val70)
		for val71 := 0; val71 < int(val70); val71++ {
			var val72 string
			var val73 android.Path
			err = gobtools.DecodeString(buf, &val72)
			if err != nil {
				return err
			}
			if val76, err := gobtools.DecodeInterface(ctx, buf); err != nil {
				return err
			} else if val76 == nil {
				val73 = nil
			} else {
				val73 = val76.(android.Path)
			}
			r.KSnapshotFiles[val72] = val73
		}
	}

	if err = r.TransitiveSrcFiles.DecodeInterface(ctx, buf); err != nil {
		return err
	}

	var val80 int
	err = gobtools.DecodeInt(buf, &val80)
	if err != nil {
		return err
	}
	if val80 != -1 {
		r.ExportedPlugins = make([]android.Path, val80)
		for val81 := 0; val81 < int(val80); val81++ {
			if val83, err := gobtools.DecodeInterface(ctx, buf); err != nil {
				return err
			} else if val83 == nil {
				r.ExportedPlugins[val81] = nil
			} else {
				r.ExportedPlugins[val81] = val83.(android.Path)
			}
		}
	}

	var val85 int
	err = gobtools.DecodeInt(buf, &val85)
	if err != nil {
		return err
	}
	if val85 != -1 {
		r.ExportedPluginClasses = make([]string, val85)
		for val86 := 0; val86 < int(val85); val86++ {
			err = gobtools.DecodeString(buf, &r.ExportedPluginClasses[val86])
			if err != nil {
				return err
			}
		}
	}

	err = gobtools.DecodeBool(buf, &r.ExportedPluginDisableTurbine)
	if err != nil {
		return err
	}

	if err = r.JacocoInfo.Decode(ctx, buf); err != nil {
		return err
	}

	var val91 int
	err = gobtools.DecodeInt(buf, &val91)
	if err != nil {
		return err
	}
	r.StubsLinkType = StubsLinkType(val91)

	var val95 int
	err = gobtools.DecodeInt(buf, &val95)
	if err != nil {
		return err
	}
	if val95 != -1 {
		r.AconfigIntermediateCacheOutputPaths = make([]android.Path, val95)
		for val96 := 0; val96 < int(val95); val96++ {
			if val98, err := gobtools.DecodeInterface(ctx, buf); err != nil {
				return err
			} else if val98 == nil {
				r.AconfigIntermediateCacheOutputPaths[val96] = nil
			} else {
				r.AconfigIntermediateCacheOutputPaths[val96] = val98.(android.Path)
			}
		}
	}

	if err = r.SdkVersion.Decode(ctx, buf); err != nil {
		return err
	}

	if val101, err := gobtools.DecodeInterface(ctx, buf); err != nil {
		return err
	} else if val101 == nil {
		r.OutputFile = nil
	} else {
		r.OutputFile = val101.(android.Path)
	}

	var val104 int
	err = gobtools.DecodeInt(buf, &val104)
	if err != nil {
		return err
	}
	if val104 != -1 {
		r.ExtraOutputFiles = make([]android.Path, val104)
		for val105 := 0; val105 < int(val104); val105++ {
			if val107, err := gobtools.DecodeInterface(ctx, buf); err != nil {
				return err
			} else if val107 == nil {
				r.ExtraOutputFiles[val105] = nil
			} else {
				r.ExtraOutputFiles[val105] = val107.(android.Path)
			}
		}
	}

	var val109 bool
	if err = gobtools.DecodeBool(buf, &val109); err != nil {
		return err
	}
	if !val109 {
		var val108 AndroidLibraryDependencyInfo
		if err = val108.Decode(ctx, buf); err != nil {
			return err
		}
		r.AndroidLibraryDependencyInfo = &val108
	}

	var val112 bool
	if err = gobtools.DecodeBool(buf, &val112); err != nil {
		return err
	}
	if !val112 {
		var val111 UsesLibraryDependencyInfo
		if err = val111.Decode(ctx, buf); err != nil {
			return err
		}
		r.UsesLibraryDependencyInfo = &val111
	}

	var val115 bool
	if err = gobtools.DecodeBool(buf, &val115); err != nil {
		return err
	}
	if !val115 {
		var val114 ProvidesUsesLibInfo
		if err = val114.Decode(ctx, buf); err != nil {
			return err
		}
		r.ProvidesUsesLibInfo = &val114
	}

	var val118 int
	err = gobtools.DecodeInt(buf, &val118)
	if err != nil {
		return err
	}
	if val118 != -1 {
		r.MissingOptionalUsesLibs = make([]string, val118)
		for val119 := 0; val119 < int(val118); val119++ {
			err = gobtools.DecodeString(buf, &r.MissingOptionalUsesLibs[val119])
			if err != nil {
				return err
			}
		}
	}

	var val122 bool
	if err = gobtools.DecodeBool(buf, &val122); err != nil {
		return err
	}
	if !val122 {
		var val121 ModuleWithSdkDepInfo
		if err = val121.Decode(ctx, buf); err != nil {
			return err
		}
		r.ModuleWithSdkDepInfo = &val121
	}

	if err = r.DexJarFile.Decode(ctx, buf); err != nil {
		return err
	}

	if val126, err := gobtools.DecodeInterface(ctx, buf); err != nil {
		return err
	} else if val126 == nil {
		r.InstallFile = nil
	} else {
		r.InstallFile = val126.(android.Path)
	}

	if err = r.BootDexJarPath.Decode(ctx, buf); err != nil {
		return err
	}

	var val130 int
	err = gobtools.DecodeInt(buf, &val130)
	if err != nil {
		return err
	}
	if val130 != -1 {
		r.HiddenapiClassesJarPaths = make([]android.Path, val130)
		for val131 := 0; val131 < int(val130); val131++ {
			if val133, err := gobtools.DecodeInterface(ctx, buf); err != nil {
				return err
			} else if val133 == nil {
				r.HiddenapiClassesJarPaths[val131] = nil
			} else {
				r.HiddenapiClassesJarPaths[val131] = val133.(android.Path)
			}
		}
	}

	var val135 bool
	if err = gobtools.DecodeBool(buf, &val135); err != nil {
		return err
	}
	if !val135 {
		var val134 bool
		err = gobtools.DecodeBool(buf, &val134)
		if err != nil {
			return err
		}
		r.UncompressDexState = &val134
	}

	err = gobtools.DecodeBool(buf, &r.Active)
	if err != nil {
		return err
	}

	err = gobtools.DecodeString(buf, &r.BuiltInstalled)
	if err != nil {
		return err
	}

	if val140, err := gobtools.DecodeInterface(ctx, buf); err != nil {
		return err
	} else if val140 == nil {
		r.ConfigPath = nil
	} else {
		r.ConfigPath = val140.(android.WritablePath)
	}

	var val143 int
	err = gobtools.DecodeInt(buf, &val143)
	if err != nil {
		return err
	}
	if val143 != -1 {
		r.LogtagsSrcs = make([]android.Path, val143)
		for val144 := 0; val144 < int(val143); val144++ {
			if val146, err := gobtools.DecodeInterface(ctx, buf); err != nil {
				return err
			} else if val146 == nil {
				r.LogtagsSrcs[val144] = nil
			} else {
				r.LogtagsSrcs[val144] = val146.(android.Path)
			}
		}
	}

	if err = r.ProguardDictionary.Decode(ctx, buf); err != nil {
		return err
	}

	if err = r.ProguardUsageZip.Decode(ctx, buf); err != nil {
		return err
	}

	var val151 int
	err = gobtools.DecodeInt(buf, &val151)
	if err != nil {
		return err
	}
	if val151 != -1 {
		r.LinterReports = make([]android.Path, val151)
		for val152 := 0; val152 < int(val151); val152++ {
			if val154, err := gobtools.DecodeInterface(ctx, buf); err != nil {
				return err
			} else if val154 == nil {
				r.LinterReports[val152] = nil
			} else {
				r.LinterReports[val152] = val154.(android.Path)
			}
		}
	}

	if err = r.HostdexInstallFile.Decode(ctx, buf); err != nil {
		return err
	}

	var val157 int
	err = gobtools.DecodeInt(buf, &val157)
	if err != nil {
		return err
	}
	if val157 != -1 {
		r.GeneratedSrcjars = make([]android.Path, val157)
		for val158 := 0; val158 < int(val157); val158++ {
			if val160, err := gobtools.DecodeInterface(ctx, buf); err != nil {
				return err
			} else if val160 == nil {
				r.GeneratedSrcjars[val158] = nil
			} else {
				r.GeneratedSrcjars[val158] = val160.(android.Path)
			}
		}
	}

	err = gobtools.DecodeBool(buf, &r.ProfileGuided)
	if err != nil {
		return err
	}

	err = gobtools.DecodeString(buf, &r.Stem)
	if err != nil {
		return err
	}

	if err = r.DexJarBuildPath.Decode(ctx, buf); err != nil {
		return err
	}

	var val165 bool
	if err = gobtools.DecodeBool(buf, &val165); err != nil {
		return err
	}
	if !val165 {
		var val164 DexpreopterInfo
		if err = val164.Decode(ctx, buf); err != nil {
			return err
		}
		r.DexpreopterInfo = &val164
	}

	var val169 int
	err = gobtools.DecodeInt(buf, &val169)
	if err != nil {
		return err
	}
	if val169 != -1 {
		r.XrefJavaFiles = make([]android.Path, val169)
		for val170 := 0; val170 < int(val169); val170++ {
			if val172, err := gobtools.DecodeInterface(ctx, buf); err != nil {
				return err
			} else if val172 == nil {
				r.XrefJavaFiles[val170] = nil
			} else {
				r.XrefJavaFiles[val170] = val172.(android.Path)
			}
		}
	}

	var val175 int
	err = gobtools.DecodeInt(buf, &val175)
	if err != nil {
		return err
	}
	if val175 != -1 {
		r.XrefKotlinFiles = make([]android.Path, val175)
		for val176 := 0; val176 < int(val175); val176++ {
			if val178, err := gobtools.DecodeInterface(ctx, buf); err != nil {
				return err
			} else if val178 == nil {
				r.XrefKotlinFiles[val176] = nil
			} else {
				r.XrefKotlinFiles[val176] = val178.(android.Path)
			}
		}
	}

	err = gobtools.DecodeBool(buf, &r.HasOverrideMinSdkVersion)
	if err != nil {
		return err
	}

	var val181 bool
	if err = gobtools.DecodeBool(buf, &val181); err != nil {
		return err
	}
	if !val181 {
		var val180 bool
		err = gobtools.DecodeBool(buf, &val180)
		if err != nil {
			return err
		}
		r.CompileDex = &val180
	}

	err = gobtools.DecodeString(buf, &r.SystemModules)
	if err != nil {
		return err
	}

	err = gobtools.DecodeBool(buf, &r.Installable)
	if err != nil {
		return err
	}

	var val186 bool
	if err = gobtools.DecodeBool(buf, &val186); err != nil {
		return err
	}
	if !val186 {
		var val185 ApexDependencyInfo
		if err = val185.Decode(ctx, buf); err != nil {
			return err
		}
		r.ApexDependencyInfo = &val185
	}

	if err = r.MaxSdkVersion.Decode(ctx, buf); err != nil {
		return err
	}

	return err
}

var JavaInfoGobRegId int16

func (r JavaInfo) GetTypeId() int16 {
	return JavaInfoGobRegId
}

func (r DexpreopterInfo) Encode(ctx gobtools.EncContext, buf *bytes.Buffer) error {
	var err error

	if err = gobtools.EncodeInterface(ctx, buf, r.OutputProfilePathOnHost); err != nil {
		return err
	}

	if r.ApexSystemServerDexpreoptInstalls == nil {
		if err = gobtools.EncodeInt(buf, -1); err != nil {
			return err
		}
	} else {
		if err = gobtools.EncodeInt(buf, len(r.ApexSystemServerDexpreoptInstalls)); err != nil {
			return err
		}
		for val1 := 0; val1 < len(r.ApexSystemServerDexpreoptInstalls); val1++ {
			if err = r.ApexSystemServerDexpreoptInstalls[val1].Encode(ctx, buf); err != nil {
				return err
			}
		}
	}

	if r.ApexSystemServerDexJars == nil {
		if err = gobtools.EncodeInt(buf, -1); err != nil {
			return err
		}
	} else {
		if err = gobtools.EncodeInt(buf, len(r.ApexSystemServerDexJars)); err != nil {
			return err
		}
		for val2 := 0; val2 < len(r.ApexSystemServerDexJars); val2++ {
			if err = gobtools.EncodeInterface(ctx, buf, r.ApexSystemServerDexJars[val2]); err != nil {
				return err
			}
		}
	}
	return err
}

func (r *DexpreopterInfo) Decode(ctx gobtools.EncContext, buf *bytes.Reader) error {
	var err error

	if val2, err := gobtools.DecodeInterface(ctx, buf); err != nil {
		return err
	} else if val2 == nil {
		r.OutputProfilePathOnHost = nil
	} else {
		r.OutputProfilePathOnHost = val2.(android.Path)
	}

	var val4 int
	err = gobtools.DecodeInt(buf, &val4)
	if err != nil {
		return err
	}
	if val4 != -1 {
		r.ApexSystemServerDexpreoptInstalls = make([]DexpreopterInstall, val4)
		for val5 := 0; val5 < int(val4); val5++ {
			if err = r.ApexSystemServerDexpreoptInstalls[val5].Decode(ctx, buf); err != nil {
				return err
			}
		}
	}

	var val9 int
	err = gobtools.DecodeInt(buf, &val9)
	if err != nil {
		return err
	}
	if val9 != -1 {
		r.ApexSystemServerDexJars = make([]android.Path, val9)
		for val10 := 0; val10 < int(val9); val10++ {
			if val12, err := gobtools.DecodeInterface(ctx, buf); err != nil {
				return err
			} else if val12 == nil {
				r.ApexSystemServerDexJars[val10] = nil
			} else {
				r.ApexSystemServerDexJars[val10] = val12.(android.Path)
			}
		}
	}

	return err
}

var DexpreopterInfoGobRegId int16

func (r DexpreopterInfo) GetTypeId() int16 {
	return DexpreopterInfoGobRegId
}

func (r JavaLibraryInfo) Encode(ctx gobtools.EncContext, buf *bytes.Buffer) error {
	var err error

	if err = gobtools.EncodeBool(buf, r.Prebuilt); err != nil {
		return err
	}

	if r.PermittedPackages == nil {
		if err = gobtools.EncodeInt(buf, -1); err != nil {
			return err
		}
	} else {
		if err = gobtools.EncodeInt(buf, len(r.PermittedPackages)); err != nil {
			return err
		}
		for val1 := 0; val1 < len(r.PermittedPackages); val1++ {
			if err = gobtools.EncodeString(buf, r.PermittedPackages[val1]); err != nil {
				return err
			}
		}
	}
	return err
}

func (r *JavaLibraryInfo) Decode(ctx gobtools.EncContext, buf *bytes.Reader) error {
	var err error

	err = gobtools.DecodeBool(buf, &r.Prebuilt)
	if err != nil {
		return err
	}

	var val3 int
	err = gobtools.DecodeInt(buf, &val3)
	if err != nil {
		return err
	}
	if val3 != -1 {
		r.PermittedPackages = make([]string, val3)
		for val4 := 0; val4 < int(val3); val4++ {
			err = gobtools.DecodeString(buf, &r.PermittedPackages[val4])
			if err != nil {
				return err
			}
		}
	}

	return err
}

var JavaLibraryInfoGobRegId int16

func (r JavaLibraryInfo) GetTypeId() int16 {
	return JavaLibraryInfoGobRegId
}

func (r JavaDexImportInfo) Encode(ctx gobtools.EncContext, buf *bytes.Buffer) error {
	var err error
	return err
}

func (r *JavaDexImportInfo) Decode(ctx gobtools.EncContext, buf *bytes.Reader) error {
	var err error

	return err
}

var JavaDexImportInfoGobRegId int16

func (r JavaDexImportInfo) GetTypeId() int16 {
	return JavaDexImportInfoGobRegId
}

func (r SyspropPublicStubInfo) Encode(ctx gobtools.EncContext, buf *bytes.Buffer) error {
	var err error

	val1 := r.JavaInfo == nil
	if err = gobtools.EncodeBool(buf, val1); err != nil {
		return err
	}
	if !val1 {
		if err = (*r.JavaInfo).Encode(ctx, buf); err != nil {
			return err
		}
	}
	return err
}

func (r *SyspropPublicStubInfo) Decode(ctx gobtools.EncContext, buf *bytes.Reader) error {
	var err error

	var val2 bool
	if err = gobtools.DecodeBool(buf, &val2); err != nil {
		return err
	}
	if !val2 {
		var val1 JavaInfo
		if err = val1.Decode(ctx, buf); err != nil {
			return err
		}
		r.JavaInfo = &val1
	}

	return err
}

var SyspropPublicStubInfoGobRegId int16

func (r SyspropPublicStubInfo) GetTypeId() int16 {
	return SyspropPublicStubInfoGobRegId
}

func (r jniLib) Encode(ctx gobtools.EncContext, buf *bytes.Buffer) error {
	var err error

	if err = gobtools.EncodeString(buf, r.name); err != nil {
		return err
	}

	if err = gobtools.EncodeInterface(ctx, buf, r.path); err != nil {
		return err
	}

	if err = r.target.Encode(ctx, buf); err != nil {
		return err
	}

	if err = r.coverageFile.Encode(ctx, buf); err != nil {
		return err
	}

	if err = gobtools.EncodeInterface(ctx, buf, r.unstrippedFile); err != nil {
		return err
	}

	if err = gobtools.EncodeString(buf, r.partition); err != nil {
		return err
	}

	if r.installPaths == nil {
		if err = gobtools.EncodeInt(buf, -1); err != nil {
			return err
		}
	} else {
		if err = gobtools.EncodeInt(buf, len(r.installPaths)); err != nil {
			return err
		}
		for val1 := 0; val1 < len(r.installPaths); val1++ {
			if err = r.installPaths[val1].Encode(ctx, buf); err != nil {
				return err
			}
		}
	}
	return err
}

func (r *jniLib) Decode(ctx gobtools.EncContext, buf *bytes.Reader) error {
	var err error

	err = gobtools.DecodeString(buf, &r.name)
	if err != nil {
		return err
	}

	if val3, err := gobtools.DecodeInterface(ctx, buf); err != nil {
		return err
	} else if val3 == nil {
		r.path = nil
	} else {
		r.path = val3.(android.Path)
	}

	if err = r.target.Decode(ctx, buf); err != nil {
		return err
	}

	if err = r.coverageFile.Decode(ctx, buf); err != nil {
		return err
	}

	if val7, err := gobtools.DecodeInterface(ctx, buf); err != nil {
		return err
	} else if val7 == nil {
		r.unstrippedFile = nil
	} else {
		r.unstrippedFile = val7.(android.Path)
	}

	err = gobtools.DecodeString(buf, &r.partition)
	if err != nil {
		return err
	}

	var val11 int
	err = gobtools.DecodeInt(buf, &val11)
	if err != nil {
		return err
	}
	if val11 != -1 {
		r.installPaths = make([]android.InstallPath, val11)
		for val12 := 0; val12 < int(val11); val12++ {
			if err = r.installPaths[val12].Decode(ctx, buf); err != nil {
				return err
			}
		}
	}

	return err
}

var jniLibGobRegId int16

func (r jniLib) GetTypeId() int16 {
	return jniLibGobRegId
}

func (r JavaTestInfo) Encode(ctx gobtools.EncContext, buf *bytes.Buffer) error {
	var err error

	if err = gobtools.EncodeInterface(ctx, buf, r.TestConfig); err != nil {
		return err
	}
	return err
}

func (r *JavaTestInfo) Decode(ctx gobtools.EncContext, buf *bytes.Reader) error {
	var err error

	if val2, err := gobtools.DecodeInterface(ctx, buf); err != nil {
		return err
	} else if val2 == nil {
		r.TestConfig = nil
	} else {
		r.TestConfig = val2.(android.Path)
	}

	return err
}

var JavaTestInfoGobRegId int16

func (r JavaTestInfo) GetTypeId() int16 {
	return JavaTestInfoGobRegId
}

func (r JavaApiImportInfo) Encode(ctx gobtools.EncContext, buf *bytes.Buffer) error {
	var err error

	if err = gobtools.EncodeInterface(ctx, buf, r.ApiFile); err != nil {
		return err
	}

	if err = gobtools.EncodeString(buf, r.ApiSurface); err != nil {
		return err
	}
	return err
}

func (r *JavaApiImportInfo) Decode(ctx gobtools.EncContext, buf *bytes.Reader) error {
	var err error

	if val2, err := gobtools.DecodeInterface(ctx, buf); err != nil {
		return err
	} else if val2 == nil {
		r.ApiFile = nil
	} else {
		r.ApiFile = val2.(android.Path)
	}

	err = gobtools.DecodeString(buf, &r.ApiSurface)
	if err != nil {
		return err
	}

	return err
}

var JavaApiImportInfoGobRegId int16

func (r JavaApiImportInfo) GetTypeId() int16 {
	return JavaApiImportInfoGobRegId
}
