// Code generated by go run gob_gen.go; DO NOT EDIT.

package java

import (
	"android/soong/android"
	"bytes"
	"github.com/google/blueprint/gobtools"
)

func init() {
	PlatformCompatConfigInfoGobRegId = gobtools.RegisterType(func() gobtools.CustomDec { return new(PlatformCompatConfigInfo) })
}

func (r PlatformCompatConfigInfo) Encode(ctx gobtools.EncContext, buf *bytes.Buffer) error {
	var err error

	if err = r.CompatConfig.Encode(ctx, buf); err != nil {
		return err
	}

	if err = gobtools.EncodeString(buf, r.SubDir); err != nil {
		return err
	}

	if err = gobtools.EncodeInterface(ctx, buf, r.CompatConfigMetadata); err != nil {
		return err
	}

	if err = gobtools.EncodeBool(buf, r.IncludeInMergedXml); err != nil {
		return err
	}

	if err = gobtools.EncodeBool(buf, r.Prebuilt); err != nil {
		return err
	}
	return err
}

func (r *PlatformCompatConfigInfo) Decode(ctx gobtools.EncContext, buf *bytes.Reader) error {
	var err error

	if err = r.CompatConfig.Decode(ctx, buf); err != nil {
		return err
	}

	err = gobtools.DecodeString(buf, &r.SubDir)
	if err != nil {
		return err
	}

	if val4, err := gobtools.DecodeInterface(ctx, buf); err != nil {
		return err
	} else if val4 == nil {
		r.CompatConfigMetadata = nil
	} else {
		r.CompatConfigMetadata = val4.(android.Path)
	}

	err = gobtools.DecodeBool(buf, &r.IncludeInMergedXml)
	if err != nil {
		return err
	}

	err = gobtools.DecodeBool(buf, &r.Prebuilt)
	if err != nil {
		return err
	}

	return err
}

var PlatformCompatConfigInfoGobRegId int16

func (r PlatformCompatConfigInfo) GetTypeId() int16 {
	return PlatformCompatConfigInfoGobRegId
}
