// Code generated by go run gob_gen.go; DO NOT EDIT.

package java

import (
	"bytes"
	"github.com/google/blueprint/gobtools"
)

func init() {
	ravenwoodLibgroupJniDepProviderInfoGobRegId = gobtools.RegisterType(func() gobtools.CustomDec { return new(ravenwoodLibgroupJniDepProviderInfo) })
}

func (r ravenwoodLibgroupJniDepProviderInfo) Encode(ctx gobtools.EncContext, buf *bytes.Buffer) error {
	var err error

	if r.names == nil {
		if err = gobtools.EncodeInt(buf, -1); err != nil {
			return err
		}
	} else {
		if err = gobtools.EncodeInt(buf, len(r.names)); err != nil {
			return err
		}
		for val1, val2 := range r.names {
			if err = gobtools.EncodeString(buf, val1); err != nil {
				return err
			}
			if err = gobtools.EncodeBool(buf, val2); err != nil {
				return err
			}
		}
	}
	return err
}

func (r *ravenwoodLibgroupJniDepProviderInfo) Decode(ctx gobtools.EncContext, buf *bytes.Reader) error {
	var err error

	var val1 int
	err = gobtools.DecodeInt(buf, &val1)
	if err != nil {
		return err
	}
	if val1 != -1 {
		r.names = make(map[string]bool, val1)
		for val2 := 0; val2 < int(val1); val2++ {
			var val3 string
			var val4 bool
			err = gobtools.DecodeString(buf, &val3)
			if err != nil {
				return err
			}
			err = gobtools.DecodeBool(buf, &val4)
			if err != nil {
				return err
			}
			r.names[val3] = val4
		}
	}

	return err
}

var ravenwoodLibgroupJniDepProviderInfoGobRegId int16

func (r ravenwoodLibgroupJniDepProviderInfo) GetTypeId() int16 {
	return ravenwoodLibgroupJniDepProviderInfoGobRegId
}
