// Code generated by go run gob_gen.go; DO NOT EDIT.

package java

import (
	"bytes"
	"github.com/google/blueprint/gobtools"
)

func init() {
	ravenwoodLibgroupJniDepProviderInfoGobRegId = gobtools.RegisterType(func() gobtools.CustomDec { return new(ravenwoodLibgroupJniDepProviderInfo) })
}

func (r ravenwoodLibgroupJniDepProviderInfo) Encode(ctx gobtools.EncContext, buf *bytes.Buffer) error {
	var err error

	if r.names == nil {
		if err = gobtools.EncodeInt(buf, -1); err != nil {
			return err
		}
	} else {
		if err = gobtools.EncodeInt(buf, len(r.names)); err != nil {
			return err
		}
		for k, v := range r.names {
			if err = gobtools.EncodeString(buf, k); err != nil {
				return err
			}
			if err = gobtools.EncodeBool(buf, v); err != nil {
				return err
			}
		}
	}
	return err
}

func (r *ravenwoodLibgroupJniDepProviderInfo) Decode(ctx gobtools.EncContext, buf *bytes.Reader) error {
	var err error

	var val1 int
	err = gobtools.DecodeInt(buf, &val1)
	if err != nil {
		return err
	}
	if val1 != -1 {
		r.names = make(map[string]bool, val1)
		for val2 := 0; val2 < int(val1); val2++ {
			var k string
			var v bool
			err = gobtools.DecodeString(buf, &k)
			if err != nil {
				return err
			}
			err = gobtools.DecodeBool(buf, &v)
			if err != nil {
				return err
			}
			r.names[k] = v
		}
	}

	return err
}

var ravenwoodLibgroupJniDepProviderInfoGobRegId int16

func (r ravenwoodLibgroupJniDepProviderInfo) GetTypeId() int16 {
	return ravenwoodLibgroupJniDepProviderInfoGobRegId
}
