// Code generated by go run gob_gen.go; DO NOT EDIT.

package java

import (
	"android/soong/android"
	"bytes"
	"github.com/google/blueprint/gobtools"
)

func init() {
	RobolectricRuntimesInfoGobRegId = gobtools.RegisterType(func() gobtools.CustomDec { return new(RobolectricRuntimesInfo) })
}

func (r RobolectricRuntimesInfo) Encode(ctx gobtools.EncContext, buf *bytes.Buffer) error {
	var err error

	if r.Runtimes == nil {
		if err = gobtools.EncodeInt(buf, -1); err != nil {
			return err
		}
	} else {
		if err = gobtools.EncodeInt(buf, len(r.Runtimes)); err != nil {
			return err
		}
		for val1 := 0; val1 < len(r.Runtimes); val1++ {
			if err = r.Runtimes[val1].Encode(ctx, buf); err != nil {
				return err
			}
		}
	}
	return err
}

func (r *RobolectricRuntimesInfo) Decode(ctx gobtools.EncContext, buf *bytes.Reader) error {
	var err error

	var val2 int
	err = gobtools.DecodeInt(buf, &val2)
	if err != nil {
		return err
	}
	if val2 != -1 {
		r.Runtimes = make([]android.InstallPath, val2)
		for val3 := 0; val3 < int(val2); val3++ {
			if err = r.Runtimes[val3].Decode(ctx, buf); err != nil {
				return err
			}
		}
	}

	return err
}

var RobolectricRuntimesInfoGobRegId int16

func (r RobolectricRuntimesInfo) GetTypeId() int16 {
	return RobolectricRuntimesInfoGobRegId
}
