// Code generated by go run gob_gen.go; DO NOT EDIT.

package java

import (
	"android/soong/android"
	"bytes"
	"github.com/google/blueprint/gobtools"
)

func init() {
	ApiScopePathsInfoGobRegId = gobtools.RegisterType(func() gobtools.CustomDec { return new(ApiScopePathsInfo) })
	ApiScopePropsInfoGobRegId = gobtools.RegisterType(func() gobtools.CustomDec { return new(ApiScopePropsInfo) })
	SdkLibraryInfoGobRegId = gobtools.RegisterType(func() gobtools.CustomDec { return new(SdkLibraryInfo) })
}

func (r ApiScopePathsInfo) Encode(ctx gobtools.EncContext, buf *bytes.Buffer) error {
	var err error

	if r.StubsImplPath == nil {
		if err = gobtools.EncodeInt(buf, -1); err != nil {
			return err
		}
	} else {
		if err = gobtools.EncodeInt(buf, len(r.StubsImplPath)); err != nil {
			return err
		}
		for val1 := 0; val1 < len(r.StubsImplPath); val1++ {
			if err = gobtools.EncodeInterface(ctx, buf, r.StubsImplPath[val1]); err != nil {
				return err
			}
		}
	}

	if err = r.CurrentApiFilePath.Encode(ctx, buf); err != nil {
		return err
	}

	if err = r.RemovedApiFilePath.Encode(ctx, buf); err != nil {
		return err
	}

	if err = r.StubsSrcJar.Encode(ctx, buf); err != nil {
		return err
	}

	if err = r.AnnotationsZip.Encode(ctx, buf); err != nil {
		return err
	}
	return err
}

func (r *ApiScopePathsInfo) Decode(ctx gobtools.EncContext, buf *bytes.Reader) error {
	var err error

	var val3 int
	err = gobtools.DecodeInt(buf, &val3)
	if err != nil {
		return err
	}
	if val3 != -1 {
		r.StubsImplPath = make([]android.Path, val3)
		for val4 := 0; val4 < int(val3); val4++ {
			if val6, err := gobtools.DecodeInterface(ctx, buf); err != nil {
				return err
			} else if val6 == nil {
				r.StubsImplPath[val4] = nil
			} else {
				r.StubsImplPath[val4] = val6.(android.Path)
			}
		}
	}

	if err = r.CurrentApiFilePath.Decode(ctx, buf); err != nil {
		return err
	}

	if err = r.RemovedApiFilePath.Decode(ctx, buf); err != nil {
		return err
	}

	if err = r.StubsSrcJar.Decode(ctx, buf); err != nil {
		return err
	}

	if err = r.AnnotationsZip.Decode(ctx, buf); err != nil {
		return err
	}

	return err
}

var ApiScopePathsInfoGobRegId int16

func (r ApiScopePathsInfo) GetTypeId() int16 {
	return ApiScopePathsInfoGobRegId
}

func (r ApiScopePropsInfo) Encode(ctx gobtools.EncContext, buf *bytes.Buffer) error {
	var err error

	val1 := r.SdkVersion == nil
	if err = gobtools.EncodeBool(buf, val1); err != nil {
		return err
	}
	if !val1 {
		if err = gobtools.EncodeString(buf, (*r.SdkVersion)); err != nil {
			return err
		}
	}
	return err
}

func (r *ApiScopePropsInfo) Decode(ctx gobtools.EncContext, buf *bytes.Reader) error {
	var err error

	var val2 bool
	if err = gobtools.DecodeBool(buf, &val2); err != nil {
		return err
	}
	if !val2 {
		var val1 string
		err = gobtools.DecodeString(buf, &val1)
		if err != nil {
			return err
		}
		r.SdkVersion = &val1
	}

	return err
}

var ApiScopePropsInfoGobRegId int16

func (r ApiScopePropsInfo) GetTypeId() int16 {
	return ApiScopePropsInfoGobRegId
}

func (r SdkLibraryInfo) Encode(ctx gobtools.EncContext, buf *bytes.Buffer) error {
	var err error

	if r.GeneratingLibs == nil {
		if err = gobtools.EncodeInt(buf, -1); err != nil {
			return err
		}
	} else {
		if err = gobtools.EncodeInt(buf, len(r.GeneratingLibs)); err != nil {
			return err
		}
		for val1 := 0; val1 < len(r.GeneratingLibs); val1++ {
			if err = gobtools.EncodeString(buf, r.GeneratingLibs[val1]); err != nil {
				return err
			}
		}
	}

	if r.EverythingStubDexJarPaths == nil {
		if err = gobtools.EncodeInt(buf, -1); err != nil {
			return err
		}
	} else {
		if err = gobtools.EncodeInt(buf, len(r.EverythingStubDexJarPaths)); err != nil {
			return err
		}
		for k, v := range r.EverythingStubDexJarPaths {
			if err = gobtools.EncodeInt(buf, int(k)); err != nil {
				return err
			}
			if err = v.Encode(ctx, buf); err != nil {
				return err
			}
		}
	}

	if r.ExportableStubDexJarPaths == nil {
		if err = gobtools.EncodeInt(buf, -1); err != nil {
			return err
		}
	} else {
		if err = gobtools.EncodeInt(buf, len(r.ExportableStubDexJarPaths)); err != nil {
			return err
		}
		for k, v := range r.ExportableStubDexJarPaths {
			if err = gobtools.EncodeInt(buf, int(k)); err != nil {
				return err
			}
			if err = v.Encode(ctx, buf); err != nil {
				return err
			}
		}
	}

	if r.RemovedTxtFiles == nil {
		if err = gobtools.EncodeInt(buf, -1); err != nil {
			return err
		}
	} else {
		if err = gobtools.EncodeInt(buf, len(r.RemovedTxtFiles)); err != nil {
			return err
		}
		for k, v := range r.RemovedTxtFiles {
			if err = gobtools.EncodeInt(buf, int(k)); err != nil {
				return err
			}
			if err = v.Encode(ctx, buf); err != nil {
				return err
			}
		}
	}

	if err = gobtools.EncodeBool(buf, r.SharedLibrary); err != nil {
		return err
	}

	if err = gobtools.EncodeBool(buf, r.Prebuilt); err != nil {
		return err
	}

	if err = gobtools.EncodeString(buf, r.DistStem); err != nil {
		return err
	}

	if r.DoctagPaths == nil {
		if err = gobtools.EncodeInt(buf, -1); err != nil {
			return err
		}
	} else {
		if err = gobtools.EncodeInt(buf, len(r.DoctagPaths)); err != nil {
			return err
		}
		for val2 := 0; val2 < len(r.DoctagPaths); val2++ {
			if err = gobtools.EncodeInterface(ctx, buf, r.DoctagPaths[val2]); err != nil {
				return err
			}
		}
	}

	val3 := r.OnBootclasspathSince == nil
	if err = gobtools.EncodeBool(buf, val3); err != nil {
		return err
	}
	if !val3 {
		if err = gobtools.EncodeString(buf, (*r.OnBootclasspathSince)); err != nil {
			return err
		}
	}

	val4 := r.OnBootclasspathBefore == nil
	if err = gobtools.EncodeBool(buf, val4); err != nil {
		return err
	}
	if !val4 {
		if err = gobtools.EncodeString(buf, (*r.OnBootclasspathBefore)); err != nil {
			return err
		}
	}

	val5 := r.MinDeviceSdk == nil
	if err = gobtools.EncodeBool(buf, val5); err != nil {
		return err
	}
	if !val5 {
		if err = gobtools.EncodeString(buf, (*r.MinDeviceSdk)); err != nil {
			return err
		}
	}

	val6 := r.MaxDeviceSdk == nil
	if err = gobtools.EncodeBool(buf, val6); err != nil {
		return err
	}
	if !val6 {
		if err = gobtools.EncodeString(buf, (*r.MaxDeviceSdk)); err != nil {
			return err
		}
	}

	if err = gobtools.EncodeBool(buf, r.ImplLibProfileGuided); err != nil {
		return err
	}

	if r.ApiScopePaths == nil {
		if err = gobtools.EncodeInt(buf, -1); err != nil {
			return err
		}
	} else {
		if err = gobtools.EncodeInt(buf, len(r.ApiScopePaths)); err != nil {
			return err
		}
		for k, v := range r.ApiScopePaths {
			if err = gobtools.EncodeString(buf, k); err != nil {
				return err
			}
			if err = v.Encode(ctx, buf); err != nil {
				return err
			}
		}
	}

	if r.ApiScopeProps == nil {
		if err = gobtools.EncodeInt(buf, -1); err != nil {
			return err
		}
	} else {
		if err = gobtools.EncodeInt(buf, len(r.ApiScopeProps)); err != nil {
			return err
		}
		for k, v := range r.ApiScopeProps {
			if err = gobtools.EncodeString(buf, k); err != nil {
				return err
			}
			if err = v.Encode(ctx, buf); err != nil {
				return err
			}
		}
	}
	return err
}

func (r *SdkLibraryInfo) Decode(ctx gobtools.EncContext, buf *bytes.Reader) error {
	var err error

	var val2 int
	err = gobtools.DecodeInt(buf, &val2)
	if err != nil {
		return err
	}
	if val2 != -1 {
		r.GeneratingLibs = make([]string, val2)
		for val3 := 0; val3 < int(val2); val3++ {
			err = gobtools.DecodeString(buf, &r.GeneratingLibs[val3])
			if err != nil {
				return err
			}
		}
	}

	var val5 int
	err = gobtools.DecodeInt(buf, &val5)
	if err != nil {
		return err
	}
	if val5 != -1 {
		r.EverythingStubDexJarPaths = make(map[android.SdkKind]OptionalDexJarPath, val5)
		for val6 := 0; val6 < int(val5); val6++ {
			var k android.SdkKind
			var v OptionalDexJarPath
			var val8 int
			err = gobtools.DecodeInt(buf, &val8)
			if err != nil {
				return err
			}
			k = android.SdkKind(val8)
			if err = v.Decode(ctx, buf); err != nil {
				return err
			}
			r.EverythingStubDexJarPaths[k] = v
		}
	}

	var val11 int
	err = gobtools.DecodeInt(buf, &val11)
	if err != nil {
		return err
	}
	if val11 != -1 {
		r.ExportableStubDexJarPaths = make(map[android.SdkKind]OptionalDexJarPath, val11)
		for val12 := 0; val12 < int(val11); val12++ {
			var k android.SdkKind
			var v OptionalDexJarPath
			var val14 int
			err = gobtools.DecodeInt(buf, &val14)
			if err != nil {
				return err
			}
			k = android.SdkKind(val14)
			if err = v.Decode(ctx, buf); err != nil {
				return err
			}
			r.ExportableStubDexJarPaths[k] = v
		}
	}

	var val17 int
	err = gobtools.DecodeInt(buf, &val17)
	if err != nil {
		return err
	}
	if val17 != -1 {
		r.RemovedTxtFiles = make(map[android.SdkKind]android.OptionalPath, val17)
		for val18 := 0; val18 < int(val17); val18++ {
			var k android.SdkKind
			var v android.OptionalPath
			var val20 int
			err = gobtools.DecodeInt(buf, &val20)
			if err != nil {
				return err
			}
			k = android.SdkKind(val20)
			if err = v.Decode(ctx, buf); err != nil {
				return err
			}
			r.RemovedTxtFiles[k] = v
		}
	}

	err = gobtools.DecodeBool(buf, &r.SharedLibrary)
	if err != nil {
		return err
	}

	err = gobtools.DecodeBool(buf, &r.Prebuilt)
	if err != nil {
		return err
	}

	err = gobtools.DecodeString(buf, &r.DistStem)
	if err != nil {
		return err
	}

	var val28 int
	err = gobtools.DecodeInt(buf, &val28)
	if err != nil {
		return err
	}
	if val28 != -1 {
		r.DoctagPaths = make([]android.Path, val28)
		for val29 := 0; val29 < int(val28); val29++ {
			if val31, err := gobtools.DecodeInterface(ctx, buf); err != nil {
				return err
			} else if val31 == nil {
				r.DoctagPaths[val29] = nil
			} else {
				r.DoctagPaths[val29] = val31.(android.Path)
			}
		}
	}

	var val33 bool
	if err = gobtools.DecodeBool(buf, &val33); err != nil {
		return err
	}
	if !val33 {
		var val32 string
		err = gobtools.DecodeString(buf, &val32)
		if err != nil {
			return err
		}
		r.OnBootclasspathSince = &val32
	}

	var val36 bool
	if err = gobtools.DecodeBool(buf, &val36); err != nil {
		return err
	}
	if !val36 {
		var val35 string
		err = gobtools.DecodeString(buf, &val35)
		if err != nil {
			return err
		}
		r.OnBootclasspathBefore = &val35
	}

	var val39 bool
	if err = gobtools.DecodeBool(buf, &val39); err != nil {
		return err
	}
	if !val39 {
		var val38 string
		err = gobtools.DecodeString(buf, &val38)
		if err != nil {
			return err
		}
		r.MinDeviceSdk = &val38
	}

	var val42 bool
	if err = gobtools.DecodeBool(buf, &val42); err != nil {
		return err
	}
	if !val42 {
		var val41 string
		err = gobtools.DecodeString(buf, &val41)
		if err != nil {
			return err
		}
		r.MaxDeviceSdk = &val41
	}

	err = gobtools.DecodeBool(buf, &r.ImplLibProfileGuided)
	if err != nil {
		return err
	}

	var val45 int
	err = gobtools.DecodeInt(buf, &val45)
	if err != nil {
		return err
	}
	if val45 != -1 {
		r.ApiScopePaths = make(map[string]ApiScopePathsInfo, val45)
		for val46 := 0; val46 < int(val45); val46++ {
			var k string
			var v ApiScopePathsInfo
			err = gobtools.DecodeString(buf, &k)
			if err != nil {
				return err
			}
			if err = v.Decode(ctx, buf); err != nil {
				return err
			}
			r.ApiScopePaths[k] = v
		}
	}

	var val49 int
	err = gobtools.DecodeInt(buf, &val49)
	if err != nil {
		return err
	}
	if val49 != -1 {
		r.ApiScopeProps = make(map[string]ApiScopePropsInfo, val49)
		for val50 := 0; val50 < int(val49); val50++ {
			var k string
			var v ApiScopePropsInfo
			err = gobtools.DecodeString(buf, &k)
			if err != nil {
				return err
			}
			if err = v.Decode(ctx, buf); err != nil {
				return err
			}
			r.ApiScopeProps[k] = v
		}
	}

	return err
}

var SdkLibraryInfoGobRegId int16

func (r SdkLibraryInfo) GetTypeId() int16 {
	return SdkLibraryInfoGobRegId
}
