// Code generated by go run gob_gen.go; DO NOT EDIT.

package java

import (
	"bytes"
	"github.com/google/blueprint/gobtools"
)

func init() {
	SystemServerClasspathInfoGobRegId = gobtools.RegisterType(func() gobtools.CustomDec { return new(SystemServerClasspathInfo) })
	LibraryNameToPartitionInfoGobRegId = gobtools.RegisterType(func() gobtools.CustomDec { return new(LibraryNameToPartitionInfo) })
}

func (r SystemServerClasspathInfo) Encode(ctx gobtools.EncContext, buf *bytes.Buffer) error {
	var err error

	if r.Contents == nil {
		if err = gobtools.EncodeInt(buf, -1); err != nil {
			return err
		}
	} else {
		if err = gobtools.EncodeInt(buf, len(r.Contents)); err != nil {
			return err
		}
		for val1 := 0; val1 < len(r.Contents); val1++ {
			if err = gobtools.EncodeString(buf, r.Contents[val1]); err != nil {
				return err
			}
		}
	}

	if r.StandaloneContents == nil {
		if err = gobtools.EncodeInt(buf, -1); err != nil {
			return err
		}
	} else {
		if err = gobtools.EncodeInt(buf, len(r.StandaloneContents)); err != nil {
			return err
		}
		for val2 := 0; val2 < len(r.StandaloneContents); val2++ {
			if err = gobtools.EncodeString(buf, r.StandaloneContents[val2]); err != nil {
				return err
			}
		}
	}
	return err
}

func (r *SystemServerClasspathInfo) Decode(ctx gobtools.EncContext, buf *bytes.Reader) error {
	var err error

	var val2 int
	err = gobtools.DecodeInt(buf, &val2)
	if err != nil {
		return err
	}
	if val2 != -1 {
		r.Contents = make([]string, val2)
		for val3 := 0; val3 < int(val2); val3++ {
			err = gobtools.DecodeString(buf, &r.Contents[val3])
			if err != nil {
				return err
			}
		}
	}

	var val6 int
	err = gobtools.DecodeInt(buf, &val6)
	if err != nil {
		return err
	}
	if val6 != -1 {
		r.StandaloneContents = make([]string, val6)
		for val7 := 0; val7 < int(val6); val7++ {
			err = gobtools.DecodeString(buf, &r.StandaloneContents[val7])
			if err != nil {
				return err
			}
		}
	}

	return err
}

var SystemServerClasspathInfoGobRegId int16

func (r SystemServerClasspathInfo) GetTypeId() int16 {
	return SystemServerClasspathInfoGobRegId
}

func (r LibraryNameToPartitionInfo) Encode(ctx gobtools.EncContext, buf *bytes.Buffer) error {
	var err error

	if r.LibraryNameToPartition == nil {
		if err = gobtools.EncodeInt(buf, -1); err != nil {
			return err
		}
	} else {
		if err = gobtools.EncodeInt(buf, len(r.LibraryNameToPartition)); err != nil {
			return err
		}
		for val1, val2 := range r.LibraryNameToPartition {
			if err = gobtools.EncodeString(buf, val1); err != nil {
				return err
			}
			if err = gobtools.EncodeString(buf, val2); err != nil {
				return err
			}
		}
	}
	return err
}

func (r *LibraryNameToPartitionInfo) Decode(ctx gobtools.EncContext, buf *bytes.Reader) error {
	var err error

	var val1 int
	err = gobtools.DecodeInt(buf, &val1)
	if err != nil {
		return err
	}
	if val1 != -1 {
		r.LibraryNameToPartition = make(map[string]string, val1)
		for val2 := 0; val2 < int(val1); val2++ {
			var val3 string
			var val4 string
			err = gobtools.DecodeString(buf, &val3)
			if err != nil {
				return err
			}
			err = gobtools.DecodeString(buf, &val4)
			if err != nil {
				return err
			}
			r.LibraryNameToPartition[val3] = val4
		}
	}

	return err
}

var LibraryNameToPartitionInfoGobRegId int16

func (r LibraryNameToPartitionInfo) GetTypeId() int16 {
	return LibraryNameToPartitionInfoGobRegId
}
