// Code generated by go run gob_gen.go; DO NOT EDIT.

package sysprop

import (
	"android/soong/android"
	"bytes"
	"github.com/google/blueprint/gobtools"
)

// begin of sysprop_library.go
func init() {
	SyspropLibraryInfoGobRegId = gobtools.RegisterType(func() gobtools.CustomDec { return new(SyspropLibraryInfo) })
}

func (r SyspropLibraryInfo) Encode(ctx gobtools.EncContext, buf *bytes.Buffer) error {
	var err error

	if err = gobtools.EncodeInterface(ctx, buf, r.CheckApiFileTimeStamp); err != nil {
		return err
	}

	if err = r.CurrentApiFile.Encode(ctx, buf); err != nil {
		return err
	}
	return err
}

func (r *SyspropLibraryInfo) Decode(ctx gobtools.EncContext, buf *bytes.Reader) error {
	var err error

	if val2, err := gobtools.DecodeInterface(ctx, buf); err != nil {
		return err
	} else if val2 == nil {
		r.CheckApiFileTimeStamp = nil
	} else {
		r.CheckApiFileTimeStamp = val2.(android.WritablePath)
	}

	if err = r.CurrentApiFile.Decode(ctx, buf); err != nil {
		return err
	}

	return err
}

var SyspropLibraryInfoGobRegId int16

func (r SyspropLibraryInfo) GetTypeId() int16 {
	return SyspropLibraryInfoGobRegId
}

// end of sysprop_library.go
