// Code generated by go run gob_gen.go; DO NOT EDIT.

package bloaty

import (
	"android/soong/android"
	"bytes"
	"github.com/google/blueprint/gobtools"
)

func init() {
	measuredFilesGobRegId = gobtools.RegisterType(func() gobtools.CustomDec { return new(measuredFiles) })
}

func (r measuredFiles) Encode(ctx gobtools.EncContext, buf *bytes.Buffer) error {
	var err error

	if r.paths == nil {
		if err = gobtools.EncodeSimple(buf, int32(-1)); err != nil {
			return err
		}
	} else {
		if err = gobtools.EncodeSimple(buf, int32(len(r.paths))); err != nil {
			return err
		}
		for val1 := 0; val1 < len(r.paths); val1++ {
			if err = gobtools.EncodeInterface(ctx, buf, r.paths[val1]); err != nil {
				return err
			}
		}
	}
	return err
}

func (r *measuredFiles) Decode(ctx gobtools.EncContext, buf *bytes.Reader) error {
	var err error

	var val2 int32
	err = gobtools.DecodeSimple[int32](buf, &val2)
	if err != nil {
		return err
	}
	if val2 != -1 {
		r.paths = make([]android.WritablePath, val2)
		for val3 := 0; val3 < int(val2); val3++ {
			if val5, err := gobtools.DecodeInterface(ctx, buf); err != nil {
				return err
			} else if val5 == nil {
				r.paths[val3] = nil
			} else {
				r.paths[val3] = val5.(android.WritablePath)
			}
		}
	}

	return err
}

var measuredFilesGobRegId int16

func (r measuredFiles) GetTypeId() int16 {
	return measuredFilesGobRegId
}
