// Code generated by go run gob_gen.go; DO NOT EDIT.

package bpf

import (
	"bytes"
	"github.com/google/blueprint/gobtools"
)

// begin of bpf.go
func init() {
	BpfInfoGobRegId = gobtools.RegisterType(func() gobtools.CustomDec { return new(BpfInfo) })
}

func (r BpfInfo) Encode(ctx gobtools.EncContext, buf *bytes.Buffer) error {
	var err error

	if err = gobtools.EncodeString(buf, r.SubDir); err != nil {
		return err
	}
	return err
}

func (r *BpfInfo) Decode(ctx gobtools.EncContext, buf *bytes.Reader) error {
	var err error

	err = gobtools.DecodeString(buf, &r.SubDir)
	if err != nil {
		return err
	}

	return err
}

var BpfInfoGobRegId int16

func (r BpfInfo) GetTypeId() int16 {
	return BpfInfoGobRegId
}

// end of bpf.go
