// Code generated by go run gob_gen.go; DO NOT EDIT.

package rust

import (
	"android/soong/android"
	"android/soong/cc"
	"bytes"
	"github.com/google/blueprint/gobtools"
)

func init() {
	LibraryInfoGobRegId = gobtools.RegisterType(func() gobtools.CustomDec { return new(LibraryInfo) })
	CompilerInfoGobRegId = gobtools.RegisterType(func() gobtools.CustomDec { return new(CompilerInfo) })
	ProtobufDecoratorInfoGobRegId = gobtools.RegisterType(func() gobtools.CustomDec { return new(ProtobufDecoratorInfo) })
	SourceProviderInfoGobRegId = gobtools.RegisterType(func() gobtools.CustomDec { return new(SourceProviderInfo) })
	ProcMacroInfoGobRegId = gobtools.RegisterType(func() gobtools.CustomDec { return new(ProcMacroInfo) })
	RustInfoGobRegId = gobtools.RegisterType(func() gobtools.CustomDec { return new(RustInfo) })
	RustFlagExporterInfoGobRegId = gobtools.RegisterType(func() gobtools.CustomDec { return new(RustFlagExporterInfo) })
	RustImplementationDepInfoGobRegId = gobtools.RegisterType(func() gobtools.CustomDec { return new(RustImplementationDepInfo) })
}

func (r LibraryInfo) Encode(ctx gobtools.EncContext, buf *bytes.Buffer) error {
	var err error

	if err = gobtools.EncodeSimple(buf, r.Rlib); err != nil {
		return err
	}

	if err = gobtools.EncodeSimple(buf, r.Dylib); err != nil {
		return err
	}
	return err
}

func (r *LibraryInfo) Decode(ctx gobtools.EncContext, buf *bytes.Reader) error {
	var err error

	err = gobtools.DecodeSimple[bool](buf, &r.Rlib)
	if err != nil {
		return err
	}

	err = gobtools.DecodeSimple[bool](buf, &r.Dylib)
	if err != nil {
		return err
	}

	return err
}

var LibraryInfoGobRegId int16

func (r LibraryInfo) GetTypeId() int16 {
	return LibraryInfoGobRegId
}

func (r CompilerInfo) Encode(ctx gobtools.EncContext, buf *bytes.Buffer) error {
	var err error

	if err = gobtools.EncodeSimple(buf, int64(int(r.StdLinkageForDevice))); err != nil {
		return err
	}

	if err = gobtools.EncodeSimple(buf, int64(int(r.StdLinkageForNonDevice))); err != nil {
		return err
	}

	if err = gobtools.EncodeSimple(buf, r.NoStdlibs); err != nil {
		return err
	}

	if err = gobtools.EncodeString(buf, r.CrateName); err != nil {
		return err
	}

	if err = gobtools.EncodeString(buf, r.Edition); err != nil {
		return err
	}

	if err = r.CargoOutDir.Encode(ctx, buf); err != nil {
		return err
	}

	if r.Features == nil {
		if err = gobtools.EncodeSimple(buf, int32(-1)); err != nil {
			return err
		}
	} else {
		if err = gobtools.EncodeSimple(buf, int32(len(r.Features))); err != nil {
			return err
		}
		for val1 := 0; val1 < len(r.Features); val1++ {
			if err = gobtools.EncodeString(buf, r.Features[val1]); err != nil {
				return err
			}
		}
	}

	if err = gobtools.EncodeInterface(ctx, buf, r.CrateRootPath); err != nil {
		return err
	}

	val2 := r.LibraryInfo == nil
	if err = gobtools.EncodeSimple(buf, val2); err != nil {
		return err
	}
	if !val2 {
		if err = (*r.LibraryInfo).Encode(ctx, buf); err != nil {
			return err
		}
	}

	if err = gobtools.EncodeInterface(ctx, buf, r.BuildTarget); err != nil {
		return err
	}

	if err = r.CheckTarget.Encode(ctx, buf); err != nil {
		return err
	}
	return err
}

func (r *CompilerInfo) Decode(ctx gobtools.EncContext, buf *bytes.Reader) error {
	var err error

	var val2 int
	var val3 int64
	err = gobtools.DecodeSimple[int64](buf, &val3)
	if err != nil {
		return err
	}
	val2 = int(val3)
	r.StdLinkageForDevice = StdLinkage(val2)

	var val5 int
	var val6 int64
	err = gobtools.DecodeSimple[int64](buf, &val6)
	if err != nil {
		return err
	}
	val5 = int(val6)
	r.StdLinkageForNonDevice = StdLinkage(val5)

	err = gobtools.DecodeSimple[bool](buf, &r.NoStdlibs)
	if err != nil {
		return err
	}

	err = gobtools.DecodeString(buf, &r.CrateName)
	if err != nil {
		return err
	}

	err = gobtools.DecodeString(buf, &r.Edition)
	if err != nil {
		return err
	}

	if err = r.CargoOutDir.Decode(ctx, buf); err != nil {
		return err
	}

	var val12 int32
	err = gobtools.DecodeSimple[int32](buf, &val12)
	if err != nil {
		return err
	}
	if val12 != -1 {
		r.Features = make([]string, val12)
		for val13 := 0; val13 < int(val12); val13++ {
			err = gobtools.DecodeString(buf, &r.Features[val13])
			if err != nil {
				return err
			}
		}
	}

	if val16, err := gobtools.DecodeInterface(ctx, buf); err != nil {
		return err
	} else if val16 == nil {
		r.CrateRootPath = nil
	} else {
		r.CrateRootPath = val16.(android.Path)
	}

	var val18 bool
	if err = gobtools.DecodeSimple(buf, &val18); err != nil {
		return err
	}
	if !val18 {
		var val17 LibraryInfo
		if err = val17.Decode(ctx, buf); err != nil {
			return err
		}
		r.LibraryInfo = &val17
	}

	if val21, err := gobtools.DecodeInterface(ctx, buf); err != nil {
		return err
	} else if val21 == nil {
		r.BuildTarget = nil
	} else {
		r.BuildTarget = val21.(android.Path)
	}

	if err = r.CheckTarget.Decode(ctx, buf); err != nil {
		return err
	}

	return err
}

var CompilerInfoGobRegId int16

func (r CompilerInfo) GetTypeId() int16 {
	return CompilerInfoGobRegId
}

func (r ProtobufDecoratorInfo) Encode(ctx gobtools.EncContext, buf *bytes.Buffer) error {
	var err error
	return err
}

func (r *ProtobufDecoratorInfo) Decode(ctx gobtools.EncContext, buf *bytes.Reader) error {
	var err error

	return err
}

var ProtobufDecoratorInfoGobRegId int16

func (r ProtobufDecoratorInfo) GetTypeId() int16 {
	return ProtobufDecoratorInfoGobRegId
}

func (r SourceProviderInfo) Encode(ctx gobtools.EncContext, buf *bytes.Buffer) error {
	var err error

	if r.Srcs == nil {
		if err = gobtools.EncodeSimple(buf, int32(-1)); err != nil {
			return err
		}
	} else {
		if err = gobtools.EncodeSimple(buf, int32(len(r.Srcs))); err != nil {
			return err
		}
		for val1 := 0; val1 < len(r.Srcs); val1++ {
			if err = gobtools.EncodeInterface(ctx, buf, r.Srcs[val1]); err != nil {
				return err
			}
		}
	}

	val2 := r.ProtobufDecoratorInfo == nil
	if err = gobtools.EncodeSimple(buf, val2); err != nil {
		return err
	}
	if !val2 {
		if err = (*r.ProtobufDecoratorInfo).Encode(ctx, buf); err != nil {
			return err
		}
	}
	return err
}

func (r *SourceProviderInfo) Decode(ctx gobtools.EncContext, buf *bytes.Reader) error {
	var err error

	var val3 int32
	err = gobtools.DecodeSimple[int32](buf, &val3)
	if err != nil {
		return err
	}
	if val3 != -1 {
		r.Srcs = make([]android.Path, val3)
		for val4 := 0; val4 < int(val3); val4++ {
			if val6, err := gobtools.DecodeInterface(ctx, buf); err != nil {
				return err
			} else if val6 == nil {
				r.Srcs[val4] = nil
			} else {
				r.Srcs[val4] = val6.(android.Path)
			}
		}
	}

	var val8 bool
	if err = gobtools.DecodeSimple(buf, &val8); err != nil {
		return err
	}
	if !val8 {
		var val7 ProtobufDecoratorInfo
		if err = val7.Decode(ctx, buf); err != nil {
			return err
		}
		r.ProtobufDecoratorInfo = &val7
	}

	return err
}

var SourceProviderInfoGobRegId int16

func (r SourceProviderInfo) GetTypeId() int16 {
	return SourceProviderInfoGobRegId
}

func (r ProcMacroInfo) Encode(ctx gobtools.EncContext, buf *bytes.Buffer) error {
	var err error

	if err = gobtools.EncodeInterface(ctx, buf, r.Dylib); err != nil {
		return err
	}
	return err
}

func (r *ProcMacroInfo) Decode(ctx gobtools.EncContext, buf *bytes.Reader) error {
	var err error

	if val2, err := gobtools.DecodeInterface(ctx, buf); err != nil {
		return err
	} else if val2 == nil {
		r.Dylib = nil
	} else {
		r.Dylib = val2.(android.Path)
	}

	return err
}

var ProcMacroInfoGobRegId int16

func (r ProcMacroInfo) GetTypeId() int16 {
	return ProcMacroInfoGobRegId
}

func (r RustInfo) Encode(ctx gobtools.EncContext, buf *bytes.Buffer) error {
	var err error

	if err = gobtools.EncodeString(buf, r.AndroidMkSuffix); err != nil {
		return err
	}

	if err = gobtools.EncodeString(buf, r.RustSubName); err != nil {
		return err
	}

	if err = r.TransitiveAndroidMkSharedLibs.EncodeString(ctx, buf); err != nil {
		return err
	}

	val1 := r.CompilerInfo == nil
	if err = gobtools.EncodeSimple(buf, val1); err != nil {
		return err
	}
	if !val1 {
		if err = (*r.CompilerInfo).Encode(ctx, buf); err != nil {
			return err
		}
	}

	val2 := r.SnapshotInfo == nil
	if err = gobtools.EncodeSimple(buf, val2); err != nil {
		return err
	}
	if !val2 {
		if err = (*r.SnapshotInfo).Encode(ctx, buf); err != nil {
			return err
		}
	}

	val3 := r.SourceProviderInfo == nil
	if err = gobtools.EncodeSimple(buf, val3); err != nil {
		return err
	}
	if !val3 {
		if err = (*r.SourceProviderInfo).Encode(ctx, buf); err != nil {
			return err
		}
	}

	val4 := r.ProcMacroInfo == nil
	if err = gobtools.EncodeSimple(buf, val4); err != nil {
		return err
	}
	if !val4 {
		if err = (*r.ProcMacroInfo).Encode(ctx, buf); err != nil {
			return err
		}
	}

	if r.XrefRustFiles == nil {
		if err = gobtools.EncodeSimple(buf, int32(-1)); err != nil {
			return err
		}
	} else {
		if err = gobtools.EncodeSimple(buf, int32(len(r.XrefRustFiles))); err != nil {
			return err
		}
		for val5 := 0; val5 < len(r.XrefRustFiles); val5++ {
			if err = gobtools.EncodeInterface(ctx, buf, r.XrefRustFiles[val5]); err != nil {
				return err
			}
		}
	}

	if err = r.DocTimestampFile.Encode(ctx, buf); err != nil {
		return err
	}
	return err
}

func (r *RustInfo) Decode(ctx gobtools.EncContext, buf *bytes.Reader) error {
	var err error

	err = gobtools.DecodeString(buf, &r.AndroidMkSuffix)
	if err != nil {
		return err
	}

	err = gobtools.DecodeString(buf, &r.RustSubName)
	if err != nil {
		return err
	}

	if err = r.TransitiveAndroidMkSharedLibs.DecodeString(ctx, buf); err != nil {
		return err
	}

	var val5 bool
	if err = gobtools.DecodeSimple(buf, &val5); err != nil {
		return err
	}
	if !val5 {
		var val4 CompilerInfo
		if err = val4.Decode(ctx, buf); err != nil {
			return err
		}
		r.CompilerInfo = &val4
	}

	var val8 bool
	if err = gobtools.DecodeSimple(buf, &val8); err != nil {
		return err
	}
	if !val8 {
		var val7 cc.SnapshotInfo
		if err = val7.Decode(ctx, buf); err != nil {
			return err
		}
		r.SnapshotInfo = &val7
	}

	var val11 bool
	if err = gobtools.DecodeSimple(buf, &val11); err != nil {
		return err
	}
	if !val11 {
		var val10 SourceProviderInfo
		if err = val10.Decode(ctx, buf); err != nil {
			return err
		}
		r.SourceProviderInfo = &val10
	}

	var val14 bool
	if err = gobtools.DecodeSimple(buf, &val14); err != nil {
		return err
	}
	if !val14 {
		var val13 ProcMacroInfo
		if err = val13.Decode(ctx, buf); err != nil {
			return err
		}
		r.ProcMacroInfo = &val13
	}

	var val18 int32
	err = gobtools.DecodeSimple[int32](buf, &val18)
	if err != nil {
		return err
	}
	if val18 != -1 {
		r.XrefRustFiles = make([]android.Path, val18)
		for val19 := 0; val19 < int(val18); val19++ {
			if val21, err := gobtools.DecodeInterface(ctx, buf); err != nil {
				return err
			} else if val21 == nil {
				r.XrefRustFiles[val19] = nil
			} else {
				r.XrefRustFiles[val19] = val21.(android.Path)
			}
		}
	}

	if err = r.DocTimestampFile.Decode(ctx, buf); err != nil {
		return err
	}

	return err
}

var RustInfoGobRegId int16

func (r RustInfo) GetTypeId() int16 {
	return RustInfoGobRegId
}

func (r RustFlagExporterInfo) Encode(ctx gobtools.EncContext, buf *bytes.Buffer) error {
	var err error

	if r.Flags == nil {
		if err = gobtools.EncodeSimple(buf, int32(-1)); err != nil {
			return err
		}
	} else {
		if err = gobtools.EncodeSimple(buf, int32(len(r.Flags))); err != nil {
			return err
		}
		for val1 := 0; val1 < len(r.Flags); val1++ {
			if err = gobtools.EncodeString(buf, r.Flags[val1]); err != nil {
				return err
			}
		}
	}

	if r.LinkDirs == nil {
		if err = gobtools.EncodeSimple(buf, int32(-1)); err != nil {
			return err
		}
	} else {
		if err = gobtools.EncodeSimple(buf, int32(len(r.LinkDirs))); err != nil {
			return err
		}
		for val2 := 0; val2 < len(r.LinkDirs); val2++ {
			if err = gobtools.EncodeString(buf, r.LinkDirs[val2]); err != nil {
				return err
			}
		}
	}

	if r.RustLibObjects == nil {
		if err = gobtools.EncodeSimple(buf, int32(-1)); err != nil {
			return err
		}
	} else {
		if err = gobtools.EncodeSimple(buf, int32(len(r.RustLibObjects))); err != nil {
			return err
		}
		for val3 := 0; val3 < len(r.RustLibObjects); val3++ {
			if err = gobtools.EncodeString(buf, r.RustLibObjects[val3]); err != nil {
				return err
			}
		}
	}

	if r.StaticLibObjects == nil {
		if err = gobtools.EncodeSimple(buf, int32(-1)); err != nil {
			return err
		}
	} else {
		if err = gobtools.EncodeSimple(buf, int32(len(r.StaticLibObjects))); err != nil {
			return err
		}
		for val4 := 0; val4 < len(r.StaticLibObjects); val4++ {
			if err = gobtools.EncodeString(buf, r.StaticLibObjects[val4]); err != nil {
				return err
			}
		}
	}

	if r.WholeStaticLibObjects == nil {
		if err = gobtools.EncodeSimple(buf, int32(-1)); err != nil {
			return err
		}
	} else {
		if err = gobtools.EncodeSimple(buf, int32(len(r.WholeStaticLibObjects))); err != nil {
			return err
		}
		for val5 := 0; val5 < len(r.WholeStaticLibObjects); val5++ {
			if err = gobtools.EncodeString(buf, r.WholeStaticLibObjects[val5]); err != nil {
				return err
			}
		}
	}

	if r.SharedLibPaths == nil {
		if err = gobtools.EncodeSimple(buf, int32(-1)); err != nil {
			return err
		}
	} else {
		if err = gobtools.EncodeSimple(buf, int32(len(r.SharedLibPaths))); err != nil {
			return err
		}
		for val6 := 0; val6 < len(r.SharedLibPaths); val6++ {
			if err = gobtools.EncodeString(buf, r.SharedLibPaths[val6]); err != nil {
				return err
			}
		}
	}

	if r.WholeRustRlibDeps == nil {
		if err = gobtools.EncodeSimple(buf, int32(-1)); err != nil {
			return err
		}
	} else {
		if err = gobtools.EncodeSimple(buf, int32(len(r.WholeRustRlibDeps))); err != nil {
			return err
		}
		for val7 := 0; val7 < len(r.WholeRustRlibDeps); val7++ {
			if err = r.WholeRustRlibDeps[val7].Encode(ctx, buf); err != nil {
				return err
			}
		}
	}
	return err
}

func (r *RustFlagExporterInfo) Decode(ctx gobtools.EncContext, buf *bytes.Reader) error {
	var err error

	var val2 int32
	err = gobtools.DecodeSimple[int32](buf, &val2)
	if err != nil {
		return err
	}
	if val2 != -1 {
		r.Flags = make([]string, val2)
		for val3 := 0; val3 < int(val2); val3++ {
			err = gobtools.DecodeString(buf, &r.Flags[val3])
			if err != nil {
				return err
			}
		}
	}

	var val6 int32
	err = gobtools.DecodeSimple[int32](buf, &val6)
	if err != nil {
		return err
	}
	if val6 != -1 {
		r.LinkDirs = make([]string, val6)
		for val7 := 0; val7 < int(val6); val7++ {
			err = gobtools.DecodeString(buf, &r.LinkDirs[val7])
			if err != nil {
				return err
			}
		}
	}

	var val10 int32
	err = gobtools.DecodeSimple[int32](buf, &val10)
	if err != nil {
		return err
	}
	if val10 != -1 {
		r.RustLibObjects = make([]string, val10)
		for val11 := 0; val11 < int(val10); val11++ {
			err = gobtools.DecodeString(buf, &r.RustLibObjects[val11])
			if err != nil {
				return err
			}
		}
	}

	var val14 int32
	err = gobtools.DecodeSimple[int32](buf, &val14)
	if err != nil {
		return err
	}
	if val14 != -1 {
		r.StaticLibObjects = make([]string, val14)
		for val15 := 0; val15 < int(val14); val15++ {
			err = gobtools.DecodeString(buf, &r.StaticLibObjects[val15])
			if err != nil {
				return err
			}
		}
	}

	var val18 int32
	err = gobtools.DecodeSimple[int32](buf, &val18)
	if err != nil {
		return err
	}
	if val18 != -1 {
		r.WholeStaticLibObjects = make([]string, val18)
		for val19 := 0; val19 < int(val18); val19++ {
			err = gobtools.DecodeString(buf, &r.WholeStaticLibObjects[val19])
			if err != nil {
				return err
			}
		}
	}

	var val22 int32
	err = gobtools.DecodeSimple[int32](buf, &val22)
	if err != nil {
		return err
	}
	if val22 != -1 {
		r.SharedLibPaths = make([]string, val22)
		for val23 := 0; val23 < int(val22); val23++ {
			err = gobtools.DecodeString(buf, &r.SharedLibPaths[val23])
			if err != nil {
				return err
			}
		}
	}

	var val26 int32
	err = gobtools.DecodeSimple[int32](buf, &val26)
	if err != nil {
		return err
	}
	if val26 != -1 {
		r.WholeRustRlibDeps = make([]cc.RustRlibDep, val26)
		for val27 := 0; val27 < int(val26); val27++ {
			if err = r.WholeRustRlibDeps[val27].Decode(ctx, buf); err != nil {
				return err
			}
		}
	}

	return err
}

var RustFlagExporterInfoGobRegId int16

func (r RustFlagExporterInfo) GetTypeId() int16 {
	return RustFlagExporterInfoGobRegId
}

func (r RustImplementationDepInfo) Encode(ctx gobtools.EncContext, buf *bytes.Buffer) error {
	var err error

	if err = r.NonApexImplementationDeps.EncodeInterface(ctx, buf); err != nil {
		return err
	}
	return err
}

func (r *RustImplementationDepInfo) Decode(ctx gobtools.EncContext, buf *bytes.Reader) error {
	var err error

	if err = r.NonApexImplementationDeps.DecodeInterface(ctx, buf); err != nil {
		return err
	}

	return err
}

var RustImplementationDepInfoGobRegId int16

func (r RustImplementationDepInfo) GetTypeId() int16 {
	return RustImplementationDepInfoGobRegId
}
