// Code generated by go run gob_gen.go; DO NOT EDIT.

package provenance

import (
	"android/soong/android"
	"bytes"
	"github.com/google/blueprint/gobtools"
)

// begin of provenance_singleton.go
func init() {
	ProvenanceMetadataInfoGobRegId = gobtools.RegisterType(func() gobtools.CustomDec { return new(ProvenanceMetadataInfo) })
}

func (r ProvenanceMetadataInfo) Encode(ctx gobtools.EncContext, buf *bytes.Buffer) error {
	var err error

	if err = gobtools.EncodeInterface(ctx, buf, r.ProvenanceMetaDataFile); err != nil {
		return err
	}
	return err
}

func (r *ProvenanceMetadataInfo) Decode(ctx gobtools.EncContext, buf *bytes.Reader) error {
	var err error

	if val2, err := gobtools.DecodeInterface(ctx, buf); err != nil {
		return err
	} else if val2 == nil {
		r.ProvenanceMetaDataFile = nil
	} else {
		r.ProvenanceMetaDataFile = val2.(android.Path)
	}

	return err
}

var ProvenanceMetadataInfoGobRegId int16

func (r ProvenanceMetadataInfo) GetTypeId() int16 {
	return ProvenanceMetadataInfoGobRegId
}

// end of provenance_singleton.go
