// Code generated by go run gob_gen.go; DO NOT EDIT.

package dexpreopt

import (
	"android/soong/android"
	"bytes"
	"github.com/google/blueprint/gobtools"
)

func init() {
	ClassLoaderContextGobRegId = gobtools.RegisterType(func() gobtools.CustomDec { return new(ClassLoaderContext) })
}

func (r ClassLoaderContext) Encode(ctx gobtools.EncContext, buf *bytes.Buffer) error {
	var err error

	if err = gobtools.EncodeString(buf, r.Name); err != nil {
		return err
	}

	if err = gobtools.EncodeSimple(buf, r.Optional); err != nil {
		return err
	}

	if err = gobtools.EncodeInterface(ctx, buf, r.Host); err != nil {
		return err
	}

	if err = gobtools.EncodeString(buf, r.Device); err != nil {
		return err
	}

	if r.Subcontexts == nil {
		if err = gobtools.EncodeSimple(buf, int32(-1)); err != nil {
			return err
		}
	} else {
		if err = gobtools.EncodeSimple(buf, int32(len(r.Subcontexts))); err != nil {
			return err
		}
		for val1 := 0; val1 < len(r.Subcontexts); val1++ {
			val2 := r.Subcontexts[val1] == nil
			if err = gobtools.EncodeSimple(buf, val2); err != nil {
				return err
			}
			if !val2 {
				if err = (*r.Subcontexts[val1]).Encode(ctx, buf); err != nil {
					return err
				}
			}
		}
	}
	return err
}

func (r *ClassLoaderContext) Decode(ctx gobtools.EncContext, buf *bytes.Reader) error {
	var err error

	err = gobtools.DecodeString(buf, &r.Name)
	if err != nil {
		return err
	}

	err = gobtools.DecodeSimple[bool](buf, &r.Optional)
	if err != nil {
		return err
	}

	if val4, err := gobtools.DecodeInterface(ctx, buf); err != nil {
		return err
	} else if val4 == nil {
		r.Host = nil
	} else {
		r.Host = val4.(android.Path)
	}

	err = gobtools.DecodeString(buf, &r.Device)
	if err != nil {
		return err
	}

	var val7 int32
	err = gobtools.DecodeSimple[int32](buf, &val7)
	if err != nil {
		return err
	}
	if val7 != -1 {
		r.Subcontexts = make([]*ClassLoaderContext, val7)
		for val8 := 0; val8 < int(val7); val8++ {
			var val10 bool
			if err = gobtools.DecodeSimple(buf, &val10); err != nil {
				return err
			}
			if !val10 {
				var val9 ClassLoaderContext
				if err = val9.Decode(ctx, buf); err != nil {
					return err
				}
				r.Subcontexts[val8] = &val9
			}
		}
	}

	return err
}

var ClassLoaderContextGobRegId int16

func (r ClassLoaderContext) GetTypeId() int16 {
	return ClassLoaderContextGobRegId
}
